
var BlinkIDImageCaptureWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDImageCaptureWasmSDK) {
  BlinkIDImageCaptureWasmSDK = BlinkIDImageCaptureWasmSDK || {};


function g(){n.buffer!=t&&aa(n.buffer);return ba}function x(){n.buffer!=t&&aa(n.buffer);return da}function ea(){n.buffer!=t&&aa(n.buffer);return fa}function z(){n.buffer!=t&&aa(n.buffer);return ha}function A(){n.buffer!=t&&aa(n.buffer);return ia}function C(){n.buffer!=t&&aa(n.buffer);return ja}function ka(){n.buffer!=t&&aa(n.buffer);return la}function ma(){n.buffer!=t&&aa(n.buffer);return na}var E;E||(E=typeof BlinkIDImageCaptureWasmSDK !== 'undefined' ? BlinkIDImageCaptureWasmSDK : {});var oa,pa;
E.ready=new Promise(function(a,b){oa=a;pa=b});E.Uc||(E.Uc=0);E.Uc++;
(function(a){function b(m,q,p){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(u){var k=q;u.total&&(k=u.total);if(u.loaded){r.Dd?E.hc[m].loaded=u.loaded:(r.Dd=!0,E.hc||(E.hc={}),E.hc[m]={loaded:u.loaded,total:k});var v=k=u=0,y;for(y in E.hc){var B=E.hc[y];u+=B.total;k+=B.loaded;v++}u=Math.ceil(u*E.Uc/v);E.setStatus&&E.setStatus("Downloading data... ("+k+"/"+u+")")}else!E.hc&&E.setStatus&&E.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)p(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(u,k,v){this.start=u;this.end=k;this.audio=v}function q(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);m.prototype.Id=u;u=a.files;for(var k=
0;k<u.length;++k)m.prototype.ed[u[k].filename].onload();E.removeRunDependency("datafile_../../resources/advanced-threads/BlinkIDImageCaptureWasmSDK.data")}E.FS_createPath("/","microblink",!0,!0);m.prototype={ed:{},open:function(u,k){this.name=k;this.ed[k]=this;E.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Id.subarray(this.start,this.end))},finish:function(u){E.FS_createDataFile(this.name,null,u,!0,!0,!0);E.removeRunDependency("fp "+this.name);this.ed[this.name]=
null}};for(var p=a.files,r=0;r<p.length;++r)(new m(p[r].start,p[r].end,p[r].audio)).open("GET",p[r].filename);E.addRunDependency("datafile_../../resources/advanced-threads/BlinkIDImageCaptureWasmSDK.data");E.vd||(E.vd={});E.vd["../../resources/advanced-threads/BlinkIDImageCaptureWasmSDK.data"]={Ve:!1};l?(q(l),l=null):h=q}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==
typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof E.locateFilePackage||E.locateFile||(E.locateFile=E.locateFilePackage,F("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=E.locateFile?E.locateFile("BlinkIDImageCaptureWasmSDK.data",
""):"BlinkIDImageCaptureWasmSDK.data",f=a.remote_package_size,h=null,l=E.getPreloadedPackage?E.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);E.calledRun?d():(E.preRun||(E.preRun=[]),E.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_Detector_general_6.6.0.strop",start:0,end:290128,audio:0},{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",start:290128,end:294546,audio:0},{filename:"/microblink/BlinkID_Analyzer_general_6.5.0.strop",start:294546,
end:312596,audio:0},{filename:"/microblink/BlinkID_Classifier_general_6.13.0.strop",start:312596,end:750998,audio:0},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:750998,end:758488,audio:0},{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",start:758488,end:766042,audio:0},{filename:"/microblink/BlinkID_RotationClassifier_general_6.1.0.strop",start:766042,end:793948,audio:0},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",start:793948,end:1165084,
audio:0}],remote_package_size:1165084,package_uuid:"1e2c2830-9c00-427a-b19e-cddbb03851ac"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},qa;qa=E.allowedThreads&&0<E.allowedThreads?E.allowedThreads-1:navigator.hardwareConcurrency-1;var sa=0,ta;0<qa&&(E.threadWorkersReadyPromise=new Promise(function(a){ta=a}));E.preRun||(E.preRun=[]);E.preRun.push(function(a){function b(){sa++;sa==qa&&ta()}var c=a.PThread.$c;a.PThread.$c=function(d){c(d,b)}});
var ua={},va;for(va in E)E.hasOwnProperty(va)&&(ua[va]=E[va]);var wa="./this.program";function xa(a,b){throw b;}var ya=!1,za=!1,Aa=!1;ya="object"===typeof window;za="function"===typeof importScripts;Aa="object"===typeof process&&"object"===typeof process.Pe&&"string"===typeof process.Pe.node;var G=E.ENVIRONMENT_IS_PTHREAD||!1;G&&(t=E.buffer);var Ba="";function Ca(a){return E.locateFile?E.locateFile(a,Ba):Ba+a}var Da,Ea;
if(ya||za)za?Ba=self.location.href:"undefined"!==typeof document&&document.currentScript&&(Ba=document.currentScript.src),_scriptDir&&(Ba=_scriptDir),Ba=0!==Ba.indexOf("blob:")?Ba.substr(0,Ba.lastIndexOf("/")+1):"",Da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},za&&(Ea=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var Fa=E.print||console.log.bind(console),F=E.printErr||console.warn.bind(console);for(va in ua)ua.hasOwnProperty(va)&&(E[va]=ua[va]);ua=null;E.thisProgram&&(wa=E.thisProgram);E.quit&&(xa=E.quit);var Ga,Ha=0,Ia;E.wasmBinary&&(Ia=E.wasmBinary);var noExitRuntime=E.noExitRuntime||!0;"object"!==typeof WebAssembly&&H("no native wasm support detected");var n,Ja,Ka=!1;function La(a,b){a||H("Assertion failed: "+b)}
function Ma(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function K(a,b){return a?Ma(x(),a,b):""}
function Na(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function Oa(a,b,c){Na(a,x(),b,c)}
function Pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Qa(a,b){for(var c="",d=0;!(d>=b/2);++d){var e=ea()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Ra(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);ea()[b>>1]=f;b+=2}ea()[b>>1]=0;return b-d}
function Sa(a){return 2*a.length}function Ta(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ua(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Wa(a){var b=Pa(a)+1,c=L(b);c&&Na(a,g(),c,b);return c}function Xa(a,b){g().set(a,b)}var t,ba,da,fa,ha,ia,ja,la,na;function aa(a){t=a;E.HEAP8=ba=new Int8Array(a);E.HEAP16=fa=new Int16Array(a);E.HEAP32=ia=new Int32Array(a);E.HEAPU8=da=new Uint8Array(a);E.HEAPU16=ha=new Uint16Array(a);E.HEAPU32=ja=new Uint32Array(a);E.HEAPF32=la=new Float32Array(a);E.HEAPF64=na=new Float64Array(a)}
var Ya=E.INITIAL_MEMORY||209715200;
if(G)n=E.wasmMemory,t=E.buffer;else if(E.wasmMemory)n=E.wasmMemory;else if(n=new WebAssembly.Memory({initial:Ya/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),Aa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
n&&(t=n.buffer);Ya=t.byteLength;aa(t);var M,Za=[],$a=[],ab=[],bb=[];G||$a.push({Rd:function(){cb()}});function db(){G||(E.noFSInit||eb||(eb=!0,fb(),E.stdin=E.stdin,E.stdout=E.stdout,E.stderr=E.stderr,E.stdin?gb("/dev","stdin",E.stdin):hb("/dev/tty","/dev/stdin"),E.stdout?gb("/dev","stdout",null,E.stdout):hb("/dev/tty","/dev/stdout"),E.stderr?gb("/dev","stderr",null,E.stderr):hb("/dev/tty1","/dev/stderr"),ib("/dev/stdin",0),ib("/dev/stdout",1),ib("/dev/stderr",1)),jb($a))}
function kb(){var a=E.preRun.shift();Za.unshift(a)}var lb=0,mb=null,nb=null;function ob(){La(!G,"addRunDependency cannot be used in a pthread worker");lb++;E.monitorRunDependencies&&E.monitorRunDependencies(lb)}function pb(){lb--;E.monitorRunDependencies&&E.monitorRunDependencies(lb);if(0==lb&&(null!==mb&&(clearInterval(mb),mb=null),nb)){var a=nb;nb=null;a()}}E.preloadedImages={};E.preloadedAudios={};
function H(a){if(E.onAbort)E.onAbort(a);G&&console.error("Pthread aborting at "+Error().stack);a+="";F(a);Ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");pa(a);throw a;}function qb(){var a=rb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var rb="BlinkIDImageCaptureWasmSDK.wasm";qb()||(rb=Ca(rb));
function sb(){var a=rb;try{if(a==rb&&Ia)return new Uint8Array(Ia);if(Ea)return Ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){H(b)}}function tb(){return Ia||!ya&&!za||"function"!==typeof fetch?Promise.resolve().then(function(){return sb()}):fetch(rb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+rb+"'";return a.arrayBuffer()}).catch(function(){return sb()})}
var N,ub,wb={223538:function(a,b){a=K(a);b=K(b);throw Error(a+b);},223648:function(a,b,c,d){a=K(a);b=K(b);c=K(c);d=K(d);throw Error(a+b+c+d);},223864:function(a){a=K(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},224E3:function(a,b){a=K(a);b=K(b);console.log(a+b)},224098:function(a){throw Error(K(a));},224141:function(){throw"Canceled!";},224159:function(a,b){setTimeout(function(){vb(a,b)},0)},224238:function(){throw Error("Unable to perform that operation while recognizer is in use!");
}};function jb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(E);else{var c=b.Rd;"number"===typeof c?void 0===b.pc?M.get(c)():M.get(c)(b.pc):c(void 0===b.pc?null:b.pc)}}}
function xb(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),yb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),yb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}E._emscripten_futex_wake=xb;
function zb(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=O.Yb[a];b&&(A()[a+12>>2]=0,O.Kc(b.worker))}
var O={bc:[],cc:[],Ye:function(){},$d:function(){for(var a=L(228),b=0;57>b;++b)C()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=L(512);for(b=0;128>b;++b)C()[c/4+b]=0;Atomics.store(C(),a+100>>2,c);Atomics.store(C(),a+40>>2,a);Ab(a,!za,1);Bb(a)},ae:function(){O.receiveObjectTransfer=O.pe;O.setThreadStatus=O.ve;O.threadCancel=O.He;O.threadExit=O.Ie},Yb:{},Nc:[],ve:function(){},re:function(){for(;0<O.Nc.length;)O.Nc.pop()();G&&Cb()&&Db()},Ad:function(a,b){Atomics.store(C(),a+56>>2,1);Atomics.store(C(),
a+60>>2,0);O.re();Atomics.store(C(),a+4>>2,b);Atomics.store(C(),a+0>>2,1);xb(a+0,2147483647);Ab(0,0,0)},Ie:function(a){var b=Cb();b&&(O.Ad(b,a),G&&postMessage({cmd:"exit"}))},He:function(){O.Ad(Cb(),-1);postMessage({cmd:"cancelDone"})},Ge:function(){for(var a in O.Yb){var b=O.Yb[a];b&&b.worker&&O.Kc(b.worker)}O.Yb={};for(a=0;a<O.bc.length;++a){var c=O.bc[a];c.terminate()}O.bc=[];for(a=0;a<O.cc.length;++a)c=O.cc[a],b=c.Rb,O.Vc(b),c.terminate();O.cc=[]},Vc:function(a){if(a){if(a.Zb){var b=A()[a.Zb+
100>>2];A()[a.Zb+100>>2]=0;P(b);P(a.Zb)}a.Zb=0;a.Tc&&a.fc&&P(a.fc);a.fc=0;a.worker&&(a.worker.Rb=null)}},Kc:function(a){O.se(function(){delete O.Yb[a.Rb.Zb];O.bc.push(a);O.cc.splice(O.cc.indexOf(a),1);O.Vc(a.Rb);a.Rb=void 0})},se:function(a){A()[Eb>>2]=0;try{a()}finally{A()[Eb>>2]=1}},pe:function(){},$c:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.Rb&&(O.Md=a.Rb.Zb);if(d.targetThread&&d.targetThread!=Cb()){var f=O.Yb[d.ef];f?f.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+
e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Fb();else if("spawnThread"===e)Gb(c.data);else if("cleanupThread"===e)zb(d.thread);else if("killThread"===e){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+12>>2]=0;c=O.Yb[c];c.worker.terminate();O.Vc(c);O.cc.splice(O.cc.indexOf(c.worker),1);c.worker.Rb=
void 0}else if("cancelThread"===e){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.Yb[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.uc&&(a.uc(),delete a.uc);else if("print"===e)Fa("Thread "+d.threadId+": "+d.text);else if("printErr"===e)F("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===
e)a.Rb&&Atomics.load(C(),a.Rb.Zb+64>>2)&&O.Kc(a);else if("exitProcess"===e)try{Hb(d.returnCode)}catch(h){if(h instanceof Ib)return;throw h;}else"cancelDone"===e?O.Kc(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):F("worker sent an unknown command "+e));O.Md=void 0};a.onerror=function(c){F("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:E.mainScriptUrlOrBlob||_scriptDir,wasmMemory:n,wasmModule:Ja})},Ed:function(){var a=
Ca("BlinkIDImageCaptureWasmSDK.worker.js");O.bc.push(new Worker(a))},Td:function(){0==O.bc.length&&(O.Ed(),O.$c(O.bc[0]));return 0<O.bc.length?O.bc.pop():null},Re:function(a){for(a=performance.now()+a;performance.now()<a;);}};E.establishStackSpace=function(a,b){Jb(a,b);Q(a)};E.getNoExitRuntime=function(){return noExitRuntime};E.invokeEntryPoint=function(a,b){return M.get(a)(b)};var Kb;Kb=G?function(){return performance.now()-E.__performance_now_clock_drift}:function(){return performance.now()};
function Lb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Kb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0}function Mb(a){this.Gb=a-16;this.Ae=function(b){A()[this.Gb+8>>2]=b};this.xe=function(b){A()[this.Gb+0>>2]=b};this.ye=function(){A()[this.Gb+4>>2]=0};this.we=function(){var b=0;g()[this.Gb+12>>0]=b};this.ze=function(){var b=0;g()[this.Gb+13>>0]=b};this.rd=function(b,c){this.Ae(b);this.xe(c);this.ye();this.we();this.ze()}}var Nb=0;
function Ob(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(G)return R(2,1);if(!Ob.Jd){Ob.Jd=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Pb()>>2]=60*f;A()[Qb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Wa(c);d=Wa(d);e<b?(A()[Rb()>>2]=c,A()[Rb()+4>>2]=d):(A()[Rb()>>2]=d,A()[Rb()+4>>2]=c)}}
function Sb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Tb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ub(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Vb(a){if("/"===a)return"/";a=Tb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Wb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){H("randomDevice")}}
function Xb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Sb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Yb=[];function Zb(a,b){Yb[a]={input:[],Mb:[],mc:b};$b(a,ac)}
var ac={open:function(a){var b=Yb[a.node.sc];if(!b)throw new S(43);a.Jb=b;a.seekable=!1},close:function(a){a.Jb.mc.flush(a.Jb)},flush:function(a){a.Jb.mc.flush(a.Jb)},read:function(a,b,c,d){if(!a.Jb||!a.Jb.mc.qd)throw new S(60);for(var e=0,f=0;f<d;f++){try{var h=a.Jb.mc.qd(a.Jb)}catch(l){throw new S(29);}if(void 0===h&&0===e)throw new S(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Jb||!a.Jb.mc.ad)throw new S(60);try{for(var e=
0;e<d;e++)a.Jb.mc.ad(a.Jb,b[c+e])}catch(f){throw new S(29);}d&&(a.node.timestamp=Date.now());return e}},cc={qd:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=bc(b,!0)}return a.input.shift()},ad:function(a,b){null===b||10===b?(Fa(Ma(a.Mb,0)),a.Mb=[]):0!=b&&a.Mb.push(b)},flush:function(a){a.Mb&&0<a.Mb.length&&
(Fa(Ma(a.Mb,0)),a.Mb=[])}},dc={ad:function(a,b){null===b||10===b?(F(Ma(a.Mb,0)),a.Mb=[]):0!=b&&a.Mb.push(b)},flush:function(a){a.Mb&&0<a.Mb.length&&(F(Ma(a.Mb,0)),a.Mb=[])}},T={Xb:null,$b:function(){return T.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new S(63);T.Xb||(T.Xb={dir:{node:{Wb:T.Db.Wb,Pb:T.Db.Pb,qc:T.Db.qc,Gc:T.Db.Gc,zd:T.Db.zd,Rc:T.Db.Rc,Lc:T.Db.Lc,yd:T.Db.yd,Mc:T.Db.Mc},stream:{ec:T.Fb.ec}},file:{node:{Wb:T.Db.Wb,Pb:T.Db.Pb},
stream:{ec:T.Fb.ec,read:T.Fb.read,write:T.Fb.write,fd:T.Fb.fd,Hc:T.Fb.Hc,Ic:T.Fb.Ic}},link:{node:{Wb:T.Db.Wb,Pb:T.Db.Pb,tc:T.Db.tc},stream:{}},hd:{node:{Wb:T.Db.Wb,Pb:T.Db.Pb},stream:ec}});c=fc(a,b,c,d);gc(c.mode)?(c.Db=T.Xb.dir.node,c.Fb=T.Xb.dir.stream,c.Eb={}):32768===(c.mode&61440)?(c.Db=T.Xb.file.node,c.Fb=T.Xb.file.stream,c.Ib=0,c.Eb=null):40960===(c.mode&61440)?(c.Db=T.Xb.link.node,c.Fb=T.Xb.link.stream):8192===(c.mode&61440)&&(c.Db=T.Xb.hd.node,c.Fb=T.Xb.hd.stream);c.timestamp=Date.now();
a&&(a.Eb[b]=c,a.timestamp=c.timestamp);return c},We:function(a){return a.Eb?a.Eb.subarray?a.Eb.subarray(0,a.Ib):new Uint8Array(a.Eb):new Uint8Array(0)},nd:function(a,b){var c=a.Eb?a.Eb.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Eb,a.Eb=new Uint8Array(b),0<a.Ib&&a.Eb.set(c.subarray(0,a.Ib),0))},qe:function(a,b){if(a.Ib!=b)if(0==b)a.Eb=null,a.Ib=0;else{var c=a.Eb;a.Eb=new Uint8Array(b);c&&a.Eb.set(c.subarray(0,Math.min(b,a.Ib)));a.Ib=b}},Db:{Wb:function(a){var b=
{};b.Nd=8192===(a.mode&61440)?a.id:1;b.Xc=a.id;b.mode=a.mode;b.ke=1;b.uid=0;b.Xd=0;b.sc=a.sc;b.size=gc(a.mode)?4096:32768===(a.mode&61440)?a.Ib:40960===(a.mode&61440)?a.link.length:0;b.Fd=new Date(a.timestamp);b.je=new Date(a.timestamp);b.Ld=new Date(a.timestamp);b.Gd=4096;b.Hd=Math.ceil(b.size/b.Gd);return b},Pb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&T.qe(a,b.size)},qc:function(){throw hc[44];},Gc:function(a,b,c,d){return T.createNode(a,
b,c,d)},zd:function(a,b,c){if(gc(a.mode)){try{var d=ic(b,c)}catch(f){}if(d)for(var e in d.Eb)throw new S(55);}delete a.parent.Eb[a.name];a.parent.timestamp=Date.now();a.name=c;b.Eb[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Rc:function(a,b){delete a.Eb[b];a.timestamp=Date.now()},Lc:function(a,b){var c=ic(a,b),d;for(d in c.Eb)throw new S(55);delete a.Eb[b];a.timestamp=Date.now()},yd:function(a){var b=[".",".."],c;for(c in a.Eb)a.Eb.hasOwnProperty(c)&&b.push(c);return b},Mc:function(a,b,c){a=T.createNode(a,
b,41471,0);a.link=c;return a},tc:function(a){if(40960!==(a.mode&61440))throw new S(28);return a.link}},Fb:{read:function(a,b,c,d,e){var f=a.node.Eb;if(e>=a.node.Ib)return 0;a=Math.min(a.node.Ib-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Eb||a.Eb.subarray)){if(f)return a.Eb=b.subarray(c,c+d),a.Ib=d;if(0===a.Ib&&0===e)return a.Eb=
b.slice(c,c+d),a.Ib=d;if(e+d<=a.Ib)return a.Eb.set(b.subarray(c,c+d),e),d}T.nd(a,e+d);if(a.Eb.subarray&&b.subarray)a.Eb.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Eb[e+f]=b[c+f];a.Ib=Math.max(a.Ib,e+d);return d},ec:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ib);if(0>b)throw new S(28);return b},fd:function(a,b,c){T.nd(a.node,b+c);a.node.Ib=Math.max(a.node.Ib,b+c)},Hc:function(a,b,c,d,e,f){if(0!==b)throw new S(28);if(32768!==(a.node.mode&61440))throw new S(43);
a=a.node.Eb;if(f&2||a.buffer!==t){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=L(f);c<f;)g()[b+c++]=0;c=b;if(!c)throw new S(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{Gb:c,Sc:d}},Ic:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new S(43);if(e&2)return 0;T.Fb.write(a,b,0,d,c,!1);return 0}}},jc=null,kc={},lc=[],mc=1,nc=null,oc=!0,pc={},S=null,hc={};
function qc(a,b){a=Xb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={pd:!0,cd:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.cd)throw new S(32);a=Sb(a.split("/").filter(function(h){return!!h}),!1);var e=jc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ic(e,a[d]);c=Tb(c+"/"+a[d]);e.kc&&(!f||f&&b.pd)&&(e=e.kc.root);if(!f||b.Cc)for(f=0;40960===(e.mode&61440);)if(e=rc(c),c=Xb(Ub(c),e),e=qc(c,{cd:b.cd}).node,40<f++)throw new S(32);}return{path:c,node:e}}
function sc(a){for(var b;;){if(a===a.parent)return a=a.$b.td,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function tc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nc.length}function uc(a){var b=tc(a.parent.id,a.name);if(nc[b]===a)nc[b]=a.lc;else for(b=nc[b];b;){if(b.lc===a){b.lc=a.lc;break}b=b.lc}}
function ic(a,b){var c;if(c=(c=vc(a,"x"))?c:a.Db.qc?0:2)throw new S(c,a);for(c=nc[tc(a.id,b)];c;c=c.lc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Db.qc(a,b)}function fc(a,b,c,d){a=new wc(a,b,c,d);b=tc(a.parent.id,a.name);a.lc=nc[b];return nc[b]=a}function gc(a){return 16384===(a&61440)}var xc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function yc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function vc(a,b){if(oc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function zc(a,b){try{return ic(a,b),20}catch(c){}return vc(a,"wx")}function Ac(a,b,c){try{var d=ic(a,b)}catch(e){return e.Lb}if(a=vc(a,"wx"))return a;if(c){if(!gc(d.mode))return 54;if(d===d.parent||"/"===sc(d))return 10}else if(gc(d.mode))return 31;return 0}
function Bc(a){var b=4096;for(a=a||0;a<=b;a++)if(!lc[a])return a;throw new S(33);}function Cc(a,b){Dc||(Dc=function(){},Dc.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Dc,d;for(d in a)c[d]=a[d];a=c;b=Bc(b);a.Vb=b;return lc[b]=a}var ec={open:function(a){a.Fb=kc[a.node.sc].Fb;a.Fb.open&&a.Fb.open(a)},ec:function(){throw new S(70);}};function $b(a,b){kc[a]={Fb:b}}
function Ec(a,b){var c="/"===b,d=!b;if(c&&jc)throw new S(10);if(!c&&!d){var e=qc(b,{pd:!1});b=e.path;e=e.node;if(e.kc)throw new S(10);if(!gc(e.mode))throw new S(54);}b={type:a,bf:{},td:b,ie:[]};a=a.$b(b);a.$b=b;b.root=a;c?jc=a:e&&(e.kc=b,e.$b&&e.$b.ie.push(b))}function Fc(a,b,c){var d=qc(a,{parent:!0}).node;a=Vb(a);if(!a||"."===a||".."===a)throw new S(28);var e=zc(d,a);if(e)throw new S(e);if(!d.Db.Gc)throw new S(63);return d.Db.Gc(d,a,b,c)}function Gc(a){return Fc(a,16895,0)}
function Hc(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Fc(a,b|8192,c)}function hb(a,b){if(!Xb(a))throw new S(44);var c=qc(b,{parent:!0}).node;if(!c)throw new S(44);b=Vb(b);var d=zc(c,b);if(d)throw new S(d);if(!c.Db.Mc)throw new S(63);c.Db.Mc(c,b,a)}
function Ic(a){var b=qc(a,{parent:!0}).node,c=Vb(a),d=ic(b,c),e=Ac(b,c,!1);if(e)throw new S(e);if(!b.Db.Rc)throw new S(63);if(d.kc)throw new S(10);try{pc.willDeletePath&&pc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Db.Rc(b,c);uc(d);try{if(pc.onDeletePath)pc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function rc(a){a=qc(a).node;if(!a)throw new S(44);if(!a.Db.tc)throw new S(28);return Xb(sc(a.parent),a.Db.tc(a))}function Jc(a,b){a="string"===typeof a?qc(a,{Cc:!0}).node:a;if(!a.Db.Pb)throw new S(63);a.Db.Pb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ib(a,b,c,d){if(""===a)throw new S(44);if("string"===typeof b){var e=xc[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=Tb(a);try{f=qc(a,{Cc:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new S(20);}else f=Fc(a,c,0),e=!0;if(!f)throw new S(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!gc(f.mode))throw new S(54);if(!e&&(c=f?40960===(f.mode&61440)?32:gc(f.mode)&&
("r"!==yc(b)||b&512)?31:vc(f,yc(b)):44))throw new S(c);if(b&512){c=f;c="string"===typeof c?qc(c,{Cc:!0}).node:c;if(!c.Db.Pb)throw new S(63);if(gc(c.mode))throw new S(31);if(32768!==(c.mode&61440))throw new S(28);if(e=vc(c,"w"))throw new S(e);c.Db.Pb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Cc({node:f,path:sc(f),flags:b,seekable:!0,position:0,Fb:f.Fb,Oe:[],error:!1},d);d.Fb.open&&d.Fb.open(d);!E.logReadFiles||b&1||(Kc||(Kc={}),a in Kc||(Kc[a]=1,F("FS.trackingDelegate error on read file: "+a)));
try{pc.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),pc.onOpenFile(a,f))}catch(h){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Lc(a){if(null===a.Vb)throw new S(8);a.Wc&&(a.Wc=null);try{a.Fb.close&&a.Fb.close(a)}catch(b){throw b;}finally{lc[a.Vb]=null}a.Vb=null}function Mc(a,b,c){if(null===a.Vb)throw new S(8);if(!a.seekable||!a.Fb.ec)throw new S(70);if(0!=c&&1!=c&&2!=c)throw new S(28);a.position=a.Fb.ec(a,b,c);a.Oe=[]}
function Nc(a,b,c,d,e,f){if(0>d||0>e)throw new S(28);if(null===a.Vb)throw new S(8);if(0===(a.flags&2097155))throw new S(8);if(gc(a.node.mode))throw new S(31);if(!a.Fb.write)throw new S(28);a.seekable&&a.flags&1024&&Mc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new S(70);b=a.Fb.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&pc.onWriteToFile)pc.onWriteToFile(a.path)}catch(l){F("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function fb(){S||(S=function(a,b){this.node=b;this.ue=function(c){this.Lb=c};this.ue(a);this.message="FS error"},S.prototype=Error(),S.prototype.constructor=S,[44].forEach(function(a){hc[a]=new S(a);hc[a].stack="<generic error, no stack>"}))}var eb;function Oc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Pc(a,b){a="string"===typeof a?a:sc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Tb(a+"/"+c);try{Gc(d)}catch(e){}a=d}}return d}
function Qc(a,b,c,d){a=Tb(("string"===typeof a?a:sc(a))+"/"+b);c=Oc(c,d);return Fc(a,(void 0!==c?c:438)&4095|32768,0)}function Rc(a,b,c,d,e,f){a=b?Tb(("string"===typeof a?a:sc(a))+"/"+b):a;d=Oc(d,e);e=Fc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Jc(e,d|146);a=ib(e,577);Nc(a,c,0,c.length,0,f);Lc(a);Jc(e,d)}return e}
function gb(a,b,c,d){a=Tb(("string"===typeof a?a:sc(a))+"/"+b);b=Oc(!!c,!!d);gb.sd||(gb.sd=64);var e=gb.sd++<<8|0;$b(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var q=0,p=0;p<m;p++){try{var r=c()}catch(u){throw new S(29);}if(void 0===r&&0===q)throw new S(6);if(null===r||void 0===r)break;q++;h[l+p]=r}q&&(f.node.timestamp=Date.now());return q},write:function(f,h,l,m){for(var q=0;q<m;q++)try{d(h[l+q])}catch(p){throw new S(29);}m&&
(f.node.timestamp=Date.now());return q}});return Hc(a,b,e)}function Sc(a){if(!(a.ce||a.de||a.link||a.Eb)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(Da)try{a.Eb=bc(Da(a.url),!0),a.Ib=a.Eb.length}catch(b){throw new S(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function Tc(a,b,c,d,e){function f(){this.Zc=!1;this.Bc=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var r=p%this.jd;return this.Dc(p/this.jd|0)[r]}};f.prototype.te=function(p){this.Dc=p};f.prototype.gd=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var r=Number(p.getResponseHeader("Content-length")),u,k=(u=p.getResponseHeader("Accept-Ranges"))&&"bytes"===u;p=
(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;k||(v=r);var y=this;y.te(function(B){var I=B*v,J=(B+1)*v-1;J=Math.min(J,r-1);if("undefined"===typeof y.Bc[B]){var ra=y.Bc;if(I>J)throw Error("invalid range ("+I+", "+J+") or no bytes requested!");if(J>r-1)throw Error("only "+r+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);r!==v&&w.setRequestHeader("Range","bytes="+I+"-"+J);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);I=void 0!==w.response?new Uint8Array(w.response||[]):bc(w.responseText||"",!0);ra[B]=I}if("undefined"===typeof y.Bc[B])throw Error("doXHR failed!");return y.Bc[B]});if(p||!r)v=r=1,v=r=this.Dc(0).length,Fa("LazyFiles on gzip forces download of the whole file when length is accessed");this.Cd=r;this.Bd=v;this.Zc=!0};if("undefined"!==
typeof XMLHttpRequest){if(!za)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Zc||this.gd();return this.Cd}},jd:{get:function(){this.Zc||this.gd();return this.Bd}}});var l=void 0}else l=c,h=void 0;var m=Qc(a,b,d,e);h?m.Eb=h:l&&(m.Eb=null,m.url=l);Object.defineProperties(m,{Ib:{get:function(){return this.Eb.length}}});var q={};Object.keys(m.Fb).forEach(function(p){var r=
m.Fb[p];q[p]=function(){Sc(m);return r.apply(null,arguments)}});q.read=function(p,r,u,k,v){Sc(m);p=p.node.Eb;if(v>=p.length)return 0;k=Math.min(p.length-v,k);if(p.slice)for(var y=0;y<k;y++)r[u+y]=p[v+y];else for(y=0;y<k;y++)r[u+y]=p.get(v+y);return k};m.Fb=q;return m}
function Uc(a,b,c,d,e,f,h,l,m,q){function p(k){function v(B){q&&q();l||Rc(a,b,B,d,e,m);f&&f();pb(u)}var y=!1;E.preloadPlugins.forEach(function(B){!y&&B.canHandle(r)&&(B.handle(k,r,v,function(){h&&h();pb(u)}),y=!0)});y||v(k)}Vc.rd();var r=b?Xb(Tb(a+"/"+b)):a,u="cp "+r;ob(u);"string"==typeof c?Vc.Qe(c,function(k){p(k)},h):p(c)}var U={},Dc,Kc,Wc={};
function Xc(a,b){try{var c=qc(a,{Cc:!0}).node;if(!c)throw new S(44);if(!c.Db.Wb)throw new S(63);var d=c.Db.Wb(c)}catch(e){if(e&&e.node&&Tb(a)!==Tb(sc(e.node)))return-54;throw e;}A()[b>>2]=d.Nd;A()[b+4>>2]=0;A()[b+8>>2]=d.Xc;A()[b+12>>2]=d.mode;A()[b+16>>2]=d.ke;A()[b+20>>2]=d.uid;A()[b+24>>2]=d.Xd;A()[b+28>>2]=d.sc;A()[b+32>>2]=0;ub=[d.size>>>0,(N=d.size,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+40>>2]=ub[0];A()[b+
44>>2]=ub[1];A()[b+48>>2]=4096;A()[b+52>>2]=d.Hd;A()[b+56>>2]=d.Fd.getTime()/1E3|0;A()[b+60>>2]=0;A()[b+64>>2]=d.je.getTime()/1E3|0;A()[b+68>>2]=0;A()[b+72>>2]=d.Ld.getTime()/1E3|0;A()[b+76>>2]=0;ub=[d.Xc>>>0,(N=d.Xc,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[b+80>>2]=ub[0];A()[b+84>>2]=ub[1];return 0}var Yc=void 0;function Zc(){Yc+=4;return A()[Yc-4>>2]}function $c(a){a=lc[a];if(!a)throw new S(8);return a}
function ad(a,b,c){if(G)return R(3,1,a,b,c);Yc=c;try{var d=$c(a);switch(b){case 0:var e=Zc();return 0>e?-28:ib(d.path,d.flags,0,e).Vb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Zc(),d.flags|=e,0;case 12:return e=Zc(),ea()[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Lb}}
function bd(a,b){if(G)return R(4,1,a,b);try{var c=$c(a);return Xc(c.path,b)}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),-d.Lb}}
function cd(a,b,c){if(G)return R(5,1,a,b,c);Yc=c;try{var d=$c(a);switch(b){case 21509:case 21505:return d.Jb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Jb?0:-59;case 21519:if(!d.Jb)return-59;var e=Zc();return A()[e>>2]=0;case 21520:return d.Jb?-28:-59;case 21531:a=e=Zc();if(!d.Fb.be)throw new S(59);return d.Fb.be(d,b,a);case 21523:return d.Jb?0:-59;case 21524:return d.Jb?0:-59;default:H("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof U&&f instanceof
S||H(f),-f.Lb}}
function dd(a,b,c,d,e,f){if(G)return R(6,1,a,b,c,d,e,f);try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=ed(16384,b);if(!m){l=-48;break a}fd(m,0,b);h=!0}else{var q=lc[e];if(!q){l=-8;break a}var p=f;if(0!==(c&2)&&0===(d&2)&&2!==(q.flags&2097155))throw new S(2);if(1===(q.flags&2097155))throw new S(2);if(!q.Fb.Hc)throw new S(43);var r=q.Fb.Hc(q,a,b,p,c,d);m=r.Gb;h=r.Sc}Wc[m]={he:m,fe:b,Sc:h,Vb:e,me:c,flags:d,offset:f};l=m}}return l}catch(u){return"undefined"!==typeof U&&
u instanceof S||H(u),-u.Lb}}function gd(a,b){if(G)return R(7,1,a,b);try{if(-1===(a|0)||0===b)var c=-28;else{var d=Wc[a];if(d&&b===d.fe){var e=lc[d.Vb];if(e&&d.me&2){var f=d.flags,h=d.offset,l=x().slice(a,a+b);e&&e.Fb.Ic&&e.Fb.Ic(e,l,h,b,f)}Wc[a]=null;d.Sc&&P(d.he)}c=0}return c}catch(m){return"undefined"!==typeof U&&m instanceof S||H(m),-m.Lb}}
function hd(a,b,c){if(G)return R(8,1,a,b,c);Yc=c;try{var d=K(a),e=c?Zc():0;return ib(d,b,e).Vb}catch(f){return"undefined"!==typeof U&&f instanceof S||H(f),-f.Lb}}
function id(a){if(G)return R(9,1,a);try{a=K(a);var b=qc(a,{parent:!0}).node,c=Vb(a),d=ic(b,c),e=Ac(b,c,!0);if(e)throw new S(e);if(!b.Db.Lc)throw new S(63);if(d.kc)throw new S(10);try{pc.willDeletePath&&pc.willDeletePath(a)}catch(f){F("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Db.Lc(b,c);uc(d);try{if(pc.onDeletePath)pc.onDeletePath(a)}catch(f){F("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==
typeof U&&f instanceof S||H(f),-f.Lb}}function jd(a,b){if(G)return R(10,1,a,b);try{return a=K(a),Xc(a,b)}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),-c.Lb}}function kd(a){if(G)return R(11,1,a);try{return a=K(a),Ic(a),0}catch(b){return"undefined"!==typeof U&&b instanceof S||H(b),-b.Lb}}var ld={};function md(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function nd(a){return this.fromWireType(C()[a>>2])}var od={},pd={},qd={};
function rd(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function sd(a,b){a=rd(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function td(a){var b=Error,c=sd(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var ud=void 0;function vd(a){throw new ud(a);}
function wd(a,b,c){function d(l){l=c(l);l.length!==a.length&&vd("Mismatched type converter count");for(var m=0;m<a.length;++m)xd(a[m],l[m])}a.forEach(function(l){qd[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){pd.hasOwnProperty(l)?e[m]=pd[l]:(f.push(l),od.hasOwnProperty(l)||(od[l]=[]),od[l].push(function(){e[m]=pd[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function yd(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var zd=void 0;function V(a){for(var b="";x()[a];)b+=zd[x()[a++]];return b}var Ad=void 0;function X(a){throw new Ad(a);}
function xd(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(pd.hasOwnProperty(a)){if(c.Yd)return;X("Cannot register type '"+d+"' twice")}pd[a]=b;delete qd[a];od.hasOwnProperty(a)&&(b=od[a],delete od[a],b.forEach(function(e){e()}))}function Bd(a){return{count:a.count,ic:a.ic,rc:a.rc,Gb:a.Gb,Kb:a.Kb,Qb:a.Qb,Sb:a.Sb}}
function Cd(a){X(a.Cb.Kb.Hb.name+" instance already deleted")}var Dd=!1;function Ed(){}function Fd(a){--a.count.value;0===a.count.value&&(a.Qb?a.Sb.ac(a.Qb):a.Kb.Hb.ac(a.Gb))}
function Gd(a){if("undefined"===typeof FinalizationGroup)return Gd=function(b){return b},a;Dd=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Gb?Fd(c):console.warn("object already deleted: "+c.Gb)});Gd=function(b){Dd.register(b,b.Cb,b.Cb);return b};Ed=function(b){Dd.unregister(b.Cb)};return Gd(a)}var Hd=void 0,Id=[];function Jd(){for(;Id.length;){var a=Id.pop();a.Cb.ic=!1;a["delete"]()}}function Kd(){}var Ld={};
function Md(a,b,c){if(void 0===a[b].Nb){var d=a[b];a[b]=function(){a[b].Nb.hasOwnProperty(arguments.length)||X("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Nb+")!");return a[b].Nb[arguments.length].apply(this,arguments)};a[b].Nb=[];a[b].Nb[d.zc]=d}}
function Nd(a,b,c){E.hasOwnProperty(a)?((void 0===c||void 0!==E[a].Nb&&void 0!==E[a].Nb[c])&&X("Cannot register public name '"+a+"' twice"),Md(E,a,a),E.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),E[a].Nb[c]=b):(E[a]=b,void 0!==c&&(E[a].af=c))}function Od(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.jc=c;this.ac=d;this.Tb=e;this.Sd=f;this.wc=h;this.Od=l;this.ne=[]}
function Pd(a,b,c){for(;b!==c;)b.wc||X("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.wc(a),b=b.Tb;return a}function Qd(a,b){if(null===b)return this.Yc&&X("null is not a valid "+this.name),0;b.Cb||X('Cannot pass "'+Rd(b)+'" as a '+this.name);b.Cb.Gb||X("Cannot pass deleted object as a pointer of type "+this.name);return Pd(b.Cb.Gb,b.Cb.Kb.Hb,this.Hb)}
function Sd(a,b){if(null===b){this.Yc&&X("null is not a valid "+this.name);if(this.Fc){var c=this.bd();null!==a&&a.push(this.ac,c);return c}return 0}b.Cb||X('Cannot pass "'+Rd(b)+'" as a '+this.name);b.Cb.Gb||X("Cannot pass deleted object as a pointer of type "+this.name);!this.Ec&&b.Cb.Kb.Ec&&X("Cannot convert argument of type "+(b.Cb.Sb?b.Cb.Sb.name:b.Cb.Kb.name)+" to parameter type "+this.name);c=Pd(b.Cb.Gb,b.Cb.Kb.Hb,this.Hb);if(this.Fc)switch(void 0===b.Cb.Qb&&X("Passing raw pointer to smart pointer is illegal"),
this.Ee){case 0:b.Cb.Sb===this?c=b.Cb.Qb:X("Cannot convert argument of type "+(b.Cb.Sb?b.Cb.Sb.name:b.Cb.Kb.name)+" to parameter type "+this.name);break;case 1:c=b.Cb.Qb;break;case 2:if(b.Cb.Sb===this)c=b.Cb.Qb;else{var d=b.clone();c=this.oe(c,Y(function(){d["delete"]()}));null!==a&&a.push(this.ac,c)}break;default:X("Unsupporting sharing policy")}return c}
function Td(a,b){if(null===b)return this.Yc&&X("null is not a valid "+this.name),0;b.Cb||X('Cannot pass "'+Rd(b)+'" as a '+this.name);b.Cb.Gb||X("Cannot pass deleted object as a pointer of type "+this.name);b.Cb.Kb.Ec&&X("Cannot convert argument of type "+b.Cb.Kb.name+" to parameter type "+this.name);return Pd(b.Cb.Gb,b.Cb.Kb.Hb,this.Hb)}function Ud(a,b,c){if(b===c)return a;if(void 0===c.Tb)return null;a=Ud(a,b,c.Tb);return null===a?null:c.Od(a)}var Vd={};
function Wd(a,b){for(void 0===b&&X("ptr should not be undefined");a.Tb;)b=a.wc(b),a=a.Tb;return Vd[b]}function Xd(a,b){b.Kb&&b.Gb||vd("makeClassHandle requires ptr and ptrType");!!b.Sb!==!!b.Qb&&vd("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Gd(Object.create(a,{Cb:{value:b}}))}
function Yd(a,b,c,d){this.name=a;this.Hb=b;this.Yc=c;this.Ec=d;this.Fc=!1;this.ac=this.oe=this.bd=this.xd=this.Ee=this.le=void 0;void 0!==b.Tb?this.toWireType=Sd:(this.toWireType=d?Qd:Td,this.Ub=null)}function Zd(a,b,c){E.hasOwnProperty(a)||vd("Replacing nonexistant public symbol");void 0!==E[a].Nb&&void 0!==c?E[a].Nb[c]=b:(E[a]=b,E[a].zc=c)}
function $d(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=E["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function ae(a,b){a=V(a);var c=-1!=a.indexOf("j")?$d(a,b):M.get(b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var be=void 0;function ce(a){a=de(a);var b=V(a);P(a);return b}
function ee(a,b){function c(f){e[f]||pd[f]||(qd[f]?qd[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new be(a+": "+d.map(ce).join([", "]));}function fe(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function ge(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=sd(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function he(a,b,c,d,e){var f=b.length;2>f&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Ub){l=!0;break}var m="void"!==b[0].name,q="",p="";for(c=0;c<f-2;++c)q+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+rd(a)+"("+q+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[X,d,e,md,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",q.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Ub&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",q.push(f+"_dtor"),d.push(b[c].Ub));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(a+"}\n");return ge(q).apply(null,d)}var ie=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function je(a){4<a&&0===--Z[a].dd&&(Z[a]=void 0,ie.push(a))}
function Y(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ie.length?ie.pop():Z.length;Z[b]={dd:1,value:a};return b}}function Rd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ke(a,b){switch(b){case 2:return function(c){return this.fromWireType(ka()[c>>2])};case 3:return function(c){return this.fromWireType(ma()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function le(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return x()[d]};case 1:return c?function(d){return ea()[d>>1]}:function(d){return z()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return C()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function me(a){a||X("Cannot use deleted val. handle = "+a);return Z[a].value}function ne(a,b){var c=pd[a];void 0===c&&X(b+" has unknown type "+ce(a));return c}
function oe(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=ne(A()[(b>>2)+d],"parameter "+d);return c}var pe={};function qe(a){var b=pe[a];return void 0===b?V(a):b}var re=[];function se(){return"object"===typeof globalThis?globalThis:Function("return this")()}function te(a){var b=re.length;re.push(a);return b}var ue={};
function ve(){za||(Ga||(Ga={}),Ga["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ga["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function we(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(ya){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),yb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),yb>>2,0),-73;d=Atomics.exchange(A(),yb>>2,0);if(0==d)break;Fb();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),yb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function R(a,b){for(var c=arguments.length-2,d=xe(),e=ye(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];ma()[f+h]=l}c=ze(a,c,e,b);Q(d);return c}var Ae=[],Be=[],Ce=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function De(a){a=2<a?K(a):a;return Ce[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ee(a,b,c){var d=De(a);if(!d)return-4;d.Ac&&(A()[d.Ac>>2]=b,A()[d.Ac+4>>2]=c);if(d.ud||!d.Te)d.ud&&(d=d.ud),a=!1,d.yc&&d.yc.xc&&(a=d.yc.xc.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.yc.xc.viewport(0,0,b,c);else{if(d.Ac){d=A()[d.Ac+8>>2];a=a?K(a):"";var e=xe(),f=ye(12),h=0;if(a){h=Pa(a)+1;var l=L(h);Oa(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;Fe(0,d,657457152,0,h,f);Q(e);return 1}return-4}return 0}
function Ge(a,b,c){return G?R(12,1,a,b,c):Ee(a,b,c)}var He=[];function Ie(a,b){C()[a>>2]=b;C()[a+4>>2]=b/4294967296|0}function Je(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var Ke;
function Le(a,b,c,d,e){function f(D){var ca=0,W=0;D&&(W=w.response?w.response.byteLength:0,ca=L(W),x().set(new Uint8Array(w.response),ca));C()[a+12>>2]=ca;Ie(a+16,W)}var h=C()[a+8>>2];if(h){var l=K(h),m=a+112,q=K(m);q||(q="GET");C();var p=C()[m+52>>2],r=C()[m+56>>2],u=!!C()[m+60>>2];C();var k=C()[m+68>>2],v=C()[m+72>>2],y=C()[m+76>>2],B=C()[m+80>>2];h=C()[m+84>>2];m=C()[m+88>>2];var I=!!(p&1),J=!!(p&2);p=!!(p&64);k=k?K(k):void 0;v=v?K(v):void 0;var ra=B?K(B):void 0,w=new XMLHttpRequest;w.withCredentials=
u;w.open(q,l,!p,k,v);p||(w.timeout=r);w.gf=l;w.responseType="arraybuffer";B&&w.overrideMimeType(ra);if(y)for(;;){q=C()[y>>2];if(!q)break;l=C()[y+4>>2];if(!l)break;y+=8;q=K(q);l=K(l);w.setRequestHeader(q,l)}He.push(w);y=He.length;C()[a+0>>2]=y;h=h&&m?x().slice(h,h+m):null;w.onload=function(D){f(I&&!J);var ca=w.response?w.response.byteLength:0;Ie(a+24,0);ca&&Ie(a+32,ca);z()[a+40>>1]=w.readyState;z()[a+42>>1]=w.status;w.statusText&&Oa(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,D):c&&
c(a,w,D)};w.onerror=function(D){f(I);var ca=w.status;Ie(a+24,0);Ie(a+32,w.response?w.response.byteLength:0);z()[a+40>>1]=w.readyState;z()[a+42>>1]=ca;c&&c(a,w,D)};w.ontimeout=function(D){c&&c(a,w,D)};w.onprogress=function(D){var ca=I&&J&&w.response?w.response.byteLength:0,W=0;I&&J&&(W=L(ca),x().set(new Uint8Array(w.response),W));C()[a+12>>2]=W;Ie(a+16,ca);Ie(a+24,D.loaded-ca);Ie(a+32,D.total);z()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<D.loaded&&(w.status=200);z()[a+42>>1]=w.status;
w.statusText&&Oa(w.statusText,a+44,64);d&&d(a,w,D);W&&P(W)};w.onreadystatechange=function(D){z()[a+40>>1]=w.readyState;2<=w.readyState&&(z()[a+42>>1]=w.status);e&&e(a,w,D)};try{w.send(h)}catch(D){c&&c(a,w,D)}}else c(a,0,"no url specified!")}
function Me(a,b,c,d){var e=Ke;if(e){var f=a+112;(f=C()[f+64>>2])||(f=C()[a+8>>2]);var h=K(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){z()[a+40>>1]=4;z()[a+42>>1]=200;Oa("OK",a+44,64);c(a,0,h)};l.onerror=function(m){z()[a+40>>1]=4;z()[a+42>>1]=413;Oa("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ne(a,b,c){var d=Ke;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=L(l);x().set(new Uint8Array(h),m);C()[a+12>>2]=m;Ie(a+16,l);Ie(a+24,0);Ie(a+32,l);z()[a+40>>1]=4;z()[a+42>>1]=200;Oa("OK",a+44,64);b(a,0,h)}else z()[a+40>>1]=4,z()[a+42>>1]=404,Oa("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){z()[a+
40>>1]=4;z()[a+42>>1]=404;Oa("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Oe(a,b,c){var d=Ke;if(d){var e=a+112;(e=C()[e+64>>2])||(e=C()[a+8>>2]);e=K(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;C()[a+12>>2]=0;Ie(a+16,0);Ie(a+24,0);Ie(a+32,0);z()[a+40>>1]=4;z()[a+42>>1]=200;Oa("OK",a+44,64);b(a,0,h)};f.onerror=function(h){z()[a+40>>1]=4;z()[a+42>>1]=404;Oa("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Pe(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Qe(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Re(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Se(a){a||(a=Te);if(!a.Zd){a.Zd=!0;var b=a.xc;Pe(b);Qe(b);Re(b);b.Ue=b.getExtension("EXT_disjoint_timer_query");b.$e=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var Te,Ue=["default","low-power","high-performance"],Ve={};
function We(){if(!Xe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:wa||"./this.program"},b;for(b in Ve)a[b]=Ve[b];var c=[];for(b in a)c.push(b+"="+a[b]);Xe=c}return Xe}var Xe;
function Ye(a,b){if(G)return R(13,1,a,b);try{var c=0;We().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof U&&d instanceof S||H(d),d.Lb}}function Ze(a,b){if(G)return R(14,1,a,b);try{var c=We();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Lb}}
function $e(a){if(G)return R(15,1,a);try{var b=$c(a);Lc(b);return 0}catch(c){return"undefined"!==typeof U&&c instanceof S||H(c),c.Lb}}function af(a,b){if(G)return R(16,1,a,b);try{var c=$c(a),d=c.Jb?2:gc(c.mode)?3:40960===(c.mode&61440)?7:4;g()[b>>0]=d;return 0}catch(e){return"undefined"!==typeof U&&e instanceof S||H(e),e.Lb}}
function bf(a,b,c,d){if(G)return R(17,1,a,b,c,d);try{a:{for(var e=$c(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,q=g(),p=h,r=l,u=void 0;if(0>r||0>u)throw new S(28);if(null===m.Vb)throw new S(8);if(1===(m.flags&2097155))throw new S(8);if(gc(m.node.mode))throw new S(31);if(!m.Fb.read)throw new S(28);var k="undefined"!==typeof u;if(!k)u=m.position;else if(!m.seekable)throw new S(70);var v=m.Fb.read(m,q,p,r,u);k||(m.position+=v);var y=v;if(0>y){var B=-1;break a}a+=y;if(y<l)break}B=a}A()[d>>
2]=B;return 0}catch(I){return"undefined"!==typeof U&&I instanceof S||H(I),I.Lb}}
function cf(a,b,c,d,e){if(G)return R(18,1,a,b,c,d,e);try{var f=$c(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Mc(f,a,d);ub=[f.position>>>0,(N=f.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];A()[e>>2]=ub[0];A()[e+4>>2]=ub[1];f.Wc&&0===a&&0===d&&(f.Wc=null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof S||H(h),h.Lb}}
function df(a,b,c,d){if(G)return R(19,1,a,b,c,d);try{a:{for(var e=$c(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=Nc(e,g(),h,l,void 0);if(0>m){var q=-1;break a}a+=m}q=a}A()[d>>2]=q;return 0}catch(p){return"undefined"!==typeof U&&p instanceof S||H(p),p.Lb}}function ef(a,b){ef.wd||(ef.wd=Wb());for(var c=0;c<b;c++)g()[a+c>>0]=ef.wd();return 0}
function Gb(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Td();if(void 0!==b.Rb)throw"Internal error!";if(!a.Jc)throw"Internal error, no pthread ptr!";O.cc.push(b);for(var c=L(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var e=a.fc+a.nc;d=O.Yb[a.Jc]={worker:b,fc:a.fc,nc:a.nc,Tc:a.Tc,Zb:a.Jc};var f=d.Zb>>2;Atomics.store(C(),f+16,a.ld);Atomics.store(C(),f+25,c);Atomics.store(C(),f+10,d.Zb);Atomics.store(C(),f+20,a.nc);Atomics.store(C(),f+19,e);Atomics.store(C(),
f+26,a.nc);Atomics.store(C(),f+28,e);Atomics.store(C(),f+29,a.ld);c=ff()+40;Atomics.store(C(),f+43,c);b.Rb=d;var h={cmd:"run",start_routine:a.Fe,arg:a.pc,threadInfoStruct:a.Jc,stackBase:a.fc,stackSize:a.nc};b.uc=function(){h.time=performance.now();b.postMessage(h,a.Ne)};b.loaded&&(b.uc(),delete b.uc)}
function gf(a,b){if(!a)return F("pthread_join attempted on a null thread pointer!"),71;if(G&&Cb()==a)return F("PThread "+a+" is attempting to join to itself!"),16;if(!G&&hf()==a)return F("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return F("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(C(),a+64>>2))return F("Attempted to join thread "+a+", which was already detached!"),28;for(ve();;){var c=
Atomics.load(C(),a+0>>2);if(1==c)return c=Atomics.load(C(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(C(),a+64>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):zb(a),0;if(G){var d=Cb();if(d&&!Atomics.load(C(),d+56>>2)&&2==Atomics.load(C(),d+0>>2))throw"Canceled!";}G||Fb();we(a+0,c,G?100:1)}}function jf(a){return 0===a%4&&(0!==a%100||0===a%400)}function kf(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var lf=[31,29,31,30,31,30,31,31,30,31,30,31],mf=[31,28,31,30,31,30,31,31,30,31,30,31];
function nf(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(jf(a.getFullYear())?lf:mf)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function of(a,b,c,d){function e(k,v,y){for(k="number"===typeof k?k.toString():k||"";k.length<v;)k=y[0]+k;return k}function f(k,v){return e(k,v,"0")}function h(k,v){function y(I){return 0>I?-1:0<I?1:0}var B;0===(B=y(k.getFullYear()-v.getFullYear()))&&0===(B=y(k.getMonth()-v.getMonth()))&&(B=y(k.getDate()-v.getDate()));return B}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=nf(new Date(k.Ob+1900,0,1),k.Qc);var v=new Date(k.getFullYear()+1,0,4),y=l(new Date(k.getFullYear(),0,4));v=l(v);return 0>=h(y,k)?0>=h(v,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=A()[d+40>>2];d={Le:A()[d>>2],Ke:A()[d+4>>2],Oc:A()[d+8>>2],vc:A()[d+12>>2],oc:A()[d+16>>2],Ob:A()[d+20>>2],Pc:A()[d+24>>2],Qc:A()[d+28>>2],ff:A()[d+
32>>2],Je:A()[d+36>>2],Me:q?K(q):""};c=K(c);q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)c=c.replace(new RegExp(p,"g"),q[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return r[k.Pc].substring(0,3)},"%A":function(k){return r[k.Pc]},"%b":function(k){return u[k.oc].substring(0,3)},"%B":function(k){return u[k.oc]},"%C":function(k){return f((k.Ob+1900)/100|0,2)},"%d":function(k){return f(k.vc,2)},"%e":function(k){return e(k.vc,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Oc,
2)},"%I":function(k){k=k.Oc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.vc+kf(jf(k.Ob+1900)?lf:mf,k.oc-1),3)},"%m":function(k){return f(k.oc+1,2)},"%M":function(k){return f(k.Ke,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Oc&&12>k.Oc?"AM":"PM"},"%S":function(k){return f(k.Le,2)},"%t":function(){return"\t"},"%u":function(k){return k.Pc||7},"%U":function(k){var v=new Date(k.Ob+1900,0,1),y=0===v.getDay()?v:nf(v,7-v.getDay());k=new Date(k.Ob+1900,k.oc,k.vc);return 0>
h(y,k)?f(Math.ceil((31-y.getDate()+(kf(jf(k.getFullYear())?lf:mf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(y,v)?"01":"00"},"%V":function(k){var v=new Date(k.Ob+1901,0,4),y=l(new Date(k.Ob+1900,0,4));v=l(v);var B=nf(new Date(k.Ob+1900,0,1),k.Qc);return 0>h(B,y)?"53":0>=h(v,B)?"01":f(Math.ceil((y.getFullYear()<k.Ob+1900?k.Qc+32-y.getDate():k.Qc+1-y.getDate())/7),2)},"%w":function(k){return k.Pc},"%W":function(k){var v=new Date(k.Ob,0,1),y=1===v.getDay()?v:nf(v,0===v.getDay()?1:7-v.getDay()+1);k=
new Date(k.Ob+1900,k.oc,k.vc);return 0>h(y,k)?f(Math.ceil((31-y.getDate()+(kf(jf(k.getFullYear())?lf:mf,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(y,v)?"01":"00"},"%y":function(k){return(k.Ob+1900).toString().substring(2)},"%Y":function(k){return k.Ob+1900},"%z":function(k){k=k.Je;var v=0<=k;k=Math.abs(k)/60;return(v?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.Me},"%%":function(){return"%"}};for(p in q)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),q[p](d)));p=
bc(c,!1);if(p.length>b)return 0;Xa(p,a);return p.length-1}
function pf(a){if(G)return R(20,1,a);switch(a){case 30:return 16384;case 85:return 51200;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;
case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||
1:1}return-1}function wc(a,b,c,d){a||(a=this);this.parent=a;this.$b=a.$b;this.kc=null;this.id=mc++;this.name=b;this.mode=c;this.Db={};this.Fb={};this.sc=d}Object.defineProperties(wc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},de:{get:function(){return gc(this.mode)}},ce:{get:function(){return 8192===(this.mode&61440)}}});fb();
nc=Array(4096);Ec(T,"/");Gc("/tmp");Gc("/home");Gc("/home/web_user");(function(){Gc("/dev");$b(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Hc("/dev/null",259);Zb(1280,cc);Zb(1536,dc);Hc("/dev/tty",1280);Hc("/dev/tty1",1536);var a=Wb();gb("/dev","random",a);gb("/dev","urandom",a);Gc("/dev/shm");Gc("/dev/shm/tmp")})();
(function(){Gc("/proc");var a=Gc("/proc/self");Gc("/proc/self/fd");Ec({$b:function(){var b=fc(a,"fd",16895,73);b.Db={qc:function(c,d){var e=lc[+d];if(!e)throw new S(8);c={parent:null,$b:{td:"fake"},Db:{tc:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Vc;E.FS_createPath=Pc;E.FS_createDataFile=Rc;E.FS_createPreloadedFile=Uc;E.FS_createLazyFile=Tc;E.FS_createDevice=gb;E.FS_unlink=Ic;ud=E.InternalError=td("InternalError");
for(var qf=Array(256),rf=0;256>rf;++rf)qf[rf]=String.fromCharCode(rf);zd=qf;Ad=E.BindingError=td("BindingError");Kd.prototype.isAliasOf=function(a){if(!(this instanceof Kd&&a instanceof Kd))return!1;var b=this.Cb.Kb.Hb,c=this.Cb.Gb,d=a.Cb.Kb.Hb;for(a=a.Cb.Gb;b.Tb;)c=b.wc(c),b=b.Tb;for(;d.Tb;)a=d.wc(a),d=d.Tb;return b===d&&c===a};
Kd.prototype.clone=function(){this.Cb.Gb||Cd(this);if(this.Cb.rc)return this.Cb.count.value+=1,this;var a=Gd(Object.create(Object.getPrototypeOf(this),{Cb:{value:Bd(this.Cb)}}));a.Cb.count.value+=1;a.Cb.ic=!1;return a};Kd.prototype["delete"]=function(){this.Cb.Gb||Cd(this);this.Cb.ic&&!this.Cb.rc&&X("Object already scheduled for deletion");Ed(this);Fd(this.Cb);this.Cb.rc||(this.Cb.Qb=void 0,this.Cb.Gb=void 0)};Kd.prototype.isDeleted=function(){return!this.Cb.Gb};
Kd.prototype.deleteLater=function(){this.Cb.Gb||Cd(this);this.Cb.ic&&!this.Cb.rc&&X("Object already scheduled for deletion");Id.push(this);1===Id.length&&Hd&&Hd(Jd);this.Cb.ic=!0;return this};Yd.prototype.Ud=function(a){this.xd&&(a=this.xd(a));return a};Yd.prototype.kd=function(a){this.ac&&this.ac(a)};Yd.prototype.argPackAdvance=8;Yd.prototype.readValueFromPointer=nd;Yd.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Yd.prototype.fromWireType=function(a){function b(){return this.Fc?Xd(this.Hb.jc,{Kb:this.le,Gb:c,Sb:this,Qb:a}):Xd(this.Hb.jc,{Kb:this,Gb:a})}var c=this.Ud(a);if(!c)return this.kd(a),null;var d=Wd(this.Hb,c);if(void 0!==d){if(0===d.Cb.count.value)return d.Cb.Gb=c,d.Cb.Qb=a,d.clone();d=d.clone();this.kd(a);return d}d=this.Hb.Sd(c);d=Ld[d];if(!d)return b.call(this);d=this.Ec?d.Kd:d.pointerType;var e=Ud(c,this.Hb,d.Hb);return null===e?b.call(this):this.Fc?Xd(d.Hb.jc,{Kb:d,Gb:e,Sb:this,Qb:a}):Xd(d.Hb.jc,
{Kb:d,Gb:e})};E.getInheritedInstanceCount=function(){return Object.keys(Vd).length};E.getLiveInheritedInstances=function(){var a=[],b;for(b in Vd)Vd.hasOwnProperty(b)&&a.push(Vd[b]);return a};E.flushPendingDeletes=Jd;E.setDelayFunction=function(a){Hd=a;Id.length&&Hd&&Hd(Jd)};be=E.UnboundTypeError=td("UnboundTypeError");E.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};E.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
G||(Je(function(a){Ke=a;pb("library_fetch_init")},function(){Ke=!1;pb("library_fetch_init")}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||ob("library_fetch_init"));var sf=[null,function(a,b){if(G)return R(1,1,a,b)},Ob,ad,bd,cd,dd,gd,hd,id,jd,kd,Ge,Ye,Ze,$e,af,bf,cf,df,pf];function bc(a,b){var c=Array(Pa(a)+1);a=Na(a,c,0,c.length);b&&(c.length=a);return c}
var Gf={o:function(a,b,c,d){H("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,d?K(d):"unknown function"])},wa:function(a,b){return Lb(a,b)},E:function(a){return L(a+16)+16},D:function(a,b,c){(new Mb(a)).rd(b,c);Nb++;throw a;},va:function(a,b){Ob();a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),
0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Rb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},W:ad,Aa:bd,ya:cd,Da:dd,Ca:function(){return 0},Ba:gd,B:hd,xa:id,za:jd,T:kd,i:function(a){var b=ld[a];delete ld[a];var c=b.bd,d=b.ac,e=b.od,f=e.map(function(h){return h.Wd}).concat(e.map(function(h){return h.Ce}));wd([a],
f,function(h){var l={};e.forEach(function(m,q){var p=h[q],r=m.Dc,u=m.Vd,k=h[q+e.length],v=m.Be,y=m.De;l[m.Qd]={read:function(B){return p.fromWireType(r(u,B))},write:function(B,I){var J=[];v(y,B,k.toWireType(J,I));md(J)}}});return[{name:b.name,fromWireType:function(m){var q={},p;for(p in l)q[p]=l[p].read(m);d(m);return q},toWireType:function(m,q){for(var p in l)if(!(p in q))throw new TypeError('Missing field:  "'+p+'"');var r=c();for(p in l)l[p].write(r,q[p]);null!==m&&m.push(d,r);return r},argPackAdvance:8,
readValueFromPointer:nd,Ub:d}]})},Fa:function(a,b,c,d,e){var f=yd(c);b=V(b);xd(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=ea();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},Ub:null})},I:function(a,b,c,d,e,f,h,l,m,q,p,r,u){p=V(p);f=ae(e,f);l&&(l=ae(h,l));q&&(q=ae(m,q));u=ae(r,u);var k=rd(p);Nd(k,function(){ee("Cannot construct "+
p+" due to unbound types",[d])});wd([a,b,c],d?[d]:[],function(v){v=v[0];if(d){var y=v.Hb;var B=y.jc}else B=Kd.prototype;v=sd(k,function(){if(Object.getPrototypeOf(this)!==I)throw new Ad("Use 'new' to construct "+p);if(void 0===J.dc)throw new Ad(p+" has no accessible constructor");var w=J.dc[arguments.length];if(void 0===w)throw new Ad("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.dc).toString()+") parameters instead!");return w.apply(this,
arguments)});var I=Object.create(B,{constructor:{value:v}});v.prototype=I;var J=new Od(p,v,I,u,y,f,l,q);y=new Yd(p,J,!0,!1);B=new Yd(p+"*",J,!1,!1);var ra=new Yd(p+" const*",J,!1,!0);Ld[a]={pointerType:B,Kd:ra};Zd(k,v);return[y,B,ra]})},aa:function(a,b,c,d,e,f){La(0<b);var h=fe(b,c);e=ae(d,e);var l=[f],m=[];wd([],[a],function(q){q=q[0];var p="constructor "+q.name;void 0===q.Hb.dc&&(q.Hb.dc=[]);if(void 0!==q.Hb.dc[b-1])throw new Ad("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+q.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");q.Hb.dc[b-1]=function(){ee("Cannot construct "+q.name+" due to unbound types",h)};wd([],h,function(r){q.Hb.dc[b-1]=function(){arguments.length!==b-1&&X(p+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var u=1;u<b;++u)l[u]=r[u].toWireType(m,arguments[u-1]);u=e.apply(null,l);md(m);return r[0].fromWireType(u)};return[]});return[]})},
s:function(a,b,c,d,e,f,h,l){var m=fe(c,d);b=V(b);f=ae(e,f);wd([],[a],function(q){function p(){ee("Cannot call "+r+" due to unbound types",m)}q=q[0];var r=q.name+"."+b;l&&q.Hb.ne.push(b);var u=q.Hb.jc,k=u[b];void 0===k||void 0===k.Nb&&k.className!==q.name&&k.zc===c-2?(p.zc=c-2,p.className=q.name,u[b]=p):(Md(u,b,r),u[b].Nb[c-2]=p);wd([],m,function(v){v=he(r,v,q,f,h);void 0===u[b].Nb?(v.zc=c-2,u[b]=v):u[b].Nb[c-2]=v;return[]});return[]})},Ea:function(a,b){b=V(b);xd(a,{name:b,fromWireType:function(c){var d=
Z[c].value;je(c);return d},toWireType:function(c,d){return Y(d)},argPackAdvance:8,readValueFromPointer:nd,Ub:null})},X:function(a,b,c){c=yd(c);b=V(b);xd(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Rd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:ke(b,c),Ub:null})},H:function(a,b,c,d,e,f){var h=fe(b,c);a=V(a);e=ae(d,e);Nd(a,function(){ee("Cannot call "+a+" due to unbound types",
h)},b-1);wd([],h,function(l){Zd(a,he(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},l:function(a,b,c,d,e){function f(q){return q}b=V(b);-1===e&&(e=4294967295);var h=yd(c);if(0===d){var l=32-8*c;f=function(q){return q<<l>>>l}}var m=-1!=b.indexOf("unsigned");xd(a,{name:b,fromWireType:f,toWireType:function(q,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Rd(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Rd(p)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:le(b,h,0!==d),Ub:null})},k:function(a,b,c){function d(f){f>>=2;var h=C();return new e(t,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=V(c);xd(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Yd:!0})},Y:function(a,b){b=V(b);var c="std::string"===b;xd(a,{name:b,fromWireType:function(d){var e=C()[d>>
2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==x()[l]){f=K(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(x()[d+4+h]);m=m.join("")}P(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||X("Cannot pass non-string to std::string");var h=(c&&f?function(){return Pa(e)}:
function(){return e.length})(),l=L(4+h+1);C()[l>>2]=h;if(c&&f)Oa(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(P(l),X("String has UTF-16 code units that do not fit in 8 bits"));x()[l+4+f]=m}else for(f=0;f<h;++f)x()[l+4+f]=e[f];null!==d&&d.push(P,l);return l},argPackAdvance:8,readValueFromPointer:nd,Ub:function(d){P(d)}})},C:function(a,b,c){c=V(c);if(2===b){var d=Qa;var e=Ra;var f=Sa;var h=function(){return z()};var l=1}else 4===b&&(d=Ta,e=Ua,f=Va,h=function(){return C()},l=2);
xd(a,{name:c,fromWireType:function(m){for(var q=C()[m>>2],p=h(),r,u=m+4,k=0;k<=q;++k){var v=m+4+k*b;if(k==q||0==p[v>>l])u=d(u,v-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=v+b}P(m);return r},toWireType:function(m,q){"string"!==typeof q&&X("Cannot pass non-string to C++ string type "+c);var p=f(q),r=L(4+p+b);C()[r>>2]=p>>l;e(q,r+4,p+b);null!==m&&m.push(P,r);return r},argPackAdvance:8,readValueFromPointer:nd,Ub:function(m){P(m)}})},j:function(a,b,c,d,e,f){ld[a]={name:V(b),bd:ae(c,d),ac:ae(e,
f),od:[]}},e:function(a,b,c,d,e,f,h,l,m,q){ld[a].od.push({Qd:V(b),Wd:c,Dc:ae(d,e),Vd:f,Ce:h,Be:ae(l,m),De:q})},Ga:function(a,b){b=V(b);xd(a,{ee:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},Ha:function(a){delete He[a-1]},pa:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.Yb[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},u:function(a,
b,c){a=me(a);b=ne(b,"emval::as");var d=[],e=Y(d);A()[c>>2]=e;return b.toWireType(d,a)},Qa:function(a,b,c,d){a=me(a);c=oe(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return Y(a)},x:function(a,b,c,d){a=re[a];b=me(b);c=qe(c);a(b,c,null,d)},O:je,Ra:function(a,b){a=me(a);b=me(b);return a==b},Oa:function(a){if(0===a)return Y(se());a=qe(a);return Y(se()[a])},w:function(a,b){b=oe(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(q){return q.name}).join("_")+
"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+rd("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.ee||(d+="    return retType.toWireType(destructors, rv);\n");
e.push(d+"};\n");a=ge(e).apply(null,f);return te(a)},Pa:function(a){a=qe(a);return Y(E[a])},q:function(a,b){a=me(a);b=me(b);return Y(a[b])},ba:function(a){4<a&&(Z[a].dd+=1)},G:function(a,b,c,d){a=me(a);var e=ue[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+
f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(ne,E,Y);ue[b]=e}return e(a,c,d)},Ma:function(){return Y([])},Va:function(a){return Y(qe(a))},Na:function(){return Y({})},Ta:function(a){md(Z[a].value);je(a)},A:function(a,b,c){a=me(a);b=me(b);c=me(c);a[b]=c},t:function(a,b){a=ne(a,"_emval_take_value");a=a.readValueFromPointer(b);
return Y(a)},Sa:function(a){a=me(a);return Y(typeof a)},m:function(){H()},K:function(){var a=E.allowedThreads;return a?a:navigator.hardwareConcurrency},P:Lb,p:function(a,b,c){Be.length=0;var d;for(c>>=2;d=x()[b++];)(d=105>d)&&c&1&&c++,Be.push(d?ma()[c++>>1]:A()[c]),++c;return wb[a].apply(null,Be)},ra:ve,R:function(){},v:we,r:xb,y:Kb,J:function(){return"undefined"!==typeof SharedArrayBuffer},d:function(a,b){tf(a,b||1);throw"longjmp";},ha:function(a,b,c){x().copyWithin(a,b,b+c)},ma:function(a,b,c){Ae.length=
b;c>>=3;for(var d=0;d<b;d++)Ae[d]=ma()[c+d];return(0>a?wb[-a-1]:sf[a]).apply(null,Ae)},ia:function(a){var b=x().length;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-t.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},na:function(a,b,c){return De(a)?Ee(a,b,c):Ge(a,b,c)},Q:function(){},Ia:function(a,b,c,d,e){function f(D){Le(D,
h,q,p,m)}function h(D,ca){Me(D,ca.response,function(W){v?M.get(v)(W):b&&b(W)},function(W){v?M.get(v)(W):b&&b(W)})}function l(D){Le(D,r,q,p,m)}function m(D){I?M.get(I)(D):e&&e(D)}function q(D){y?M.get(y)(D):c&&c(D)}function p(D){B?M.get(B)(D):d&&d(D)}function r(D){v?M.get(v)(D):b&&b(D)}noExitRuntime=!0;var u=a+112,k=K(u),v=C()[u+36>>2],y=C()[u+40>>2],B=C()[u+44>>2],I=C()[u+48>>2],J=C()[u+52>>2],ra=!!(J&4),w=!!(J&32);J=!!(J&16);if("EM_IDB_STORE"===k)k=C()[u+84>>2],Me(a,x().slice(k,k+C()[u+88>>2]),r,
q);else if("EM_IDB_DELETE"===k)Oe(a,r,q);else if(J){if(w)return 0;Le(a,ra?h:r,q,p,m)}else Ne(a,r,w?q:ra?f:l);return a},oa:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Ue[c],failIfMajorPerformanceCaveat:!!A()[b+7],ge:A()[b+8],Ze:A()[b+9],md:A()[b+10],Pd:A()[b+11],cf:A()[b+12],df:A()[b+13]};a=De(a);if(!a||b.Pd)b=0;else if(a=a.getContext("webgl",b)){c=L(8);
A()[c+4>>2]=Cb();var d={Xe:c,attributes:b,version:b.ge,xc:a};a.canvas&&(a.canvas.yc=d);("undefined"===typeof b.md||b.md)&&Se(d);b=c}else b=0;return b},ta:Ye,ua:Ze,F:function(a){Hb(a)},z:$e,sa:af,V:bf,Ua:cf,U:df,b:function(){return Ha|0},La:function(){var a=self.navigator.userAgent,b=Pa(a)+1,c=L(b);Oa(a,c,b);return c},ka:ef,ga:function(){O.$d()},L:uf,h:vf,n:wf,N:xf,fa:yf,f:zf,g:Af,M:Bf,ea:Cf,da:Df,ca:Ef,a:n||E.wasmMemory,Ka:function(a){Ob();var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],
A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();
return b.getTime()/1E3|0},qa:function(a){var b=O.Nc.pop();a&&b()},S:function(a,b){O.Nc.push(function(){M.get(a)(b)})},Z:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return F("pthread_create called with a null thread pointer!"),28;var e=[];if(G&&0===e.length)return Ff(687865856,a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;
(b=0==f)?f=ed(16,l):(f-=l,La(0<f));for(var m=L(228),q=0;57>q;++q)C()[(m>>2)+q]=0;A()[a>>2]=m;A()[m+12>>2]=m;a=m+152;A()[a>>2]=a;c={fc:f,nc:l,Tc:b,ld:h,Fe:c,Jc:m,pc:d,Ne:e};G?(c.Se="spawnThread",postMessage(c,e)):Gb(c);return 0},Ja:function(a,b){return gf(a,b)},c:function(a){Ha=a|0},_:of,la:function(a,b,c,d){return of(a,b,c,d)},ja:pf,$:function(a){var b=Date.now()/1E3|0;a&&(A()[a>>2]=b);return b}};
(function(){function a(e,f){E.asm=e.exports;M=E.asm._a;Ja=f;G||pb("wasm-instantiate")}function b(e){a(e.instance,e.module)}function c(e){return tb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);H(f)})}var d={a:Gf};G||ob("wasm-instantiate");if(E.instantiateWasm)try{return E.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Ia||"function"!==typeof WebAssembly.instantiateStreaming||
qb()||"function"!==typeof fetch?c(b):fetch(rb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(pa);return{}})();
var cb=E.___wasm_call_ctors=function(){return(cb=E.___wasm_call_ctors=E.asm.Wa).apply(null,arguments)},P=E._free=function(){return(P=E._free=E.asm.Xa).apply(null,arguments)},L=E._malloc=function(){return(L=E._malloc=E.asm.Ya).apply(null,arguments)},Cb=E._pthread_self=function(){return(Cb=E._pthread_self=E.asm.Za).apply(null,arguments)},de=E.___getTypeName=function(){return(de=E.___getTypeName=E.asm.$a).apply(null,arguments)};
E.___embind_register_native_and_builtin_types=function(){return(E.___embind_register_native_and_builtin_types=E.asm.ab).apply(null,arguments)};
var ff=E._emscripten_get_global_libc=function(){return(ff=E._emscripten_get_global_libc=E.asm.bb).apply(null,arguments)},fd=E._memset=function(){return(fd=E._memset=E.asm.cb).apply(null,arguments)},Rb=E.__get_tzname=function(){return(Rb=E.__get_tzname=E.asm.db).apply(null,arguments)},Qb=E.__get_daylight=function(){return(Qb=E.__get_daylight=E.asm.eb).apply(null,arguments)},Pb=E.__get_timezone=function(){return(Pb=E.__get_timezone=E.asm.fb).apply(null,arguments)},hf=E._emscripten_main_browser_thread_id=
function(){return(hf=E._emscripten_main_browser_thread_id=E.asm.gb).apply(null,arguments)},Db=E.___pthread_tsd_run_dtors=function(){return(Db=E.___pthread_tsd_run_dtors=E.asm.hb).apply(null,arguments)},Fb=E._emscripten_main_thread_process_queued_calls=function(){return(Fb=E._emscripten_main_thread_process_queued_calls=E.asm.ib).apply(null,arguments)};E._emscripten_current_thread_process_queued_calls=function(){return(E._emscripten_current_thread_process_queued_calls=E.asm.jb).apply(null,arguments)};
var Bb=E._emscripten_register_main_browser_thread_id=function(){return(Bb=E._emscripten_register_main_browser_thread_id=E.asm.kb).apply(null,arguments)},vb=E.__emscripten_do_dispatch_to_thread=function(){return(vb=E.__emscripten_do_dispatch_to_thread=E.asm.lb).apply(null,arguments)},Ff=E._emscripten_sync_run_in_main_thread_4=function(){return(Ff=E._emscripten_sync_run_in_main_thread_4=E.asm.mb).apply(null,arguments)},ze=E._emscripten_run_in_main_runtime_thread_js=function(){return(ze=E._emscripten_run_in_main_runtime_thread_js=
E.asm.nb).apply(null,arguments)},Fe=E.__emscripten_call_on_thread=function(){return(Fe=E.__emscripten_call_on_thread=E.asm.ob).apply(null,arguments)};E._emscripten_tls_init=function(){return(E._emscripten_tls_init=E.asm.pb).apply(null,arguments)};
var Ab=E.__emscripten_thread_init=function(){return(Ab=E.__emscripten_thread_init=E.asm.qb).apply(null,arguments)},xe=E.stackSave=function(){return(xe=E.stackSave=E.asm.rb).apply(null,arguments)},Q=E.stackRestore=function(){return(Q=E.stackRestore=E.asm.sb).apply(null,arguments)},ye=E.stackAlloc=function(){return(ye=E.stackAlloc=E.asm.tb).apply(null,arguments)},Jb=E._emscripten_stack_set_limits=function(){return(Jb=E._emscripten_stack_set_limits=E.asm.ub).apply(null,arguments)},tf=E._setThrew=function(){return(tf=
E._setThrew=E.asm.vb).apply(null,arguments)},ed=E._memalign=function(){return(ed=E._memalign=E.asm.wb).apply(null,arguments)};E.dynCall_jiji=function(){return(E.dynCall_jiji=E.asm.xb).apply(null,arguments)};E.dynCall_viijii=function(){return(E.dynCall_viijii=E.asm.yb).apply(null,arguments)};E.dynCall_iiiiiijj=function(){return(E.dynCall_iiiiiijj=E.asm.zb).apply(null,arguments)};E.dynCall_iiiiij=function(){return(E.dynCall_iiiiij=E.asm.Ab).apply(null,arguments)};
E.dynCall_iiiiijj=function(){return(E.dynCall_iiiiijj=E.asm.Bb).apply(null,arguments)};var Eb=E.__emscripten_allow_main_runtime_queued_calls=223012,yb=E.__emscripten_main_thread_futex=822120;function zf(a,b){var c=xe();try{M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;tf(1,0)}}function vf(a,b){var c=xe();try{return M.get(a)(b)}catch(d){Q(c);if(d!==d+0&&"longjmp"!==d)throw d;tf(1,0)}}
function Af(a,b,c){var d=xe();try{M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;tf(1,0)}}function wf(a,b,c){var d=xe();try{return M.get(a)(b,c)}catch(e){Q(d);if(e!==e+0&&"longjmp"!==e)throw e;tf(1,0)}}function xf(a,b,c,d){var e=xe();try{return M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;tf(1,0)}}function Bf(a,b,c,d){var e=xe();try{M.get(a)(b,c,d)}catch(f){Q(e);if(f!==f+0&&"longjmp"!==f)throw f;tf(1,0)}}
function yf(a,b,c,d,e){var f=xe();try{return M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;tf(1,0)}}function Cf(a,b,c,d,e){var f=xe();try{M.get(a)(b,c,d,e)}catch(h){Q(f);if(h!==h+0&&"longjmp"!==h)throw h;tf(1,0)}}function uf(a){var b=xe();try{return M.get(a)()}catch(c){Q(b);if(c!==c+0&&"longjmp"!==c)throw c;tf(1,0)}}function Df(a,b,c,d,e,f,h){var l=xe();try{M.get(a)(b,c,d,e,f,h)}catch(m){Q(l);if(m!==m+0&&"longjmp"!==m)throw m;tf(1,0)}}
function Ef(a,b,c,d,e,f,h,l,m,q){var p=xe();try{M.get(a)(b,c,d,e,f,h,l,m,q)}catch(r){Q(p);if(r!==r+0&&"longjmp"!==r)throw r;tf(1,0)}}E.addRunDependency=ob;E.removeRunDependency=pb;E.FS_createPath=Pc;E.FS_createDataFile=Rc;E.FS_createPreloadedFile=Uc;E.FS_createLazyFile=Tc;E.FS_createDevice=gb;E.FS_unlink=Ic;E.PThread=O;E.PThread=O;E.wasmMemory=n;E.ExitStatus=Ib;var Hf;function Ib(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}
nb=function If(){Hf||Jf();Hf||(nb=If)};
function Jf(){function a(){if(!Hf&&(Hf=!0,E.calledRun=!0,!Ka)){db();G||(oc=!1,jb(ab));oa(E);if(E.onRuntimeInitialized)E.onRuntimeInitialized();if(!G){if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;){var b=E.postRun.shift();bb.unshift(b)}jb(bb)}}}if(!(0<lb))if(G)oa(E),db(),postMessage({cmd:"loaded"});else{if(!G){if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)kb();jb(Za)}0<lb||(E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){E.setStatus("")},
1);a()},1)):a())}}E.run=Jf;function Hb(a){if(G)throw postMessage({cmd:"exitProcess",returnCode:a}),new Ib(a);if(!noExitRuntime){O.Ge();if(E.onExit)E.onExit(a);Ka=!0}xa(a,new Ib(a))}if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.pop()();G&&(noExitRuntime=!1,O.ae());Jf();


  return BlinkIDImageCaptureWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDImageCaptureWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDImageCaptureWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDImageCaptureWasmSDK"] = BlinkIDImageCaptureWasmSDK;
