
var BlinkIDImageCaptureWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDImageCaptureWasmSDK) {
  BlinkIDImageCaptureWasmSDK = BlinkIDImageCaptureWasmSDK || {};


var g;g||(g=typeof BlinkIDImageCaptureWasmSDK !== 'undefined' ? BlinkIDImageCaptureWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Nb||(g.Nb=0);g.Nb++;
(function(a){function b(m,p,n){var r=new XMLHttpRequest;r.open("GET",m,!0);r.responseType="arraybuffer";r.onprogress=function(v){var k=p;v.total&&(k=v.total);if(v.loaded){r.qc?g.kb[m].loaded=v.loaded:(r.qc=!0,g.kb||(g.kb={}),g.kb[m]={loaded:v.loaded,total:k});var u=k=v=0,x;for(x in g.kb){var y=g.kb[x];v+=y.total;k+=y.loaded;u++}v=Math.ceil(v*g.Nb/u);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+v+")")}else!g.kb&&g.setStatus&&g.setStatus("Downloading data...")};r.onerror=function(){throw Error("NetworkError for: "+
m);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)n(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.uc=v;v=a.files;for(var k=
0;k<v.length;++k)m.prototype.Wb[v[k].filename].onload();g.removeRunDependency("datafile_../../resources/advanced/BlinkIDImageCaptureWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Wb:{},open:function(v,k){this.name=k;this.Wb[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.uc.subarray(this.start,this.end))},finish:function(v){g.FS_createDataFile(this.name,null,v,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.Wb[this.name]=
null}};for(var n=a.files,r=0;r<n.length;++r)(new m(n[r].start,n[r].end,n[r].audio||0)).open("GET",n[r].filename);g.addRunDependency("datafile_../../resources/advanced/BlinkIDImageCaptureWasmSDK.data");g.ic||(g.ic={});g.ic["../../resources/advanced/BlinkIDImageCaptureWasmSDK.data"]={ed:!1};l?(p(l),l=null):h=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==
typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,q("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkIDImageCaptureWasmSDK.data",""):"BlinkIDImageCaptureWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_BarcodeDetector_pdf417_6.0.0.strop",start:0,end:214096},{filename:"/microblink/BlinkID_BarcodeDeblurring_pdf417_6.0.0.strop",start:214096,end:4932412},{filename:"/microblink/BlinkID_Detector_general_6.7.0.strop",start:4932412,end:5220620},{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",start:5220620,end:5224558},
{filename:"/microblink/BlinkID_Analyzer_general_6.6.0.strop",start:5224558,end:5241296},{filename:"/microblink/BlinkID_Classifier_general_6.16.0.strop",start:5241296,end:5770610},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:5770610,end:5777428},{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",start:5777428,end:5784310},{filename:"/microblink/BlinkID_RotationClassifier_general_6.2.0.strop",start:5784310,end:5840824},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",
start:5840824,end:6210616}],remote_package_size:6210616,package_uuid:"d7d16760-8ce7-444b-8d8c-44c5c3d24c2a"});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in g)g.hasOwnProperty(da)&&(ca[da]=g[da]);var ea="./this.program";function fa(a,b){throw b;}var ia="object"===typeof window,ja="function"===typeof importScripts,ka="",la,ma,na;
if(ia||ja)ja?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),_scriptDir&&(ka=_scriptDir),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ja&&(na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ma=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",
a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var oa=g.print||console.log.bind(console),q=g.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(g[da]=ca[da]);ca=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var pa=0,qa;g.wasmBinary&&(qa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&t("no native wasm support detected");
var ra,sa=!1,ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?ua(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ya[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ea(a){var b=va(a)+1,c=Fa(b);c&&B(a,F,c,b);return c}var Ga,F,A,ya,C,E,I,Ha,Ia;
function Ja(){var a=ra.buffer;Ga=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=ya=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=C=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=Ha=new Float32Array(a);g.HEAPF64=Ia=new Float64Array(a)}var L,Ka=[],La=[],Ma=[];function Na(){var a=g.preRun.shift();Ka.unshift(a)}var Oa=0,Pa=null,Qa=null;function Ra(){Oa++;g.monitorRunDependencies&&g.monitorRunDependencies(Oa)}
function Sa(){Oa--;g.monitorRunDependencies&&g.monitorRunDependencies(Oa);if(0==Oa&&(null!==Pa&&(clearInterval(Pa),Pa=null),Qa)){var a=Qa;Qa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);a+="";q(a);sa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ta(){return Ua.startsWith("data:application/octet-stream;base64,")}var Ua;Ua="BlinkIDImageCaptureWasmSDK.wasm";
if(!Ta()){var Wa=Ua;Ua=g.locateFile?g.locateFile(Wa,ka):ka+Wa}function Xa(){var a=Ua;try{if(a==Ua&&qa)return new Uint8Array(qa);if(na)return na(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}function Ya(){return qa||!ia&&!ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Xa()}):fetch(Ua,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ua+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}
var M,Za,$a={286313:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},286449:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},286665:function(a,b){a=z(a);b=z(b);throw Error(a+b);},286775:function(a,b){a=z(a);b=z(b);console.log(a+b)},286873:function(a){throw Error(z(a));},286916:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};
function ab(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.fd;"number"===typeof c?void 0===b.Mb?L.get(c)():L.get(c)(b.Mb):c(void 0===b.Mb?null:b.Mb)}}}
function bb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);E[cb()>>2]=60*f;E[db()>>2]=Number(b!=e);c=a(c);d=a(d);c=Ea(c);d=Ea(d);e<b?(E[eb()>>2]=c,E[eb()+4>>2]=d):(E[eb()>>2]=d,E[eb()+4>>2]=c)}var fb;
function gb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function N(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";a=N(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){t("randomDevice")}}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=gb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var lb=[];function mb(a,b){lb[a]={input:[],Ua:[],ob:b};nb(a,ob)}
var ob={open:function(a){var b=lb[a.node.tb];if(!b)throw new O(43);a.Sa=b;a.seekable=!1},close:function(a){a.Sa.ob.flush(a.Sa)},flush:function(a){a.Sa.ob.flush(a.Sa)},read:function(a,b,c,d){if(!a.Sa||!a.Sa.ob.ec)throw new O(60);for(var e=0,f=0;f<d;f++){try{var h=a.Sa.ob.ec(a.Sa)}catch(l){throw new O(29);}if(void 0===h&&0===e)throw new O(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Sa||!a.Sa.ob.Sb)throw new O(60);try{for(var e=
0;e<d;e++)a.Sa.ob.Sb(a.Sa,b[c+e])}catch(f){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},qb={ec:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},Sb:function(a,b){null===b||10===b?(oa(ua(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},flush:function(a){a.Ua&&0<a.Ua.length&&
(oa(ua(a.Ua,0)),a.Ua=[])}},rb={Sb:function(a,b){null===b||10===b?(q(ua(a.Ua,0)),a.Ua=[]):0!=b&&a.Ua.push(b)},flush:function(a){a.Ua&&0<a.Ua.length&&(q(ua(a.Ua,0)),a.Ua=[])}};function sb(a){a=65536*Math.ceil(a/65536);var b=tb(65536,a);if(!b)return 0;A.fill(0,b,b+a);return b}
var P={fb:null,gb:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.fb||(P.fb={dir:{node:{eb:P.Na.eb,Ya:P.Na.Ya,qb:P.Na.qb,Db:P.Na.Db,mc:P.Na.mc,Kb:P.Na.Kb,nc:P.Na.nc,lc:P.Na.lc,Gb:P.Na.Gb},stream:{jb:P.Oa.jb}},file:{node:{eb:P.Na.eb,Ya:P.Na.Ya},stream:{jb:P.Oa.jb,read:P.Oa.read,write:P.Oa.write,Xb:P.Oa.Xb,Eb:P.Oa.Eb,Fb:P.Oa.Fb}},link:{node:{eb:P.Na.eb,Ya:P.Na.Ya,ub:P.Na.ub},stream:{}},Zb:{node:{eb:P.Na.eb,Ya:P.Na.Ya},
stream:ub}});c=vb(a,b,c,d);Q(c.mode)?(c.Na=P.fb.dir.node,c.Oa=P.fb.dir.stream,c.Ma={}):32768===(c.mode&61440)?(c.Na=P.fb.file.node,c.Oa=P.fb.file.stream,c.Ra=0,c.Ma=null):40960===(c.mode&61440)?(c.Na=P.fb.link.node,c.Oa=P.fb.link.stream):8192===(c.mode&61440)&&(c.Na=P.fb.Zb.node,c.Oa=P.fb.Zb.stream);c.timestamp=Date.now();a&&(a.Ma[b]=c,a.timestamp=c.timestamp);return c},gd:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Ra):new Uint8Array(a.Ma):new Uint8Array(0)},bc:function(a,b){var c=a.Ma?
a.Ma.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Ra&&a.Ma.set(c.subarray(0,a.Ra),0))},Tc:function(a,b){if(a.Ra!=b)if(0==b)a.Ma=null,a.Ra=0;else{var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Ra)));a.Ra=b}},Na:{eb:function(a){var b={};b.xc=8192===(a.mode&61440)?a.id:1;b.Pb=a.id;b.mode=a.mode;b.Oc=1;b.uid=0;b.Ec=0;b.tb=a.tb;b.size=Q(a.mode)?4096:32768===(a.mode&61440)?a.Ra:40960===(a.mode&61440)?a.link.length:
0;b.rc=new Date(a.timestamp);b.Nc=new Date(a.timestamp);b.wc=new Date(a.timestamp);b.sc=4096;b.tc=Math.ceil(b.size/b.sc);return b},Ya:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Tc(a,b.size)},qb:function(){throw wb[44];},Db:function(a,b,c,d){return P.createNode(a,b,c,d)},mc:function(a,b,c){if(Q(a.mode)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.Ma)throw new O(55);}delete a.parent.Ma[a.name];a.parent.timestamp=Date.now();a.name=
c;b.Ma[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Kb:function(a,b){delete a.Ma[b];a.timestamp=Date.now()},nc:function(a,b){var c=xb(a,b),d;for(d in c.Ma)throw new O(55);delete a.Ma[b];a.timestamp=Date.now()},lc:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&b.push(c);return b},Gb:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},ub:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},Oa:{read:function(a,b,c,d,e){var f=a.node.Ma;if(e>=a.node.Ra)return 0;
a=Math.min(a.node.Ra-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===F.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(f)return a.Ma=b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===e)return a.Ma=b.slice(c,c+d),a.Ra=d;if(e+d<=a.Ra)return a.Ma.set(b.subarray(c,c+d),e),d}P.bc(a,e+d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ma[e+
f]=b[c+f];a.Ra=Math.max(a.Ra,e+d);return d},jb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new O(28);return b},Xb:function(a,b,c){P.bc(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},Eb:function(a,b,c,d,e,f){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.Ma;if(f&2||a.buffer!==Ga){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=sb(c);if(!c)throw new O(48);F.set(a,
c)}else d=!1,c=a.byteOffset;return{Qa:c,Lb:d}},Fb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.Oa.write(a,b,0,d,c,!1);return 0}}};function yb(a,b,c){var d="al "+a;ma(a,function(e){e||t('Assertion failed: Loading data file "'+(a+'" failed (no arrayBuffer).'));b(new Uint8Array(e));d&&Sa(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ra(d)}var zb=null,Ab={},Bb=[],Cb=1,Db=null,Eb=!0,Fb={},O=null,wb={};
function Gb(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={dc:!0,Ub:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Ub)throw new O(32);a=gb(a.split("/").filter(function(h){return!!h}),!1);var e=zb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=xb(e,a[d]);c=N(c+"/"+a[d]);e.rb&&(!f||f&&b.dc)&&(e=e.rb.root);if(!f||b.zb)for(f=0;40960===(e.mode&61440);)if(e=Hb(c),c=kb(hb(c),e),e=Gb(c,{Ub:b.Ub}).node,40<f++)throw new O(32);}return{path:c,node:e}}
function Ib(a){for(var b;;){if(a===a.parent)return a=a.gb.hc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Jb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function xb(a,b){var c;if(c=(c=Kb(a,"x"))?c:a.Na.qb?0:2)throw new O(c,a);for(c=Db[Jb(a.id,b)];c;c=c.nb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.qb(a,b)}
function vb(a,b,c,d){a=new Lb(a,b,c,d);b=Jb(a.parent.id,a.name);a.nb=Db[b];return Db[b]=a}function Q(a){return 16384===(a&61440)}var Mb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Nb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Kb(a,b){if(Eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ob(a,b){try{return xb(a,b),20}catch(c){}return Kb(a,"wx")}
function Pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Bb[a])return a;throw new O(33);}function Qb(a,b){Rb||(Rb=function(){},Rb.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Rb,d;for(d in a)c[d]=a[d];a=c;b=Pb(b);a.cb=b;return Bb[b]=a}var ub={open:function(a){a.Oa=Ab[a.node.tb].Oa;a.Oa.open&&a.Oa.open(a)},jb:function(){throw new O(70);}};function nb(a,b){Ab[a]={Oa:b}}
function Sb(a,b){var c="/"===b,d=!b;if(c&&zb)throw new O(10);if(!c&&!d){var e=Gb(b,{dc:!1});b=e.path;e=e.node;if(e.rb)throw new O(10);if(!Q(e.mode))throw new O(54);}b={type:a,kd:{},hc:b,Mc:[]};a=a.gb(b);a.gb=b;b.root=a;c?zb=a:e&&(e.rb=b,e.gb&&e.gb.Mc.push(b))}function Tb(a,b,c){var d=Gb(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new O(28);var e=Ob(d,a);if(e)throw new O(e);if(!d.Na.Db)throw new O(63);return d.Na.Db(d,a,b,c)}function Ub(a){return Tb(a,16895,0)}
function Vb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Tb(a,b|8192,c)}function Wb(a,b){if(!kb(a))throw new O(44);var c=Gb(b,{parent:!0}).node;if(!c)throw new O(44);b=ib(b);var d=Ob(c,b);if(d)throw new O(d);if(!c.Na.Gb)throw new O(63);c.Na.Gb(c,b,a)}
function Xb(a){var b=Gb(a,{parent:!0}).node,c=ib(a),d=xb(b,c);a:{try{var e=xb(b,c)}catch(h){e=h.Wa;break a}var f=Kb(b,"wx");e=f?f:Q(e.mode)?31:0}if(e)throw new O(e);if(!b.Na.Kb)throw new O(63);if(d.rb)throw new O(10);try{Fb.willDeletePath&&Fb.willDeletePath(a)}catch(h){q("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Na.Kb(b,c);b=Jb(d.parent.id,d.name);if(Db[b]===d)Db[b]=d.nb;else for(b=Db[b];b;){if(b.nb===d){b.nb=d.nb;break}b=b.nb}try{if(Fb.onDeletePath)Fb.onDeletePath(a)}catch(h){q("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function Hb(a){a=Gb(a).node;if(!a)throw new O(44);if(!a.Na.ub)throw new O(28);return kb(Ib(a.parent),a.Na.ub(a))}function Yb(a,b){a="string"===typeof a?Gb(a,{zb:!0}).node:a;if(!a.Na.Ya)throw new O(63);a.Na.Ya(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Zb(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var e=Mb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=N(a);try{f=Gb(a,{zb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new O(20);}else f=Tb(a,c,0),e=!0;if(!f)throw new O(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!Q(f.mode))throw new O(54);if(!e&&(c=f?40960===(f.mode&61440)?32:Q(f.mode)&&
("r"!==Nb(b)||b&512)?31:Kb(f,Nb(b)):44))throw new O(c);if(b&512){c=f;c="string"===typeof c?Gb(c,{zb:!0}).node:c;if(!c.Na.Ya)throw new O(63);if(Q(c.mode))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(e=Kb(c,"w"))throw new O(e);c.Na.Ya(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Qb({node:f,path:Ib(f),flags:b,seekable:!0,position:0,Oa:f.Oa,dd:[],error:!1},d);d.Oa.open&&d.Oa.open(d);!g.logReadFiles||b&1||($b||($b={}),a in $b||($b[a]=1,q("FS.trackingDelegate error on read file: "+a)));
try{Fb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Fb.onOpenFile(a,f))}catch(h){q("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function ac(a){if(null===a.cb)throw new O(8);a.Ob&&(a.Ob=null);try{a.Oa.close&&a.Oa.close(a)}catch(b){throw b;}finally{Bb[a.cb]=null}a.cb=null}function bc(a,b,c){if(null===a.cb)throw new O(8);if(!a.seekable||!a.Oa.jb)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.Oa.jb(a,b,c);a.dd=[]}
function cc(a,b,c,d,e,f){if(0>d||0>e)throw new O(28);if(null===a.cb)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(Q(a.node.mode))throw new O(31);if(!a.Oa.write)throw new O(28);a.seekable&&a.flags&1024&&bc(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new O(70);b=a.Oa.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Fb.onWriteToFile)Fb.onWriteToFile(a.path)}catch(l){q("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function dc(){O||(O=function(a,b){this.node=b;this.Vc=function(c){this.Wa=c};this.Vc(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){wb[a]=new O(a);wb[a].stack="<generic error, no stack>"}))}var ec;function fc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function gc(a,b){a="string"===typeof a?a:Ib(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=N(a+"/"+c);try{Ub(d)}catch(e){}a=d}}return d}
function hc(a,b,c,d){a=N(("string"===typeof a?a:Ib(a))+"/"+b);c=fc(c,d);return Tb(a,(void 0!==c?c:438)&4095|32768,0)}function ic(a,b,c,d,e,f){a=b?N(("string"===typeof a?a:Ib(a))+"/"+b):a;d=fc(d,e);e=Tb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Yb(e,d|146);a=Zb(e,577);cc(a,c,0,c.length,0,f);ac(a);Yb(e,d)}return e}
function jc(a,b,c,d){a=N(("string"===typeof a?a:Ib(a))+"/"+b);b=fc(!!c,!!d);jc.fc||(jc.fc=64);var e=jc.fc++<<8|0;nb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var p=0,n=0;n<m;n++){try{var r=c()}catch(v){throw new O(29);}if(void 0===r&&0===p)throw new O(6);if(null===r||void 0===r)break;p++;h[l+n]=r}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{d(h[l+p])}catch(n){throw new O(29);}m&&
(f.node.timestamp=Date.now());return p}});return Vb(a,b,e)}function kc(a){if(!(a.Hc||a.Ic||a.link||a.Ma)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.Ma=pb(la(a.url),!0),a.Ra=a.Ma.length}catch(b){throw new O(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function lc(a,b,c,d,e){function f(){this.Rb=!1;this.yb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var r=n%this.$b;return this.Ab(n/this.$b|0)[r]}};f.prototype.Uc=function(n){this.Ab=n};f.prototype.Yb=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=
(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=r);var x=this;x.Uc(function(y){var H=y*u,G=(y+1)*u-1;G=Math.min(G,r-1);if("undefined"===typeof x.yb[y]){var ha=x.yb;if(H>G)throw Error("invalid range ("+H+", "+G+") or no bytes requested!");if(G>r-1)throw Error("only "+r+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);r!==u&&w.setRequestHeader("Range","bytes="+H+"-"+G);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);H=void 0!==w.response?new Uint8Array(w.response||[]):pb(w.responseText||"",!0);ha[y]=H}if("undefined"===typeof x.yb[y])throw Error("doXHR failed!");return x.yb[y]});if(n||!r)u=r=1,u=r=this.Ab(0).length,oa("LazyFiles on gzip forces download of the whole file when length is accessed");this.pc=r;this.oc=u;this.Rb=!0};if("undefined"!==
typeof XMLHttpRequest){if(!ja)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Rb||this.Yb();return this.pc}},$b:{get:function(){this.Rb||this.Yb();return this.oc}}});var l=void 0}else l=c,h=void 0;var m=hc(a,b,d,e);h?m.Ma=h:l&&(m.Ma=null,m.url=l);Object.defineProperties(m,{Ra:{get:function(){return this.Ma.length}}});var p={};Object.keys(m.Oa).forEach(function(n){var r=
m.Oa[n];p[n]=function(){kc(m);return r.apply(null,arguments)}});p.read=function(n,r,v,k,u){kc(m);n=n.node.Ma;if(u>=n.length)return 0;k=Math.min(n.length-u,k);if(n.slice)for(var x=0;x<k;x++)r[v+x]=n[u+x];else for(x=0;x<k;x++)r[v+x]=n.get(u+x);return k};m.Oa=p;return m}
function mc(a,b,c,d,e,f,h,l,m,p){function n(k){function u(y){p&&p();l||ic(a,b,y,d,e,m);f&&f();Sa(v)}var x=!1;g.preloadPlugins.forEach(function(y){!x&&y.canHandle(r)&&(y.handle(k,r,u,function(){h&&h();Sa(v)}),x=!0)});x||u(k)}nc.hd();var r=b?kb(N(a+"/"+b)):a,v="cp "+r;Ra(v);"string"==typeof c?yb(c,function(k){n(k)},h):n(c)}var R={},Rb,$b,oc={};
function pc(a,b){try{var c=Gb(a,{zb:!0}).node;if(!c)throw new O(44);if(!c.Na.eb)throw new O(63);var d=c.Na.eb(c)}catch(e){if(e&&e.node&&N(a)!==N(Ib(e.node)))return-54;throw e;}E[b>>2]=d.xc;E[b+4>>2]=0;E[b+8>>2]=d.Pb;E[b+12>>2]=d.mode;E[b+16>>2]=d.Oc;E[b+20>>2]=d.uid;E[b+24>>2]=d.Ec;E[b+28>>2]=d.tb;E[b+32>>2]=0;Za=[d.size>>>0,(M=d.size,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+40>>2]=Za[0];E[b+44>>2]=Za[1];E[b+48>>
2]=4096;E[b+52>>2]=d.tc;E[b+56>>2]=d.rc.getTime()/1E3|0;E[b+60>>2]=0;E[b+64>>2]=d.Nc.getTime()/1E3|0;E[b+68>>2]=0;E[b+72>>2]=d.wc.getTime()/1E3|0;E[b+76>>2]=0;Za=[d.Pb>>>0,(M=d.Pb,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+80>>2]=Za[0];E[b+84>>2]=Za[1];return 0}var qc=void 0;function rc(){qc+=4;return E[qc-4>>2]}function sc(a){a=Bb[a];if(!a)throw new O(8);return a}var tc={};
function uc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function vc(a){return this.fromWireType(I[a>>2])}var wc={},xc={},yc={};function zc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ac(a,b){a=zc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Bc(a){var b=Error,c=Ac(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Cc=void 0;function Dc(a){throw new Cc(a);}
function Ec(a,b,c){function d(l){l=c(l);l.length!==a.length&&Dc("Mismatched type converter count");for(var m=0;m<a.length;++m)Fc(a[m],l[m])}a.forEach(function(l){yc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){xc.hasOwnProperty(l)?e[m]=xc[l]:(f.push(l),wc.hasOwnProperty(l)||(wc[l]=[]),wc[l].push(function(){e[m]=xc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Gc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Hc=void 0;function S(a){for(var b="";A[a];)b+=Hc[A[a++]];return b}var Ic=void 0;function T(a){throw new Ic(a);}
function Fc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(xc.hasOwnProperty(a)){if(c.Fc)return;T("Cannot register type '"+d+"' twice")}xc[a]=b;delete yc[a];wc.hasOwnProperty(a)&&(b=wc[a],delete wc[a],b.forEach(function(e){e()}))}function Jc(a){T(a.La.Ta.Pa.name+" instance already deleted")}var Kc=!1;function Lc(){}
function Mc(a){--a.count.value;0===a.count.value&&(a.Za?a.$a.hb(a.Za):a.Ta.Pa.hb(a.Qa))}function Nc(a){if("undefined"===typeof FinalizationGroup)return Nc=function(b){return b},a;Kc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Qa?Mc(c):console.warn("object already deleted: "+c.Qa)});Nc=function(b){Kc.register(b,b.La,b.La);return b};Lc=function(b){Kc.unregister(b.La)};return Nc(a)}var Oc=void 0,Pc=[];
function Qc(){for(;Pc.length;){var a=Pc.pop();a.La.lb=!1;a["delete"]()}}function Rc(){}var Sc={};function Tc(a,b,c){if(void 0===a[b].Va){var d=a[b];a[b]=function(){a[b].Va.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Va+")!");return a[b].Va[arguments.length].apply(this,arguments)};a[b].Va=[];a[b].Va[d.xb]=d}}
function Uc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Va&&void 0!==g[a].Va[c])&&T("Cannot register public name '"+a+"' twice"),Tc(g,a,a),g.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Va[c]=b):(g[a]=b,void 0!==c&&(g[a].jd=c))}function Vc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.mb=c;this.hb=d;this.ab=e;this.Ac=f;this.wb=h;this.yc=l;this.Rc=[]}
function Wc(a,b,c){for(;b!==c;)b.wb||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.wb(a),b=b.ab;return a}function Xc(a,b){if(null===b)return this.Qb&&T("null is not a valid "+this.name),0;b.La||T('Cannot pass "'+Yc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);return Wc(b.La.Qa,b.La.Ta.Pa,this.Pa)}
function Zc(a,b){if(null===b){this.Qb&&T("null is not a valid "+this.name);if(this.Cb){var c=this.Tb();null!==a&&a.push(this.hb,c);return c}return 0}b.La||T('Cannot pass "'+Yc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);!this.Bb&&b.La.Ta.Bb&&T("Cannot convert argument of type "+(b.La.$a?b.La.$a.name:b.La.Ta.name)+" to parameter type "+this.name);c=Wc(b.La.Qa,b.La.Ta.Pa,this.Pa);if(this.Cb)switch(void 0===b.La.Za&&T("Passing raw pointer to smart pointer is illegal"),
this.Zc){case 0:b.La.$a===this?c=b.La.Za:T("Cannot convert argument of type "+(b.La.$a?b.La.$a.name:b.La.Ta.name)+" to parameter type "+this.name);break;case 1:c=b.La.Za;break;case 2:if(b.La.$a===this)c=b.La.Za;else{var d=b.clone();c=this.Sc(c,U(function(){d["delete"]()}));null!==a&&a.push(this.hb,c)}break;default:T("Unsupporting sharing policy")}return c}
function $c(a,b){if(null===b)return this.Qb&&T("null is not a valid "+this.name),0;b.La||T('Cannot pass "'+Yc(b)+'" as a '+this.name);b.La.Qa||T("Cannot pass deleted object as a pointer of type "+this.name);b.La.Ta.Bb&&T("Cannot convert argument of type "+b.La.Ta.name+" to parameter type "+this.name);return Wc(b.La.Qa,b.La.Ta.Pa,this.Pa)}function ad(a,b,c){if(b===c)return a;if(void 0===c.ab)return null;a=ad(a,b,c.ab);return null===a?null:c.yc(a)}var bd={};
function cd(a,b){for(void 0===b&&T("ptr should not be undefined");a.ab;)b=a.wb(b),a=a.ab;return bd[b]}function dd(a,b){b.Ta&&b.Qa||Dc("makeClassHandle requires ptr and ptrType");!!b.$a!==!!b.Za&&Dc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Nc(Object.create(a,{La:{value:b}}))}
function ed(a,b,c,d){this.name=a;this.Pa=b;this.Qb=c;this.Bb=d;this.Cb=!1;this.hb=this.Sc=this.Tb=this.kc=this.Zc=this.Pc=void 0;void 0!==b.ab?this.toWireType=Zc:(this.toWireType=d?Xc:$c,this.bb=null)}function fd(a,b,c){g.hasOwnProperty(a)||Dc("Replacing nonexistant public symbol");void 0!==g[a].Va&&void 0!==c?g[a].Va[c]=b:(g[a]=b,g[a].xb=c)}
function gd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function V(a,b){a=S(a);var c=a.includes("j")?gd(a,b):L.get(b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var hd=void 0;function jd(a){a=kd(a);var b=S(a);W(a);return b}
function ld(a,b){function c(f){e[f]||xc[f]||(yc[f]?yc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new hd(a+": "+d.map(jd).join([", "]));}function md(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function nd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ac(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function od(a,b,c,d,e){var f=b.length;2>f&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].bb){l=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+zc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var r=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[T,d,e,uc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].bb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].bb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return nd(p).apply(null,d)}var pd=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function qd(a){4<a&&0===--X[a].Vb&&(X[a]=void 0,pd.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=pd.length?pd.pop():X.length;X[b]={Vb:1,value:a};return b}}function Yc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function rd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ha[c>>2])};case 3:return function(c){return this.fromWireType(Ia[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function sd(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return A[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Y(a){a||T("Cannot use deleted val. handle = "+a);return X[a].value}function td(a,b){var c=xc[a];void 0===c&&T(b+" has unknown type "+jd(a));return c}
function ud(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=td(E[(b>>2)+d],"parameter "+d);return c}var vd={};function wd(a){var b=vd[a];return void 0===b?S(a):b}var xd=[];function yd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function zd(a){var b=xd.length;xd.push(a);return b}var Ad={},Bd;Bd=function(){return performance.now()};var Cd=[],Dd=[];function Z(a,b){I[a>>2]=b;I[a+4>>2]=b/4294967296|0}var Ed;
function Fd(a,b,c,d,e){function f(J){var K=0,D=0;J&&(D=w.response?w.response.byteLength:0,K=Fa(D),A.set(new Uint8Array(w.response),K));I[a+12>>2]=K;Z(a+16,D)}var h=I[a+8>>2];if(h){var l=z(h),m=a+112,p=z(m);p||(p="GET");var n=I[m+52>>2],r=I[m+56>>2],v=!!I[m+60>>2],k=I[m+68>>2],u=I[m+72>>2];h=I[m+76>>2];var x=I[m+80>>2],y=I[m+84>>2];m=I[m+88>>2];var H=!!(n&1),G=!!(n&2);n=!!(n&64);k=k?z(k):void 0;u=u?z(u):void 0;var ha=x?z(x):void 0,w=new XMLHttpRequest;w.withCredentials=v;w.open(p,l,!n,k,u);n||(w.timeout=
r);w.md=l;w.responseType="arraybuffer";x&&w.overrideMimeType(ha);if(h)for(;;){p=I[h>>2];if(!p)break;l=I[h+4>>2];if(!l)break;h+=8;p=z(p);l=z(l);w.setRequestHeader(p,l)}Dd.push(w);I[a+0>>2]=Dd.length;h=y&&m?A.slice(y,y+m):null;w.onload=function(J){f(H&&!G);var K=w.response?w.response.byteLength:0;Z(a+24,0);K&&Z(a+32,K);C[a+40>>1]=w.readyState;C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,J):c&&c(a,w,J)};w.onerror=function(J){f(H);var K=w.status;Z(a+
24,0);Z(a+32,w.response?w.response.byteLength:0);C[a+40>>1]=w.readyState;C[a+42>>1]=K;c&&c(a,w,J)};w.ontimeout=function(J){c&&c(a,w,J)};w.onprogress=function(J){var K=H&&G&&w.response?w.response.byteLength:0,D=0;H&&G&&(D=Fa(K),A.set(new Uint8Array(w.response),D));I[a+12>>2]=D;Z(a+16,K);Z(a+24,J.loaded-K);Z(a+32,J.total);C[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<J.loaded&&(w.status=200);C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);d&&d(a,w,J);D&&W(D)};w.onreadystatechange=
function(J){C[a+40>>1]=w.readyState;2<=w.readyState&&(C[a+42>>1]=w.status);e&&e(a,w,J)};try{w.send(h)}catch(J){c&&c(a,w,J)}}else c(a,0,"no url specified!")}function Gd(a,b){if(!sa)if(b)a();else try{a()}catch(c){if(a=c,!(a instanceof Hd||"unwind"===a))throw a&&"object"===typeof a&&a.stack&&q("exception thrown: "+[a,a.stack]),a;}}
function Id(a,b,c,d){var e=Ed;if(e){var f=I[a+112+64>>2];f||(f=I[a+8>>2]);var h=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,h)};l.onerror=function(m){C[a+40>>1]=4;C[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Jd(a,b,c){var d=Ed;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Fa(l);A.set(new Uint8Array(h),m);I[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)}else C[a+40>>1]=4,C[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Kd(a,b,c){var d=Ed;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;I[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Ld={};
function Md(){if(!Nd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ld)void 0===Ld[b]?delete a[b]:a[b]=Ld[b];var c=[];for(b in a)c.push(b+"="+a[b]);Nd=c}return Nd}var Nd;function Od(a,b){Od.jc||(Od.jc=jb());for(var c=0;c<b;c++)F[a+c>>0]=Od.jc();return 0}function Pd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Qd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Rd=[31,29,31,30,31,30,31,31,30,31,30,31],Sd=[31,28,31,30,31,30,31,31,30,31,30,31];function Td(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Pd(a.getFullYear())?Rd:Sd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ud(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(H){return 0>H?-1:0<H?1:0}var y;0===(y=x(k.getFullYear()-u.getFullYear()))&&0===(y=x(k.getMonth()-u.getMonth()))&&(y=x(k.getDate()-u.getDate()));return y}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Td(new Date(k.Xa+1900,0,1),k.Jb);var u=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(x,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=E[d+40>>2];d={bd:E[d>>2],ad:E[d+4>>2],Hb:E[d+8>>2],vb:E[d+12>>2],pb:E[d+16>>2],Xa:E[d+20>>2],Ib:E[d+24>>2],Jb:E[d+28>>2],ld:E[d+32>>2],$c:E[d+
36>>2],cd:p?z(p):""};c=z(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return r[k.Ib].substring(0,3)},"%A":function(k){return r[k.Ib]},"%b":function(k){return v[k.pb].substring(0,3)},"%B":function(k){return v[k.pb]},"%C":function(k){return f((k.Xa+1900)/100|0,2)},"%d":function(k){return f(k.vb,2)},"%e":function(k){return e(k.vb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Hb,
2)},"%I":function(k){k=k.Hb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.vb+Qd(Pd(k.Xa+1900)?Rd:Sd,k.pb-1),3)},"%m":function(k){return f(k.pb+1,2)},"%M":function(k){return f(k.ad,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Hb&&12>k.Hb?"AM":"PM"},"%S":function(k){return f(k.bd,2)},"%t":function(){return"\t"},"%u":function(k){return k.Ib||7},"%U":function(k){var u=new Date(k.Xa+1900,0,1),x=0===u.getDay()?u:Td(u,7-u.getDay());k=new Date(k.Xa+1900,k.pb,k.vb);return 0>
h(x,k)?f(Math.ceil((31-x.getDate()+(Qd(Pd(k.getFullYear())?Rd:Sd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.Xa+1901,0,4),x=l(new Date(k.Xa+1900,0,4));u=l(u);var y=Td(new Date(k.Xa+1900,0,1),k.Jb);return 0>h(y,x)?"53":0>=h(u,y)?"01":f(Math.ceil((x.getFullYear()<k.Xa+1900?k.Jb+32-x.getDate():k.Jb+1-x.getDate())/7),2)},"%w":function(k){return k.Ib},"%W":function(k){var u=new Date(k.Xa,0,1),x=1===u.getDay()?u:Td(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.Xa+1900,k.pb,k.vb);return 0>h(x,k)?f(Math.ceil((31-x.getDate()+(Qd(Pd(k.getFullYear())?Rd:Sd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%y":function(k){return(k.Xa+1900).toString().substring(2)},"%Y":function(k){return k.Xa+1900},"%z":function(k){k=k.$c;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.cd},"%%":function(){return"%"}};for(n in p)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));n=pb(c,
!1);if(n.length>b)return 0;F.set(n,a);return n.length-1}function Lb(a,b,c,d){a||(a=this);this.parent=a;this.gb=a.gb;this.rb=null;this.id=Cb++;this.name=b;this.mode=c;this.Na={};this.Oa={};this.tb=d}
Object.defineProperties(Lb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Ic:{get:function(){return Q(this.mode)}},Hc:{get:function(){return 8192===(this.mode&61440)}}});dc();Db=Array(4096);Sb(P,"/");Ub("/tmp");Ub("/home");Ub("/home/web_user");
(function(){Ub("/dev");nb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Vb("/dev/null",259);mb(1280,qb);mb(1536,rb);Vb("/dev/tty",1280);Vb("/dev/tty1",1536);var a=jb();jc("/dev","random",a);jc("/dev","urandom",a);Ub("/dev/shm");Ub("/dev/shm/tmp")})();
(function(){Ub("/proc");var a=Ub("/proc/self");Ub("/proc/self/fd");Sb({gb:function(){var b=vb(a,"fd",16895,73);b.Na={qb:function(c,d){var e=Bb[+d];if(!e)throw new O(8);c={parent:null,gb:{hc:"fake"},Na:{ub:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var nc;g.FS_createPath=gc;g.FS_createDataFile=ic;g.FS_createPreloadedFile=mc;g.FS_createLazyFile=lc;g.FS_createDevice=jc;g.FS_unlink=Xb;Cc=g.InternalError=Bc("InternalError");
for(var Vd=Array(256),Wd=0;256>Wd;++Wd)Vd[Wd]=String.fromCharCode(Wd);Hc=Vd;Ic=g.BindingError=Bc("BindingError");Rc.prototype.isAliasOf=function(a){if(!(this instanceof Rc&&a instanceof Rc))return!1;var b=this.La.Ta.Pa,c=this.La.Qa,d=a.La.Ta.Pa;for(a=a.La.Qa;b.ab;)c=b.wb(c),b=b.ab;for(;d.ab;)a=d.wb(a),d=d.ab;return b===d&&c===a};
Rc.prototype.clone=function(){this.La.Qa||Jc(this);if(this.La.sb)return this.La.count.value+=1,this;var a=Nc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.La;a=a(c.call(b,d,{La:{value:{count:e.count,lb:e.lb,sb:e.sb,Qa:e.Qa,Ta:e.Ta,Za:e.Za,$a:e.$a}}}));a.La.count.value+=1;a.La.lb=!1;return a};Rc.prototype["delete"]=function(){this.La.Qa||Jc(this);this.La.lb&&!this.La.sb&&T("Object already scheduled for deletion");Lc(this);Mc(this.La);this.La.sb||(this.La.Za=void 0,this.La.Qa=void 0)};
Rc.prototype.isDeleted=function(){return!this.La.Qa};Rc.prototype.deleteLater=function(){this.La.Qa||Jc(this);this.La.lb&&!this.La.sb&&T("Object already scheduled for deletion");Pc.push(this);1===Pc.length&&Oc&&Oc(Qc);this.La.lb=!0;return this};ed.prototype.Bc=function(a){this.kc&&(a=this.kc(a));return a};ed.prototype.ac=function(a){this.hb&&this.hb(a)};ed.prototype.argPackAdvance=8;ed.prototype.readValueFromPointer=vc;ed.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
ed.prototype.fromWireType=function(a){function b(){return this.Cb?dd(this.Pa.mb,{Ta:this.Pc,Qa:c,$a:this,Za:a}):dd(this.Pa.mb,{Ta:this,Qa:a})}var c=this.Bc(a);if(!c)return this.ac(a),null;var d=cd(this.Pa,c);if(void 0!==d){if(0===d.La.count.value)return d.La.Qa=c,d.La.Za=a,d.clone();d=d.clone();this.ac(a);return d}d=this.Pa.Ac(c);d=Sc[d];if(!d)return b.call(this);d=this.Bb?d.vc:d.pointerType;var e=ad(c,this.Pa,d.Pa);return null===e?b.call(this):this.Cb?dd(d.Pa.mb,{Ta:d,Qa:e,$a:this,Za:a}):dd(d.Pa.mb,
{Ta:d,Qa:e})};g.getInheritedInstanceCount=function(){return Object.keys(bd).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in bd)bd.hasOwnProperty(b)&&a.push(bd[b]);return a};g.flushPendingDeletes=Qc;g.setDelayFunction=function(a){Oc=a;Pc.length&&Oc&&Oc(Qc)};hd=g.UnboundTypeError=Bc("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){Ed=a;Sa("library_fetch_init")},function(){Ed=!1;Sa("library_fetch_init")});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Ra("library_fetch_init");
function pb(a,b){var c=Array(va(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var $d={W:function(a,b){fb||(fb=!0,bb());a=new Date(1E3*E[a>>2]);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;E[b+32>>2]=a;
a=E[eb()+(a?4:0)>>2];E[b+40>>2]=a;return b},C:function(a,b,c){qc=c;try{var d=sc(a);switch(b){case 0:var e=rc();return 0>e?-28:Zb(d.path,d.flags,0,e).cb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=rc(),d.flags|=e,0;case 12:return e=rc(),ya[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Wa}},Z:function(a,b){try{var c=sc(a);return pc(c.path,b)}catch(d){return"undefined"!==
typeof R&&d instanceof O||t(d),-d.Wa}},X:function(a,b,c){qc=c;try{var d=sc(a);switch(b){case 21509:case 21505:return d.Sa?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Sa?0:-59;case 21519:if(!d.Sa)return-59;var e=rc();return E[e>>2]=0;case 21520:return d.Sa?-28:-59;case 21531:a=e=rc();if(!d.Oa.Gc)throw new O(59);return d.Oa.Gc(d,b,a);case 21523:return d.Sa?0:-59;case 21524:return d.Sa?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof R&&
f instanceof O||t(f),-f.Wa}},aa:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=sb(b);if(!m){l=-48;break a}h=!0}else{var p=Bb[e];if(!p){l=-8;break a}var n=f;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new O(2);if(1===(p.flags&2097155))throw new O(2);if(!p.Oa.Eb)throw new O(43);var r=p.Oa.Eb(p,a,b,n,c,d);m=r.Qa;h=r.Lb}oc[m]={Lc:m,Kc:b,Lb:h,cb:e,Qc:c,flags:d,offset:f};l=m}}return l}catch(v){return"undefined"!==typeof R&&v instanceof
O||t(v),-v.Wa}},$:function(){return 0},_:function(a,b){try{var c=oc[a];if(0!==b&&c){if(b===c.Kc){var d=Bb[c.cb];d&&c.Qc&2&&d&&d.Oa.Fb&&d.Oa.Fb(d,A.slice(a,a+b),c.offset,b,c.flags);oc[a]=null;c.Lb&&W(c.Lc)}var e=0}else e=-28;return e}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Wa}},D:function(a,b,c){qc=c;try{var d=z(a),e=c?rc():0;return Zb(d,b,e).cb}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Wa}},Y:function(a,b){try{return a=z(a),pc(a,b)}catch(c){return"undefined"!==
typeof R&&c instanceof O||t(c),-c.Wa}},d:function(a){var b=tc[a];delete tc[a];var c=b.Tb,d=b.hb,e=b.cc,f=e.map(function(h){return h.Dc}).concat(e.map(function(h){return h.Xc}));Ec([a],f,function(h){var l={};e.forEach(function(m,p){var n=h[p],r=m.Ab,v=m.Cc,k=h[p+e.length],u=m.Wc,x=m.Yc;l[m.zc]={read:function(y){return n.fromWireType(r(v,y))},write:function(y,H){var G=[];u(x,y,k.toWireType(G,H));uc(G)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in l)p[n]=l[n].read(m);d(m);return p},
toWireType:function(m,p){for(var n in l)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var r=c();for(n in l)l[n].write(r,p[n]);null!==m&&m.push(d,r);return r},argPackAdvance:8,readValueFromPointer:vc,bb:d}]})},M:function(){},fa:function(a,b,c,d,e){var f=Gc(c);b=S(b);Fc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=F;else if(2===c)l=ya;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(l[h>>f])},bb:null})},v:function(a,b,c,d,e,f,h,l,m,p,n,r,v){n=S(n);f=V(e,f);l&&(l=V(h,l));p&&(p=V(m,p));v=V(r,v);var k=zc(n);Uc(k,function(){ld("Cannot construct "+n+" due to unbound types",[d])});Ec([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.Pa;var y=x.mb}else y=Rc.prototype;u=Ac(k,function(){if(Object.getPrototypeOf(this)!==H)throw new Ic("Use 'new' to construct "+n);if(void 0===G.ib)throw new Ic(n+" has no accessible constructor");var w=G.ib[arguments.length];
if(void 0===w)throw new Ic("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.ib).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(y,{constructor:{value:u}});u.prototype=H;var G=new Vc(n,u,H,v,x,f,l,p);x=new ed(n,G,!0,!1);y=new ed(n+"*",G,!1,!1);var ha=new ed(n+" const*",G,!1,!0);Sc[a]={pointerType:y,vc:ha};fd(k,u);return[x,y,ha]})},I:function(a,b,c,d,e,f){0<b||t("Assertion failed: undefined");
var h=md(b,c);e=V(d,e);Ec([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.Pa.ib&&(l.Pa.ib=[]);if(void 0!==l.Pa.ib[b-1])throw new Ic("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.Pa.ib[b-1]=function(){ld("Cannot construct "+l.name+" due to unbound types",h)};Ec([],h,function(p){p.splice(1,0,null);l.Pa.ib[b-1]=od(m,p,null,
e,f);return[]});return[]})},k:function(a,b,c,d,e,f,h,l){var m=md(c,d);b=S(b);f=V(e,f);Ec([],[a],function(p){function n(){ld("Cannot call "+r+" due to unbound types",m)}p=p[0];var r=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.Pa.Rc.push(b);var v=p.Pa.mb,k=v[b];void 0===k||void 0===k.Va&&k.className!==p.name&&k.xb===c-2?(n.xb=c-2,n.className=p.name,v[b]=n):(Tc(v,b,r),v[b].Va[c-2]=n);Ec([],m,function(u){u=od(r,u,p,f,h);void 0===v[b].Va?(u.xb=c-2,v[b]=u):v[b].Va[c-2]=u;return[]});
return[]})},ea:function(a,b){b=S(b);Fc(a,{name:b,fromWireType:function(c){var d=X[c].value;qd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:vc,bb:null})},E:function(a,b,c){c=Gc(c);b=S(b);Fc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Yc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:rd(b,c),bb:null})},u:function(a,b,c,d,e,f){var h=
md(b,c);a=S(a);e=V(d,e);Uc(a,function(){ld("Cannot call "+a+" due to unbound types",h)},b-1);Ec([],h,function(l){fd(a,od(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},g:function(a,b,c,d,e){function f(p){return p}b=S(b);-1===e&&(e=4294967295);var h=Gc(c);if(0===d){var l=32-8*c;f=function(p){return p<<l>>>l}}var m=b.includes("unsigned");Fc(a,{name:b,fromWireType:f,toWireType:function(p,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Yc(n)+'" to '+
this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Yc(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:sd(b,h,0!==d),bb:null})},f:function(a,b,c){function d(f){f>>=2;var h=I;return new e(Ga,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);Fc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{Fc:!0})},F:function(a,b){b=S(b);var c="std::string"===b;Fc(a,{name:b,fromWireType:function(d){var e=I[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[d+4+h]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=(c&&f?function(){return va(e)}:function(){return e.length})(),l=Fa(4+h+1);I[l>>2]=h;if(c&&f)B(e,A,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(W(l),T("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<h;++f)A[l+4+f]=e[f];null!==d&&d.push(W,l);return l},argPackAdvance:8,readValueFromPointer:vc,bb:function(d){W(d)}})},r:function(a,b,c){c=S(c);if(2===b){var d=xa;var e=za;var f=
Aa;var h=function(){return C};var l=1}else 4===b&&(d=Ba,e=Ca,f=Da,h=function(){return I},l=2);Fc(a,{name:c,fromWireType:function(m){for(var p=I[m>>2],n=h(),r,v=m+4,k=0;k<=p;++k){var u=m+4+k*b;if(k==p||0==n[u>>l])v=d(v,u-v),void 0===r?r=v:(r+=String.fromCharCode(0),r+=v),v=u+b}W(m);return r},toWireType:function(m,p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var n=f(p),r=Fa(4+n+b);I[r>>2]=n>>l;e(p,r+4,n+b);null!==m&&m.push(W,r);return r},argPackAdvance:8,readValueFromPointer:vc,
bb:function(m){W(m)}})},e:function(a,b,c,d,e,f){tc[a]={name:S(b),Tb:V(c,d),hb:V(e,f),cc:[]}},a:function(a,b,c,d,e,f,h,l,m,p){tc[a].cc.push({zc:S(b),Dc:c,Ab:V(d,e),Cc:f,Xc:h,Wc:V(l,m),Yc:p})},ga:function(a,b){b=S(b);Fc(a,{Jc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ba:function(a){delete Dd[a-1]},O:function(){throw"longjmp";},h:function(a,b,c){a=Y(a);b=td(b,"emval::as");var d=[],e=U(d);E[c>>2]=e;return b.toWireType(d,a)},ma:function(a,b,c,d){a=Y(a);c=ud(b,c);for(var e=
Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return U(a)},n:function(a,b,c,d){a=xd[a];b=Y(b);c=wd(c);a(b,c,null,d)},y:qd,na:function(a,b){a=Y(a);b=Y(b);return a==b},la:function(a){if(0===a)return U(yd());a=wd(a);return U(yd()[a])},m:function(a,b){b=ud(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);
d="return function "+zc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Jc||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=nd(e).apply(null,f);return zd(a)},ja:function(a){a=wd(a);return U(g[a])},
i:function(a,b){a=Y(a);b=Y(b);return U(a[b])},J:function(a){4<a&&(X[a].Vb+=1)},t:function(a,b,c,d){a=Y(a);var e=Ad[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType",
"Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(td,g,U);Ad[b]=e}return e(a,c,d)},ia:function(){return U([])},K:function(a){return U(wd(a))},ka:function(){return U({})},pa:function(a){uc(X[a].value);qd(a)},p:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},l:function(a,b){a=td(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},oa:function(a){a=Y(a);return U(typeof a)},j:function(){t()},z:function(a,b){if(0===a)a=Date.now();else if(1===
a||4===a)a=Bd();else return-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},o:function(a,b,c){Cd.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,Cd.push(d?Ia[c++>>1]:E[c]),++c;return $a[a].apply(null,Cd)},da:function(){return!ja},P:function(a,b,c){A.copyWithin(a,b,b+c)},Q:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ra.grow(Math.min(2147483648,d)-Ga.byteLength+
65535>>>16);Ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ca:function(a,b,c,d,e){function f(D){Fd(D,h,p,n,m)}function h(D,be){Id(D,be.response,function(Va){Gd(function(){u?L.get(u)(Va):b&&b(Va)},K)},function(Va){Gd(function(){u?L.get(u)(Va):b&&b(Va)},K)})}function l(D){Fd(D,r,p,n,m)}function m(D){Gd(function(){H?L.get(H)(D):e&&e(D)},K)}function p(D){Gd(function(){x?L.get(x)(D):c&&c(D)},K)}function n(D){Gd(function(){y?L.get(y)(D):d&&d(D)},K)}function r(D){Gd(function(){u?L.get(u)(D):
b&&b(D)},K)}var v=a+112,k=z(v),u=I[v+36>>2],x=I[v+40>>2],y=I[v+44>>2],H=I[v+48>>2],G=I[v+52>>2],ha=!!(G&4),w=!!(G&32),J=!!(G&16),K=!!(G&64);if("EM_IDB_STORE"===k)k=I[v+84>>2],Id(a,A.slice(k,k+I[v+88>>2]),r,p);else if("EM_IDB_DELETE"===k)Kd(a,r,p);else if(J){if(w)return 0;Fd(a,ha?h:r,p,n,m)}else Jd(a,r,w?p:ha?f:l);return a},U:function(a,b){var c=0;Md().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=0;c+=d.length+1});return 0},V:function(a,b){var c=
Md();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},s:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);sa=!0}fa(a,new Hd(a))},q:function(a){try{var b=sc(a);ac(b);return 0}catch(c){return"undefined"!==typeof R&&c instanceof O||t(c),c.Wa}},T:function(a,b){try{var c=sc(a);F[b>>0]=c.Sa?2:Q(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof R&&d instanceof O||t(d),d.Wa}},B:function(a,b,c,d){try{a:{for(var e=sc(a),f=a=0;f<c;f++){var h=
E[b+(8*f+4)>>2],l=e,m=E[b+8*f>>2],p=h,n=void 0,r=F;if(0>p||0>n)throw new O(28);if(null===l.cb)throw new O(8);if(1===(l.flags&2097155))throw new O(8);if(Q(l.node.mode))throw new O(31);if(!l.Oa.read)throw new O(28);var v="undefined"!==typeof n;if(!v)n=l.position;else if(!l.seekable)throw new O(70);var k=l.Oa.read(l,r,m,p,n);v||(l.position+=k);var u=k;if(0>u){var x=-1;break a}a+=u;if(u<h)break}x=a}E[d>>2]=x;return 0}catch(y){return"undefined"!==typeof R&&y instanceof O||t(y),y.Wa}},L:function(a,b,c,
d,e){try{var f=sc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;bc(f,a,d);Za=[f.position>>>0,(M=f.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[e>>2]=Za[0];E[e+4>>2]=Za[1];f.Ob&&0===a&&0===d&&(f.Ob=null);return 0}catch(h){return"undefined"!==typeof R&&h instanceof O||t(h),h.Wa}},A:function(a,b,c,d){try{a:{for(var e=sc(a),f=a=0;f<c;f++){var h=cc(e,F,E[b+8*f>>2],E[b+(8*f+4)>>2],
void 0);if(0>h){var l=-1;break a}a+=h}l=a}E[d>>2]=l;return 0}catch(m){return"undefined"!==typeof R&&m instanceof O||t(m),m.Wa}},c:function(){return pa},qa:function(){var a=self.navigator.userAgent,b=va(a)+1,c=Fa(b);B(a,A,c,b);return c},R:Od,N:Xd,x:Yd,w:Zd,ha:function(a){fb||(fb=!0,bb());var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),
l=Math.min(h,f);0>c?E[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},b:function(a){pa=a},G:Ud,S:function(a,b,c,d){return Ud(a,b,c,d)},H:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;ra=g.asm.ra;Ja();L=g.asm.Ea;La.unshift(g.asm.sa);Sa("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){q("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:$d};Ra("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return q("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return qa||
"function"!==typeof WebAssembly.instantiateStreaming||Ta()||"function"!==typeof fetch?c(b):fetch(Ua,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){q("wasm streaming compile failed: "+f);q("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.sa).apply(null,arguments)};
var W=g._free=function(){return(W=g._free=g.asm.ta).apply(null,arguments)},Fa=g._malloc=function(){return(Fa=g._malloc=g.asm.ua).apply(null,arguments)},kd=g.___getTypeName=function(){return(kd=g.___getTypeName=g.asm.va).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.wa).apply(null,arguments)};
var eb=g.__get_tzname=function(){return(eb=g.__get_tzname=g.asm.xa).apply(null,arguments)},db=g.__get_daylight=function(){return(db=g.__get_daylight=g.asm.ya).apply(null,arguments)},cb=g.__get_timezone=function(){return(cb=g.__get_timezone=g.asm.za).apply(null,arguments)},ae=g.stackSave=function(){return(ae=g.stackSave=g.asm.Aa).apply(null,arguments)},ce=g.stackRestore=function(){return(ce=g.stackRestore=g.asm.Ba).apply(null,arguments)},de=g._setThrew=function(){return(de=g._setThrew=g.asm.Ca).apply(null,
arguments)},tb=g._memalign=function(){return(tb=g._memalign=g.asm.Da).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Fa).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Ga).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ha).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ia).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ja).apply(null,arguments)};
g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Ka).apply(null,arguments)};function Yd(a,b){var c=ae();try{L.get(a)(b)}catch(d){ce(c);if(d!==d+0&&"longjmp"!==d)throw d;de(1,0)}}function Zd(a,b,c){var d=ae();try{L.get(a)(b,c)}catch(e){ce(d);if(e!==e+0&&"longjmp"!==e)throw e;de(1,0)}}function Xd(a,b,c,d){var e=ae();try{return L.get(a)(b,c,d)}catch(f){ce(e);if(f!==f+0&&"longjmp"!==f)throw f;de(1,0)}}g.addRunDependency=Ra;g.removeRunDependency=Sa;g.FS_createPath=gc;g.FS_createDataFile=ic;
g.FS_createPreloadedFile=mc;g.FS_createLazyFile=lc;g.FS_createDevice=jc;g.FS_unlink=Xb;var ee;function Hd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Qa=function fe(){ee||ge();ee||(Qa=fe)};
function ge(){function a(){if(!ee&&(ee=!0,g.calledRun=!0,!sa)){g.noFSInit||ec||(ec=!0,dc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?jc("/dev","stdin",g.stdin):Wb("/dev/tty","/dev/stdin"),g.stdout?jc("/dev","stdout",null,g.stdout):Wb("/dev/tty","/dev/stdout"),g.stderr?jc("/dev","stderr",null,g.stderr):Wb("/dev/tty1","/dev/stderr"),Zb("/dev/stdin",0),Zb("/dev/stdout",1),Zb("/dev/stderr",1));Eb=!1;ab(La);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ma.unshift(b)}ab(Ma)}}if(!(0<Oa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Na();ab(Ka);0<Oa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ge;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ge();


  return BlinkIDImageCaptureWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDImageCaptureWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDImageCaptureWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDImageCaptureWasmSDK"] = BlinkIDImageCaptureWasmSDK;
