
var BlinkIDImageCaptureWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDImageCaptureWasmSDK) {
  BlinkIDImageCaptureWasmSDK = BlinkIDImageCaptureWasmSDK || {};


var g;g||(g=typeof BlinkIDImageCaptureWasmSDK !== 'undefined' ? BlinkIDImageCaptureWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.Ob||(g.Ob=0);g.Ob++;
(function(a){function b(m,p,n){var q=new XMLHttpRequest;q.open("GET",m,!0);q.responseType="arraybuffer";q.onprogress=function(v){var k=p;v.total&&(k=v.total);if(v.loaded){q.rc?g.lb[m].loaded=v.loaded:(q.rc=!0,g.lb||(g.lb={}),g.lb[m]={loaded:v.loaded,total:k});var u=k=v=0,x;for(x in g.lb){var y=g.lb[x];v+=y.total;k+=y.loaded;u++}v=Math.ceil(v*g.Ob/u);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+v+")")}else!g.lb&&g.setStatus&&g.setStatus("Downloading data...")};q.onerror=function(){throw Error("NetworkError for: "+
m);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)n(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.vc=v;v=a.files;for(var k=
0;k<v.length;++k)m.prototype.Xb[v[k].filename].onload();g.removeRunDependency("datafile_../../resources/basic/BlinkIDImageCaptureWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={Xb:{},open:function(v,k){this.name=k;this.Xb[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.vc.subarray(this.start,this.end))},finish:function(v){g.FS_createDataFile(this.name,null,v,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.Xb[this.name]=null}};
for(var n=a.files,q=0;q<n.length;++q)(new m(n[q].start,n[q].end,n[q].audio)).open("GET",n[q].filename);g.addRunDependency("datafile_../../resources/basic/BlinkIDImageCaptureWasmSDK.data");g.jc||(g.jc={});g.jc["../../resources/basic/BlinkIDImageCaptureWasmSDK.data"]={gd:!1};l?(p(l),l=null):h=p}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,r("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkIDImageCaptureWasmSDK.data",""):"BlinkIDImageCaptureWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_Detector_general_6.7.0.strop",start:0,end:288208,audio:0},{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",start:288208,end:292146,audio:0},{filename:"/microblink/BlinkID_Analyzer_general_6.6.0.strop",start:292146,end:308884,audio:0},{filename:"/microblink/BlinkID_Classifier_general_6.15.0.strop",start:308884,
end:837814,audio:0},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:837814,end:844632,audio:0},{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",start:844632,end:851514,audio:0},{filename:"/microblink/BlinkID_RotationClassifier_general_6.2.0.strop",start:851514,end:908028,audio:0},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",start:908028,end:1277820,audio:0}],remote_package_size:1277820,package_uuid:"5aaa3657-20b2-490f-bf66-6da4065e3b43"});
var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in g)g.hasOwnProperty(da)&&(ca[da]=g[da]);var ea="./this.program";function fa(a,b){throw b;}var ia=!1,ja=!1;ia="object"===typeof window;ja="function"===typeof importScripts;var ka="",la,ma;
if(ia||ja)ja?ka=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ka=document.currentScript.src),_scriptDir&&(ka=_scriptDir),ka=0!==ka.indexOf("blob:")?ka.substr(0,ka.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ja&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(g[da]=ca[da]);ca=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var oa=0,pa;g.wasmBinary&&(pa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&t("no native wasm support detected");var qa,ra=!1,sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?ta(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&C[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=xa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)xa[b>>1]=a.charCodeAt(e),b+=2;xa[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Da(a){var b=ua(a)+1,c=Ea(b);c&&B(a,F,c,b);return c}var Fa,F,A,xa,C,E,I,Ga,Ha;
function Ia(){var a=qa.buffer;Fa=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=xa=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=C=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=Ga=new Float32Array(a);g.HEAPF64=Ha=new Float64Array(a)}var L,Ja=[],Ka=[],La=[];function Ma(){var a=g.preRun.shift();Ja.unshift(a)}var Na=0,Oa=null,Pa=null;function Qa(){Na++;g.monitorRunDependencies&&g.monitorRunDependencies(Na)}
function Ra(){Na--;g.monitorRunDependencies&&g.monitorRunDependencies(Na);if(0==Na&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa)){var a=Pa;Pa=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);a+="";r(a);ra=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Sa(){return Ta.startsWith("data:application/octet-stream;base64,")}var Ta="BlinkIDImageCaptureWasmSDK.wasm";
if(!Sa()){var Va=Ta;Ta=g.locateFile?g.locateFile(Va,ka):ka+Va}function Wa(){var a=Ta;try{if(a==Ta&&pa)return new Uint8Array(pa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}function Xa(){return pa||!ia&&!ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Wa()}):fetch(Ta,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ta+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}
var M,Ya,Za={292837:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},292973:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},293189:function(a,b){a=z(a);b=z(b);throw Error(a+b);},293299:function(a,b){a=z(a);b=z(b);console.log(a+b)},293397:function(a){throw Error(z(a));},293440:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};
function $a(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.hd;"number"===typeof c?void 0===b.Nb?L.get(c)():L.get(c)(b.Nb):c(void 0===b.Nb?null:b.Nb)}}}
function ab(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(!bb){bb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);E[cb()>>2]=60*f;E[db()>>2]=Number(b!=e);c=a(c);d=a(d);c=Da(c);d=Da(d);e<b?(E[eb()>>2]=c,E[eb()+4>>2]=d):(E[eb()>>2]=d,E[eb()+4>>2]=c)}}var bb;
function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function N(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function gb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function hb(a){if("/"===a)return"/";a=N(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ib(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){t("randomDevice")}}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],Wa:[],pb:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.ub];if(!b)throw new O(43);a.Ta=b;a.seekable=!1},close:function(a){a.Ta.pb.flush(a.Ta)},flush:function(a){a.Ta.pb.flush(a.Ta)},read:function(a,b,c,d){if(!a.Ta||!a.Ta.pb.fc)throw new O(60);for(var e=0,f=0;f<d;f++){try{var h=a.Ta.pb.fc(a.Ta)}catch(l){throw new O(29);}if(void 0===h&&0===e)throw new O(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ta||!a.Ta.pb.Tb)throw new O(60);try{for(var e=
0;e<d;e++)a.Ta.pb.Tb(a.Ta,b[c+e])}catch(f){throw new O(29);}d&&(a.node.timestamp=Date.now());return e}},pb={fc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},Tb:function(a,b){null===b||10===b?(na(ta(a.Wa,0)),a.Wa=[]):0!=b&&a.Wa.push(b)},flush:function(a){a.Wa&&0<a.Wa.length&&
(na(ta(a.Wa,0)),a.Wa=[])}},qb={Tb:function(a,b){null===b||10===b?(r(ta(a.Wa,0)),a.Wa=[]):0!=b&&a.Wa.push(b)},flush:function(a){a.Wa&&0<a.Wa.length&&(r(ta(a.Wa,0)),a.Wa=[])}},P={gb:null,hb:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.gb||(P.gb={dir:{node:{fb:P.Oa.fb,Za:P.Oa.Za,rb:P.Oa.rb,Eb:P.Oa.Eb,nc:P.Oa.nc,Lb:P.Oa.Lb,oc:P.Oa.oc,mc:P.Oa.mc,Hb:P.Oa.Hb},stream:{kb:P.Pa.kb}},file:{node:{fb:P.Oa.fb,Za:P.Oa.Za},
stream:{kb:P.Pa.kb,read:P.Pa.read,write:P.Pa.write,Yb:P.Pa.Yb,Fb:P.Pa.Fb,Gb:P.Pa.Gb}},link:{node:{fb:P.Oa.fb,Za:P.Oa.Za,vb:P.Oa.vb},stream:{}},$b:{node:{fb:P.Oa.fb,Za:P.Oa.Za},stream:rb}});c=sb(a,b,c,d);Q(c.mode)?(c.Oa=P.gb.dir.node,c.Pa=P.gb.dir.stream,c.Na={}):32768===(c.mode&61440)?(c.Oa=P.gb.file.node,c.Pa=P.gb.file.stream,c.Sa=0,c.Na=null):40960===(c.mode&61440)?(c.Oa=P.gb.link.node,c.Pa=P.gb.link.stream):8192===(c.mode&61440)&&(c.Oa=P.gb.$b.node,c.Pa=P.gb.$b.stream);c.timestamp=Date.now();a&&
(a.Na[b]=c,a.timestamp=c.timestamp);return c},jd:function(a){return a.Na?a.Na.subarray?a.Na.subarray(0,a.Sa):new Uint8Array(a.Na):new Uint8Array(0)},cc:function(a,b){var c=a.Na?a.Na.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Na,a.Na=new Uint8Array(b),0<a.Sa&&a.Na.set(c.subarray(0,a.Sa),0))},Uc:function(a,b){if(a.Sa!=b)if(0==b)a.Na=null,a.Sa=0;else{var c=a.Na;a.Na=new Uint8Array(b);c&&a.Na.set(c.subarray(0,Math.min(b,a.Sa)));a.Sa=b}},Oa:{fb:function(a){var b=
{};b.yc=8192===(a.mode&61440)?a.id:1;b.Qb=a.id;b.mode=a.mode;b.Pc=1;b.uid=0;b.Fc=0;b.ub=a.ub;b.size=Q(a.mode)?4096:32768===(a.mode&61440)?a.Sa:40960===(a.mode&61440)?a.link.length:0;b.sc=new Date(a.timestamp);b.Oc=new Date(a.timestamp);b.xc=new Date(a.timestamp);b.tc=4096;b.uc=Math.ceil(b.size/b.tc);return b},Za:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Uc(a,b.size)},rb:function(){throw tb[44];},Eb:function(a,b,c,d){return P.createNode(a,
b,c,d)},nc:function(a,b,c){if(Q(a.mode)){try{var d=ub(b,c)}catch(f){}if(d)for(var e in d.Na)throw new O(55);}delete a.parent.Na[a.name];a.parent.timestamp=Date.now();a.name=c;b.Na[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Lb:function(a,b){delete a.Na[b];a.timestamp=Date.now()},oc:function(a,b){var c=ub(a,b),d;for(d in c.Na)throw new O(55);delete a.Na[b];a.timestamp=Date.now()},mc:function(a){var b=[".",".."],c;for(c in a.Na)a.Na.hasOwnProperty(c)&&b.push(c);return b},Hb:function(a,b,c){a=P.createNode(a,
b,41471,0);a.link=c;return a},vb:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},Pa:{read:function(a,b,c,d,e){var f=a.node.Na;if(e>=a.node.Sa)return 0;a=Math.min(a.node.Sa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===F.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Na||a.Na.subarray)){if(f)return a.Na=b.subarray(c,c+d),a.Sa=d;if(0===a.Sa&&0===e)return a.Na=
b.slice(c,c+d),a.Sa=d;if(e+d<=a.Sa)return a.Na.set(b.subarray(c,c+d),e),d}P.cc(a,e+d);if(a.Na.subarray&&b.subarray)a.Na.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Na[e+f]=b[c+f];a.Sa=Math.max(a.Sa,e+d);return d},kb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Sa);if(0>b)throw new O(28);return b},Yb:function(a,b,c){P.cc(a.node,b+c);a.node.Sa=Math.max(a.node.Sa,b+c)},Fb:function(a,b,c,d,e,f){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);
a=a.node.Na;if(f&2||a.buffer!==Fa){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=65536*Math.ceil(c/65536);for(b=Ea(f);c<f;)F[b+c++]=0;c=b;if(!c)throw new O(48);F.set(a,c)}else d=!1,c=a.byteOffset;return{Ra:c,Mb:d}},Gb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new O(43);if(e&2)return 0;P.Pa.write(a,b,0,d,c,!1);return 0}}},vb=null,wb={},xb=[],yb=1,zb=null,Ab={},O=null,tb={};
function Bb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ec:!0,Vb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Vb)throw new O(32);a=fb(a.split("/").filter(function(h){return!!h}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ub(e,a[d]);c=N(c+"/"+a[d]);e.sb&&(!f||f&&b.ec)&&(e=e.sb.root);if(!f||b.Ab)for(f=0;40960===(e.mode&61440);)if(e=Cb(c),c=jb(gb(c),e),e=Bb(c,{Vb:b.Vb}).node,40<f++)throw new O(32);}return{path:c,node:e}}
function Db(a){for(var b;;){if(a===a.parent)return a=a.hb.ic,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Eb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function ub(a,b){var c;if(c=a.Oa.rb?0:2)throw new O(c,a);for(c=zb[Eb(a.id,b)];c;c=c.ob){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Oa.rb(a,b)}function sb(a,b,c,d){a=new Fb(a,b,c,d);b=Eb(a.parent.id,a.name);a.ob=zb[b];return zb[b]=a}
function Q(a){return 16384===(a&61440)}var Gb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Hb(a,b){try{return ub(a,b),20}catch(c){}return 0}function Ib(a){var b=4096;for(a=a||0;a<=b;a++)if(!xb[a])return a;throw new O(33);}function Jb(a,b){Kb||(Kb=function(){},Kb.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Kb,d;for(d in a)c[d]=a[d];a=c;b=Ib(b);a.eb=b;return xb[b]=a}
var rb={open:function(a){a.Pa=wb[a.node.ub].Pa;a.Pa.open&&a.Pa.open(a)},kb:function(){throw new O(70);}};function mb(a,b){wb[a]={Pa:b}}function Lb(a,b){var c="/"===b,d=!b;if(c&&vb)throw new O(10);if(!c&&!d){var e=Bb(b,{ec:!1});b=e.path;e=e.node;if(e.sb)throw new O(10);if(!Q(e.mode))throw new O(54);}b={type:a,md:{},ic:b,Nc:[]};a=a.hb(b);a.hb=b;b.root=a;c?vb=a:e&&(e.sb=b,e.hb&&e.hb.Nc.push(b))}
function Mb(a,b,c){var d=Bb(a,{parent:!0}).node;a=hb(a);if(!a||"."===a||".."===a)throw new O(28);var e=Hb(d,a);if(e)throw new O(e);if(!d.Oa.Eb)throw new O(63);return d.Oa.Eb(d,a,b,c)}function Nb(a){return Mb(a,16895,0)}function Ob(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Mb(a,b|8192,c)}function Pb(a,b){if(!jb(a))throw new O(44);var c=Bb(b,{parent:!0}).node;if(!c)throw new O(44);b=hb(b);var d=Hb(c,b);if(d)throw new O(d);if(!c.Oa.Hb)throw new O(63);c.Oa.Hb(c,b,a)}
function Qb(a){var b=Bb(a,{parent:!0}).node,c=hb(a),d=ub(b,c);a:{try{var e=ub(b,c)}catch(f){e=f.Va;break a}e=Q(e.mode)?31:0}if(e)throw new O(e);if(!b.Oa.Lb)throw new O(63);if(d.sb)throw new O(10);try{Ab.willDeletePath&&Ab.willDeletePath(a)}catch(f){r("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Oa.Lb(b,c);b=Eb(d.parent.id,d.name);if(zb[b]===d)zb[b]=d.ob;else for(b=zb[b];b;){if(b.ob===d){b.ob=d.ob;break}b=b.ob}try{if(Ab.onDeletePath)Ab.onDeletePath(a)}catch(f){r("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+f.message)}}function Cb(a){a=Bb(a).node;if(!a)throw new O(44);if(!a.Oa.vb)throw new O(28);return jb(Db(a.parent),a.Oa.vb(a))}function Rb(a,b){a="string"===typeof a?Bb(a,{Ab:!0}).node:a;if(!a.Oa.Za)throw new O(63);a.Oa.Za(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Sb(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var e=Gb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=N(a);try{f=Bb(a,{Ab:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new O(20);}else f=Mb(a,c,0),e=!0;if(!f)throw new O(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!Q(f.mode))throw new O(54);if(!e){if(f)if(40960===(f.mode&61440))c=32;else{if(c=
Q(f.mode))c=["r","w","rw"][b&3],b&512&&(c+="w"),c="r"!==c||b&512;c=c?31:0}else c=44;if(c)throw new O(c);}if(b&512){c=f;c="string"===typeof c?Bb(c,{Ab:!0}).node:c;if(!c.Oa.Za)throw new O(63);if(Q(c.mode))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);c.Oa.Za(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Jb({node:f,path:Db(f),flags:b,seekable:!0,position:0,Pa:f.Pa,ed:[],error:!1},d);d.Pa.open&&d.Pa.open(d);!g.logReadFiles||b&1||(Tb||(Tb={}),a in Tb||(Tb[a]=1,r("FS.trackingDelegate error on read file: "+
a)));try{Ab.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Ab.onOpenFile(a,f))}catch(h){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function Ub(a){if(null===a.eb)throw new O(8);a.Pb&&(a.Pb=null);try{a.Pa.close&&a.Pa.close(a)}catch(b){throw b;}finally{xb[a.eb]=null}a.eb=null}
function Vb(a,b,c){if(null===a.eb)throw new O(8);if(!a.seekable||!a.Pa.kb)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.Pa.kb(a,b,c);a.ed=[]}
function Wb(a,b,c,d,e,f){if(0>d||0>e)throw new O(28);if(null===a.eb)throw new O(8);if(0===(a.flags&2097155))throw new O(8);if(Q(a.node.mode))throw new O(31);if(!a.Pa.write)throw new O(28);a.seekable&&a.flags&1024&&Vb(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new O(70);b=a.Pa.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&Ab.onWriteToFile)Ab.onWriteToFile(a.path)}catch(l){r("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function Xb(){O||(O=function(a,b){this.node=b;this.Wc=function(c){this.Va=c};this.Wc(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){tb[a]=new O(a);tb[a].stack="<generic error, no stack>"}))}var Yb;function Zb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function $b(a,b){a="string"===typeof a?a:Db(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=N(a+"/"+c);try{Nb(d)}catch(e){}a=d}}return d}
function ac(a,b,c,d){a=N(("string"===typeof a?a:Db(a))+"/"+b);c=Zb(c,d);return Mb(a,(void 0!==c?c:438)&4095|32768,0)}function bc(a,b,c,d,e,f){a=b?N(("string"===typeof a?a:Db(a))+"/"+b):a;d=Zb(d,e);e=Mb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Rb(e,d|146);a=Sb(e,577);Wb(a,c,0,c.length,0,f);Ub(a);Rb(e,d)}return e}
function cc(a,b,c,d){a=N(("string"===typeof a?a:Db(a))+"/"+b);b=Zb(!!c,!!d);cc.hc||(cc.hc=64);var e=cc.hc++<<8|0;mb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var p=0,n=0;n<m;n++){try{var q=c()}catch(v){throw new O(29);}if(void 0===q&&0===p)throw new O(6);if(null===q||void 0===q)break;p++;h[l+n]=q}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{d(h[l+p])}catch(n){throw new O(29);}m&&
(f.node.timestamp=Date.now());return p}});return Ob(a,b,e)}function dc(a){if(!(a.Ic||a.Jc||a.link||a.Na)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.Na=ob(la(a.url),!0),a.Sa=a.Na.length}catch(b){throw new O(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function ec(a,b,c,d,e){function f(){this.Sb=!1;this.zb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.ac;return this.Bb(n/this.ac|0)[q]}};f.prototype.Vc=function(n){this.Bb=n};f.prototype.Zb=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=
(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=q);var x=this;x.Vc(function(y){var H=y*u,G=(y+1)*u-1;G=Math.min(G,q-1);if("undefined"===typeof x.zb[y]){var ha=x.zb;if(H>G)throw Error("invalid range ("+H+", "+G+") or no bytes requested!");if(G>q-1)throw Error("only "+q+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);q!==u&&w.setRequestHeader("Range","bytes="+H+"-"+G);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);H=void 0!==w.response?new Uint8Array(w.response||[]):ob(w.responseText||"",!0);ha[y]=H}if("undefined"===typeof x.zb[y])throw Error("doXHR failed!");return x.zb[y]});if(n||!q)u=q=1,u=q=this.Bb(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.qc=q;this.pc=u;this.Sb=!0};if("undefined"!==
typeof XMLHttpRequest){if(!ja)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.Sb||this.Zb();return this.qc}},ac:{get:function(){this.Sb||this.Zb();return this.pc}}});var l=void 0}else l=c,h=void 0;var m=ac(a,b,d,e);h?m.Na=h:l&&(m.Na=null,m.url=l);Object.defineProperties(m,{Sa:{get:function(){return this.Na.length}}});var p={};Object.keys(m.Pa).forEach(function(n){var q=
m.Pa[n];p[n]=function(){dc(m);return q.apply(null,arguments)}});p.read=function(n,q,v,k,u){dc(m);n=n.node.Na;if(u>=n.length)return 0;k=Math.min(n.length-u,k);if(n.slice)for(var x=0;x<k;x++)q[v+x]=n[u+x];else for(x=0;x<k;x++)q[v+x]=n.get(u+x);return k};m.Pa=p;return m}
function fc(a,b,c,d,e,f,h,l,m,p){function n(k){function u(y){p&&p();l||bc(a,b,y,d,e,m);f&&f();Ra(v)}var x=!1;g.preloadPlugins.forEach(function(y){!x&&y.canHandle(q)&&(y.handle(k,q,u,function(){h&&h();Ra(v)}),x=!0)});x||u(k)}gc.kd();var q=b?jb(N(a+"/"+b)):a,v="cp "+q;Qa(v);"string"==typeof c?gc.fd(c,function(k){n(k)},h):n(c)}var R={},Kb,Tb,hc={};
function ic(a,b){try{var c=Bb(a,{Ab:!0}).node;if(!c)throw new O(44);if(!c.Oa.fb)throw new O(63);var d=c.Oa.fb(c)}catch(e){if(e&&e.node&&N(a)!==N(Db(e.node)))return-54;throw e;}E[b>>2]=d.yc;E[b+4>>2]=0;E[b+8>>2]=d.Qb;E[b+12>>2]=d.mode;E[b+16>>2]=d.Pc;E[b+20>>2]=d.uid;E[b+24>>2]=d.Fc;E[b+28>>2]=d.ub;E[b+32>>2]=0;Ya=[d.size>>>0,(M=d.size,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+40>>2]=Ya[0];E[b+44>>2]=Ya[1];E[b+48>>
2]=4096;E[b+52>>2]=d.uc;E[b+56>>2]=d.sc.getTime()/1E3|0;E[b+60>>2]=0;E[b+64>>2]=d.Oc.getTime()/1E3|0;E[b+68>>2]=0;E[b+72>>2]=d.xc.getTime()/1E3|0;E[b+76>>2]=0;Ya=[d.Qb>>>0,(M=d.Qb,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:0)];E[b+80>>2]=Ya[0];E[b+84>>2]=Ya[1];return 0}var jc=void 0;function kc(){jc+=4;return E[jc-4>>2]}function lc(a){a=xb[a];if(!a)throw new O(8);return a}var mc={};
function nc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function oc(a){return this.fromWireType(I[a>>2])}var pc={},qc={},rc={};function sc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function tc(a,b){a=sc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function uc(a){var b=Error,c=tc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var vc=void 0;function wc(a){throw new vc(a);}
function xc(a,b,c){function d(l){l=c(l);l.length!==a.length&&wc("Mismatched type converter count");for(var m=0;m<a.length;++m)yc(a[m],l[m])}a.forEach(function(l){rc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){qc.hasOwnProperty(l)?e[m]=qc[l]:(f.push(l),pc.hasOwnProperty(l)||(pc[l]=[]),pc[l].push(function(){e[m]=qc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function zc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ac=void 0;function S(a){for(var b="";A[a];)b+=Ac[A[a++]];return b}var Bc=void 0;function T(a){throw new Bc(a);}
function yc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(qc.hasOwnProperty(a)){if(c.Gc)return;T("Cannot register type '"+d+"' twice")}qc[a]=b;delete rc[a];pc.hasOwnProperty(a)&&(b=pc[a],delete pc[a],b.forEach(function(e){e()}))}function Cc(a){T(a.Ma.Ua.Qa.name+" instance already deleted")}var Dc=!1;function Ec(){}
function Fc(a){--a.count.value;0===a.count.value&&(a.$a?a.ab.ib(a.$a):a.Ua.Qa.ib(a.Ra))}function Gc(a){if("undefined"===typeof FinalizationGroup)return Gc=function(b){return b},a;Dc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Ra?Fc(c):console.warn("object already deleted: "+c.Ra)});Gc=function(b){Dc.register(b,b.Ma,b.Ma);return b};Ec=function(b){Dc.unregister(b.Ma)};return Gc(a)}var Hc=void 0,Ic=[];
function Jc(){for(;Ic.length;){var a=Ic.pop();a.Ma.mb=!1;a["delete"]()}}function Kc(){}var Lc={};function Mc(a,b,c){if(void 0===a[b].Xa){var d=a[b];a[b]=function(){a[b].Xa.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].Xa+")!");return a[b].Xa[arguments.length].apply(this,arguments)};a[b].Xa=[];a[b].Xa[d.yb]=d}}
function Nc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].Xa&&void 0!==g[a].Xa[c])&&T("Cannot register public name '"+a+"' twice"),Mc(g,a,a),g.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].Xa[c]=b):(g[a]=b,void 0!==c&&(g[a].ld=c))}function Oc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.nb=c;this.ib=d;this.bb=e;this.Bc=f;this.xb=h;this.zc=l;this.Sc=[]}
function Pc(a,b,c){for(;b!==c;)b.xb||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.xb(a),b=b.bb;return a}function Qc(a,b){if(null===b)return this.Rb&&T("null is not a valid "+this.name),0;b.Ma||T('Cannot pass "'+Rc(b)+'" as a '+this.name);b.Ma.Ra||T("Cannot pass deleted object as a pointer of type "+this.name);return Pc(b.Ma.Ra,b.Ma.Ua.Qa,this.Qa)}
function Sc(a,b){if(null===b){this.Rb&&T("null is not a valid "+this.name);if(this.Db){var c=this.Ub();null!==a&&a.push(this.ib,c);return c}return 0}b.Ma||T('Cannot pass "'+Rc(b)+'" as a '+this.name);b.Ma.Ra||T("Cannot pass deleted object as a pointer of type "+this.name);!this.Cb&&b.Ma.Ua.Cb&&T("Cannot convert argument of type "+(b.Ma.ab?b.Ma.ab.name:b.Ma.Ua.name)+" to parameter type "+this.name);c=Pc(b.Ma.Ra,b.Ma.Ua.Qa,this.Qa);if(this.Db)switch(void 0===b.Ma.$a&&T("Passing raw pointer to smart pointer is illegal"),
this.$c){case 0:b.Ma.ab===this?c=b.Ma.$a:T("Cannot convert argument of type "+(b.Ma.ab?b.Ma.ab.name:b.Ma.Ua.name)+" to parameter type "+this.name);break;case 1:c=b.Ma.$a;break;case 2:if(b.Ma.ab===this)c=b.Ma.$a;else{var d=b.clone();c=this.Tc(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ib,c)}break;default:T("Unsupporting sharing policy")}return c}
function Tc(a,b){if(null===b)return this.Rb&&T("null is not a valid "+this.name),0;b.Ma||T('Cannot pass "'+Rc(b)+'" as a '+this.name);b.Ma.Ra||T("Cannot pass deleted object as a pointer of type "+this.name);b.Ma.Ua.Cb&&T("Cannot convert argument of type "+b.Ma.Ua.name+" to parameter type "+this.name);return Pc(b.Ma.Ra,b.Ma.Ua.Qa,this.Qa)}function Uc(a,b,c){if(b===c)return a;if(void 0===c.bb)return null;a=Uc(a,b,c.bb);return null===a?null:c.zc(a)}var Vc={};
function Wc(a,b){for(void 0===b&&T("ptr should not be undefined");a.bb;)b=a.xb(b),a=a.bb;return Vc[b]}function Xc(a,b){b.Ua&&b.Ra||wc("makeClassHandle requires ptr and ptrType");!!b.ab!==!!b.$a&&wc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Gc(Object.create(a,{Ma:{value:b}}))}
function Yc(a,b,c,d){this.name=a;this.Qa=b;this.Rb=c;this.Cb=d;this.Db=!1;this.ib=this.Tc=this.Ub=this.lc=this.$c=this.Qc=void 0;void 0!==b.bb?this.toWireType=Sc:(this.toWireType=d?Qc:Tc,this.cb=null)}function Zc(a,b,c){g.hasOwnProperty(a)||wc("Replacing nonexistant public symbol");void 0!==g[a].Xa&&void 0!==c?g[a].Xa[c]=b:(g[a]=b,g[a].yb=c)}
function $c(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function V(a,b){a=S(a);var c=a.includes("j")?$c(a,b):L.get(b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var ad=void 0;function bd(a){a=cd(a);var b=S(a);W(a);return b}
function dd(a,b){function c(f){e[f]||qc[f]||(rc[f]?rc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new ad(a+": "+d.map(bd).join([", "]));}function ed(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function fd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=tc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function gd(a,b,c,d,e){var f=b.length;2>f&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].cb){l=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+sc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var q=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[T,d,e,nc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].cb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].cb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return fd(p).apply(null,d)}var hd=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function jd(a){4<a&&0===--X[a].Wb&&(X[a]=void 0,hd.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=hd.length?hd.pop():X.length;X[b]={Wb:1,value:a};return b}}function Rc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function kd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ga[c>>2])};case 3:return function(c){return this.fromWireType(Ha[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ld(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return A[d]};case 1:return c?function(d){return xa[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Y(a){a||T("Cannot use deleted val. handle = "+a);return X[a].value}function md(a,b){var c=qc[a];void 0===c&&T(b+" has unknown type "+bd(a));return c}
function nd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=md(E[(b>>2)+d],"parameter "+d);return c}var od={};function pd(a){var b=od[a];return void 0===b?S(a):b}var qd=[];function rd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function sd(a){var b=qd.length;qd.push(a);return b}var td={},ud;ud=function(){return performance.now()};var vd=[];function wd(){return!ja}g._emscripten_is_main_browser_thread=wd;var xd=[];function Z(a,b){I[a>>2]=b;I[a+4>>2]=b/4294967296|0}var yd;
function zd(a,b,c,d,e){function f(J){var K=0,D=0;J&&(D=w.response?w.response.byteLength:0,K=Ea(D),A.set(new Uint8Array(w.response),K));I[a+12>>2]=K;Z(a+16,D)}var h=I[a+8>>2];if(h){var l=z(h),m=a+112,p=z(m);p||(p="GET");var n=I[m+52>>2],q=I[m+56>>2],v=!!I[m+60>>2],k=I[m+68>>2],u=I[m+72>>2];h=I[m+76>>2];var x=I[m+80>>2],y=I[m+84>>2];m=I[m+88>>2];var H=!!(n&1),G=!!(n&2);n=!!(n&64);k=k?z(k):void 0;u=u?z(u):void 0;var ha=x?z(x):void 0,w=new XMLHttpRequest;w.withCredentials=v;w.open(p,l,!n,k,u);n||(w.timeout=
q);w.od=l;w.responseType="arraybuffer";x&&w.overrideMimeType(ha);if(h)for(;;){p=I[h>>2];if(!p)break;l=I[h+4>>2];if(!l)break;h+=8;p=z(p);l=z(l);w.setRequestHeader(p,l)}xd.push(w);I[a+0>>2]=xd.length;h=y&&m?A.slice(y,y+m):null;w.onload=function(J){f(H&&!G);var K=w.response?w.response.byteLength:0;Z(a+24,0);K&&Z(a+32,K);C[a+40>>1]=w.readyState;C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,J):c&&c(a,w,J)};w.onerror=function(J){f(H);var K=w.status;Z(a+
24,0);Z(a+32,w.response?w.response.byteLength:0);C[a+40>>1]=w.readyState;C[a+42>>1]=K;c&&c(a,w,J)};w.ontimeout=function(J){c&&c(a,w,J)};w.onprogress=function(J){var K=H&&G&&w.response?w.response.byteLength:0,D=0;H&&G&&(D=Ea(K),A.set(new Uint8Array(w.response),D));I[a+12>>2]=D;Z(a+16,K);Z(a+24,J.loaded-K);Z(a+32,J.total);C[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<J.loaded&&(w.status=200);C[a+42>>1]=w.status;w.statusText&&B(w.statusText,A,a+44,64);d&&d(a,w,J);D&&W(D)};w.onreadystatechange=
function(J){C[a+40>>1]=w.readyState;2<=w.readyState&&(C[a+42>>1]=w.status);e&&e(a,w,J)};try{w.send(h)}catch(J){c&&c(a,w,J)}}else c(a,0,"no url specified!")}function Ad(a,b){if(!ra)if(b)a();else try{a()}catch(c){if(!(c instanceof Bd)&&"unwind"!==c)throw c&&"object"===typeof c&&c.stack&&r("exception thrown: "+[c,c.stack]),c;}}
function Cd(a,b,c,d){var e=yd;if(e){var f=I[a+112+64>>2];f||(f=I[a+8>>2]);var h=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,h)};l.onerror=function(m){C[a+40>>1]=4;C[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Dd(a,b,c){var d=yd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Ea(l);A.set(new Uint8Array(h),m);I[a+12>>2]=m;Z(a+16,l);Z(a+24,0);Z(a+32,l);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)}else C[a+40>>1]=4,C[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Ed(a,b,c){var d=yd;if(d){var e=I[a+112+64>>2];e||(e=I[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;I[a+12>>2]=0;Z(a+16,0);Z(a+24,0);Z(a+32,0);C[a+40>>1]=4;C[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)};f.onerror=function(h){C[a+40>>1]=4;C[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Fd={};
function Gd(){if(!Hd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Fd)a[b]=Fd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Hd=c}return Hd}var Hd;function Id(a,b){Id.kc||(Id.kc=ib());for(var c=0;c<b;c++)F[a+c>>0]=Id.kc();return 0}function Jd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Kd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Ld=[31,29,31,30,31,30,31,31,30,31,30,31],Md=[31,28,31,30,31,30,31,31,30,31,30,31];function Nd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Jd(a.getFullYear())?Ld:Md)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Od(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(H){return 0>H?-1:0<H?1:0}var y;0===(y=x(k.getFullYear()-u.getFullYear()))&&0===(y=x(k.getMonth()-u.getMonth()))&&(y=x(k.getDate()-u.getDate()));return y}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Nd(new Date(k.Ya+1900,0,1),k.Kb);var u=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(x,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=E[d+40>>2];d={cd:E[d>>2],bd:E[d+4>>2],Ib:E[d+8>>2],wb:E[d+12>>2],qb:E[d+16>>2],Ya:E[d+20>>2],Jb:E[d+24>>2],Kb:E[d+28>>2],nd:E[d+32>>2],ad:E[d+
36>>2],dd:p?z(p):""};c=z(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return q[k.Jb].substring(0,3)},"%A":function(k){return q[k.Jb]},"%b":function(k){return v[k.qb].substring(0,3)},"%B":function(k){return v[k.qb]},"%C":function(k){return f((k.Ya+1900)/100|0,2)},"%d":function(k){return f(k.wb,2)},"%e":function(k){return e(k.wb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Ib,
2)},"%I":function(k){k=k.Ib;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.wb+Kd(Jd(k.Ya+1900)?Ld:Md,k.qb-1),3)},"%m":function(k){return f(k.qb+1,2)},"%M":function(k){return f(k.bd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Ib&&12>k.Ib?"AM":"PM"},"%S":function(k){return f(k.cd,2)},"%t":function(){return"\t"},"%u":function(k){return k.Jb||7},"%U":function(k){var u=new Date(k.Ya+1900,0,1),x=0===u.getDay()?u:Nd(u,7-u.getDay());k=new Date(k.Ya+1900,k.qb,k.wb);return 0>
h(x,k)?f(Math.ceil((31-x.getDate()+(Kd(Jd(k.getFullYear())?Ld:Md,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.Ya+1901,0,4),x=l(new Date(k.Ya+1900,0,4));u=l(u);var y=Nd(new Date(k.Ya+1900,0,1),k.Kb);return 0>h(y,x)?"53":0>=h(u,y)?"01":f(Math.ceil((x.getFullYear()<k.Ya+1900?k.Kb+32-x.getDate():k.Kb+1-x.getDate())/7),2)},"%w":function(k){return k.Jb},"%W":function(k){var u=new Date(k.Ya,0,1),x=1===u.getDay()?u:Nd(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.Ya+1900,k.qb,k.wb);return 0>h(x,k)?f(Math.ceil((31-x.getDate()+(Kd(Jd(k.getFullYear())?Ld:Md,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%y":function(k){return(k.Ya+1900).toString().substring(2)},"%Y":function(k){return k.Ya+1900},"%z":function(k){k=k.ad;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.dd},"%%":function(){return"%"}};for(n in p)c.includes(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));n=ob(c,
!1);if(n.length>b)return 0;F.set(n,a);return n.length-1}function Fb(a,b,c,d){a||(a=this);this.parent=a;this.hb=a.hb;this.sb=null;this.id=yb++;this.name=b;this.mode=c;this.Oa={};this.Pa={};this.ub=d}
Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Jc:{get:function(){return Q(this.mode)}},Ic:{get:function(){return 8192===(this.mode&61440)}}});Xb();zb=Array(4096);Lb(P,"/");Nb("/tmp");Nb("/home");Nb("/home/web_user");
(function(){Nb("/dev");mb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Ob("/dev/null",259);lb(1280,pb);lb(1536,qb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=ib();cc("/dev","random",a);cc("/dev","urandom",a);Nb("/dev/shm");Nb("/dev/shm/tmp")})();
(function(){Nb("/proc");var a=Nb("/proc/self");Nb("/proc/self/fd");Lb({hb:function(){var b=sb(a,"fd",16895,73);b.Oa={rb:function(c,d){var e=xb[+d];if(!e)throw new O(8);c={parent:null,hb:{ic:"fake"},Oa:{vb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var gc;g.FS_createPath=$b;g.FS_createDataFile=bc;g.FS_createPreloadedFile=fc;g.FS_createLazyFile=ec;g.FS_createDevice=cc;g.FS_unlink=Qb;vc=g.InternalError=uc("InternalError");
for(var Pd=Array(256),Qd=0;256>Qd;++Qd)Pd[Qd]=String.fromCharCode(Qd);Ac=Pd;Bc=g.BindingError=uc("BindingError");Kc.prototype.isAliasOf=function(a){if(!(this instanceof Kc&&a instanceof Kc))return!1;var b=this.Ma.Ua.Qa,c=this.Ma.Ra,d=a.Ma.Ua.Qa;for(a=a.Ma.Ra;b.bb;)c=b.xb(c),b=b.bb;for(;d.bb;)a=d.xb(a),d=d.bb;return b===d&&c===a};
Kc.prototype.clone=function(){this.Ma.Ra||Cc(this);if(this.Ma.tb)return this.Ma.count.value+=1,this;var a=Gc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.Ma;a=a(c.call(b,d,{Ma:{value:{count:e.count,mb:e.mb,tb:e.tb,Ra:e.Ra,Ua:e.Ua,$a:e.$a,ab:e.ab}}}));a.Ma.count.value+=1;a.Ma.mb=!1;return a};Kc.prototype["delete"]=function(){this.Ma.Ra||Cc(this);this.Ma.mb&&!this.Ma.tb&&T("Object already scheduled for deletion");Ec(this);Fc(this.Ma);this.Ma.tb||(this.Ma.$a=void 0,this.Ma.Ra=void 0)};
Kc.prototype.isDeleted=function(){return!this.Ma.Ra};Kc.prototype.deleteLater=function(){this.Ma.Ra||Cc(this);this.Ma.mb&&!this.Ma.tb&&T("Object already scheduled for deletion");Ic.push(this);1===Ic.length&&Hc&&Hc(Jc);this.Ma.mb=!0;return this};Yc.prototype.Cc=function(a){this.lc&&(a=this.lc(a));return a};Yc.prototype.bc=function(a){this.ib&&this.ib(a)};Yc.prototype.argPackAdvance=8;Yc.prototype.readValueFromPointer=oc;Yc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Yc.prototype.fromWireType=function(a){function b(){return this.Db?Xc(this.Qa.nb,{Ua:this.Qc,Ra:c,ab:this,$a:a}):Xc(this.Qa.nb,{Ua:this,Ra:a})}var c=this.Cc(a);if(!c)return this.bc(a),null;var d=Wc(this.Qa,c);if(void 0!==d){if(0===d.Ma.count.value)return d.Ma.Ra=c,d.Ma.$a=a,d.clone();d=d.clone();this.bc(a);return d}d=this.Qa.Bc(c);d=Lc[d];if(!d)return b.call(this);d=this.Cb?d.wc:d.pointerType;var e=Uc(c,this.Qa,d.Qa);return null===e?b.call(this):this.Db?Xc(d.Qa.nb,{Ua:d,Ra:e,ab:this,$a:a}):Xc(d.Qa.nb,
{Ua:d,Ra:e})};g.getInheritedInstanceCount=function(){return Object.keys(Vc).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Vc)Vc.hasOwnProperty(b)&&a.push(Vc[b]);return a};g.flushPendingDeletes=Jc;g.setDelayFunction=function(a){Hc=a;Ic.length&&Hc&&Hc(Jc)};ad=g.UnboundTypeError=uc("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){yd=a;Ra("library_fetch_init")},function(){yd=!1;Ra("library_fetch_init")});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Qa("library_fetch_init");
function ob(a,b){var c=Array(ua(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var Xd={W:function(a,b){ab();a=new Date(1E3*E[a>>2]);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;E[b+32>>2]=a;a=E[eb()+(a?
4:0)>>2];E[b+40>>2]=a;return b},D:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 0:var e=kc();return 0>e?-28:Sb(d.path,d.flags,0,e).eb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=kc(),d.flags|=e,0;case 12:return e=kc(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Va}},Z:function(a,b){try{var c=lc(a);return ic(c.path,b)}catch(d){return"undefined"!==typeof R&&d instanceof
O||t(d),-d.Va}},X:function(a,b,c){jc=c;try{var d=lc(a);switch(b){case 21509:case 21505:return d.Ta?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.Ta?0:-59;case 21519:if(!d.Ta)return-59;var e=kc();return E[e>>2]=0;case 21520:return d.Ta?-28:-59;case 21531:a=e=kc();if(!d.Pa.Hc)throw new O(59);return d.Pa.Hc(d,b,a);case 21523:return d.Ta?0:-59;case 21524:return d.Ta?0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),
-f.Va}},aa:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%65536)var l=-28;else{if(0!==(d&32)){var m=Rd(65536,b);if(!m){l=-48;break a}Sd(m,0,b);h=!0}else{var p=xb[e];if(!p){l=-8;break a}var n=f;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new O(2);if(1===(p.flags&2097155))throw new O(2);if(!p.Pa.Fb)throw new O(43);var q=p.Pa.Fb(p,a,b,n,c,d);m=q.Ra;h=q.Mb}hc[m]={Mc:m,Lc:b,Mb:h,eb:e,Rc:c,flags:d,offset:f};l=m}}return l}catch(v){return"undefined"!==typeof R&&v instanceof O||
t(v),-v.Va}},$:function(){return 0},_:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=hc[a];if(d&&b===d.Lc){var e=xb[d.eb];e&&d.Rc&2&&e&&e.Pa.Gb&&e.Pa.Gb(e,A.slice(a,a+b),d.offset,b,d.flags);hc[a]=null;d.Mb&&W(d.Mc)}c=0}return c}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Va}},E:function(a,b,c){jc=c;try{var d=z(a),e=c?kc():0;return Sb(d,b,e).eb}catch(f){return"undefined"!==typeof R&&f instanceof O||t(f),-f.Va}},Y:function(a,b){try{return a=z(a),ic(a,b)}catch(c){return"undefined"!==
typeof R&&c instanceof O||t(c),-c.Va}},d:function(a){var b=mc[a];delete mc[a];var c=b.Ub,d=b.ib,e=b.dc,f=e.map(function(h){return h.Ec}).concat(e.map(function(h){return h.Yc}));xc([a],f,function(h){var l={};e.forEach(function(m,p){var n=h[p],q=m.Bb,v=m.Dc,k=h[p+e.length],u=m.Xc,x=m.Zc;l[m.Ac]={read:function(y){return n.fromWireType(q(v,y))},write:function(y,H){var G=[];u(x,y,k.toWireType(G,H));nc(G)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in l)p[n]=l[n].read(m);d(m);return p},
toWireType:function(m,p){for(var n in l)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in l)l[n].write(q,p[n]);null!==m&&m.push(d,q);return q},argPackAdvance:8,readValueFromPointer:oc,cb:d}]})},N:function(){},ca:function(a,b,c,d,e){var f=zc(c);b=S(b);yc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=F;else if(2===c)l=xa;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(l[h>>f])},cb:null})},v:function(a,b,c,d,e,f,h,l,m,p,n,q,v){n=S(n);f=V(e,f);l&&(l=V(h,l));p&&(p=V(m,p));v=V(q,v);var k=sc(n);Nc(k,function(){dd("Cannot construct "+n+" due to unbound types",[d])});xc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.Qa;var y=x.nb}else y=Kc.prototype;u=tc(k,function(){if(Object.getPrototypeOf(this)!==H)throw new Bc("Use 'new' to construct "+n);if(void 0===G.jb)throw new Bc(n+" has no accessible constructor");var w=G.jb[arguments.length];
if(void 0===w)throw new Bc("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.jb).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(y,{constructor:{value:u}});u.prototype=H;var G=new Oc(n,u,H,v,x,f,l,p);x=new Yc(n,G,!0,!1);y=new Yc(n+"*",G,!1,!1);var ha=new Yc(n+" const*",G,!1,!0);Lc[a]={pointerType:y,wc:ha};Zc(k,u);return[x,y,ha]})},J:function(a,b,c,d,e,f){0<b||t("Assertion failed: undefined");
var h=ed(b,c);e=V(d,e);var l=[f],m=[];xc([],[a],function(p){p=p[0];var n="constructor "+p.name;void 0===p.Qa.jb&&(p.Qa.jb=[]);if(void 0!==p.Qa.jb[b-1])throw new Bc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+p.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");p.Qa.jb[b-1]=function(){dd("Cannot construct "+p.name+" due to unbound types",h)};xc([],h,function(q){p.Qa.jb[b-1]=function(){arguments.length!==
b-1&&T(n+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var v=1;v<b;++v)l[v]=q[v].toWireType(m,arguments[v-1]);v=e.apply(null,l);nc(m);return q[0].fromWireType(v)};return[]});return[]})},k:function(a,b,c,d,e,f,h,l){var m=ed(c,d);b=S(b);f=V(e,f);xc([],[a],function(p){function n(){dd("Cannot call "+q+" due to unbound types",m)}p=p[0];var q=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.Qa.Sc.push(b);var v=p.Qa.nb,k=v[b];void 0===k||void 0===
k.Xa&&k.className!==p.name&&k.yb===c-2?(n.yb=c-2,n.className=p.name,v[b]=n):(Mc(v,b,q),v[b].Xa[c-2]=n);xc([],m,function(u){u=gd(q,u,p,f,h);void 0===v[b].Xa?(u.yb=c-2,v[b]=u):v[b].Xa[c-2]=u;return[]});return[]})},ba:function(a,b){b=S(b);yc(a,{name:b,fromWireType:function(c){var d=X[c].value;jd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:oc,cb:null})},F:function(a,b,c){c=zc(c);b=S(b);yc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==
typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Rc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:kd(b,c),cb:null})},u:function(a,b,c,d,e,f){var h=ed(b,c);a=S(a);e=V(d,e);Nc(a,function(){dd("Cannot call "+a+" due to unbound types",h)},b-1);xc([],h,function(l){Zc(a,gd(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},g:function(a,b,c,d,e){function f(p){return p}b=S(b);-1===e&&(e=4294967295);var h=zc(c);if(0===d){var l=32-8*c;f=function(p){return p<<
l>>>l}}var m=b.includes("unsigned");yc(a,{name:b,fromWireType:f,toWireType:function(p,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Rc(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Rc(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:ld(b,h,0!==d),cb:null})},f:function(a,b,c){function d(f){f>>=2;var h=I;return new e(Fa,
h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);yc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Gc:!0})},G:function(a,b){b=S(b);var c="std::string"===b;yc(a,{name:b,fromWireType:function(d){var e=I[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[d+
4+h]);m=m.join("")}W(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=(c&&f?function(){return ua(e)}:function(){return e.length})(),l=Ea(4+h+1);I[l>>2]=h;if(c&&f)B(e,A,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(W(l),T("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+
f]=m}else for(f=0;f<h;++f)A[l+4+f]=e[f];null!==d&&d.push(W,l);return l},argPackAdvance:8,readValueFromPointer:oc,cb:function(d){W(d)}})},r:function(a,b,c){c=S(c);if(2===b){var d=wa;var e=ya;var f=za;var h=function(){return C};var l=1}else 4===b&&(d=Aa,e=Ba,f=Ca,h=function(){return I},l=2);yc(a,{name:c,fromWireType:function(m){for(var p=I[m>>2],n=h(),q,v=m+4,k=0;k<=p;++k){var u=m+4+k*b;if(k==p||0==n[u>>l])v=d(v,u-v),void 0===q?q=v:(q+=String.fromCharCode(0),q+=v),v=u+b}W(m);return q},toWireType:function(m,
p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var n=f(p),q=Ea(4+n+b);I[q>>2]=n>>l;e(p,q+4,n+b);null!==m&&m.push(W,q);return q},argPackAdvance:8,readValueFromPointer:oc,cb:function(m){W(m)}})},e:function(a,b,c,d,e,f){mc[a]={name:S(b),Ub:V(c,d),ib:V(e,f),dc:[]}},a:function(a,b,c,d,e,f,h,l,m,p){mc[a].dc.push({Ac:S(b),Ec:c,Bb:V(d,e),Dc:f,Yc:h,Xc:V(l,m),Zc:p})},da:function(a,b){b=S(b);yc(a,{Kc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ea:function(a){delete xd[a-
1]},h:function(a,b,c){a=Y(a);b=md(b,"emval::as");var d=[],e=U(d);E[c>>2]=e;return b.toWireType(d,a)},ma:function(a,b,c,d){a=Y(a);c=nd(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return U(a)},n:function(a,b,c,d){a=qd[a];b=Y(b);c=pd(c);a(b,c,null,d)},z:jd,na:function(a,b){a=Y(a);b=Y(b);return a==b},la:function(a){if(0===a)return U(rd());a=pd(a);return U(rd()[a])},m:function(a,b){b=nd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+
"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+sc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Kc||(d+="    return retType.toWireType(destructors, rv);\n");
e.push(d+"};\n");a=fd(e).apply(null,f);return sd(a)},ja:function(a){a=pd(a);return U(g[a])},i:function(a,b){a=Y(a);b=Y(b);return U(a[b])},K:function(a){4<a&&(X[a].Wb+=1)},t:function(a,b,c,d){a=Y(a);var e=td[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+
f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(md,g,U);td[b]=e}return e(a,c,d)},ia:function(){return U([])},L:function(a){return U(pd(a))},ka:function(){return U({})},pa:function(a){nc(X[a].value);jd(a)},p:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},l:function(a,b){a=md(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},oa:function(a){a=Y(a);return U(typeof a)},
j:function(){t()},A:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ud();else return-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0},o:function(a,b,c){vd.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,vd.push(d?Ha[c++>>1]:E[c]),++c;return Za[a].apply(null,vd)},ga:wd,y:function(a,b){Td(a,b||1);throw"longjmp";},P:function(a,b,c){A.copyWithin(a,b,b+c)},Q:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=
Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{qa.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ia();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},fa:function(a,b,c,d,e){function f(D){zd(D,h,p,n,m)}function h(D,Yd){Cd(D,Yd.response,function(Ua){Ad(function(){u?L.get(u)(Ua):b&&b(Ua)},K)},function(Ua){Ad(function(){u?L.get(u)(Ua):b&&b(Ua)},K)})}function l(D){zd(D,q,p,n,m)}function m(D){Ad(function(){H?L.get(H)(D):e&&e(D)},K)}function p(D){Ad(function(){x?L.get(x)(D):c&&c(D)},
K)}function n(D){Ad(function(){y?L.get(y)(D):d&&d(D)},K)}function q(D){Ad(function(){u?L.get(u)(D):b&&b(D)},K)}var v=a+112,k=z(v),u=I[v+36>>2],x=I[v+40>>2],y=I[v+44>>2],H=I[v+48>>2],G=I[v+52>>2],ha=!!(G&4),w=!!(G&32),J=!!(G&16),K=!!(G&64);if("EM_IDB_STORE"===k)k=I[v+84>>2],Cd(a,A.slice(k,k+I[v+88>>2]),q,p);else if("EM_IDB_DELETE"===k)Ed(a,q,p);else if(J){if(w)return 0;zd(a,ha?h:q,p,n,m)}else Dd(a,q,w?p:ha?f:l);return a},U:function(a,b){try{var c=0;Gd().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=
f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof R&&d instanceof O||t(d),d.Va}},V:function(a,b){try{var c=Gd();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0}catch(e){return"undefined"!==typeof R&&e instanceof O||t(e),e.Va}},s:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ra=!0}fa(a,new Bd(a))},q:function(a){try{var b=lc(a);Ub(b);return 0}catch(c){return"undefined"!==typeof R&&c instanceof
O||t(c),c.Va}},T:function(a,b){try{var c=lc(a);F[b>>0]=c.Ta?2:Q(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof R&&d instanceof O||t(d),d.Va}},C:function(a,b,c,d){try{a:{for(var e=lc(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],l=e,m=E[b+8*f>>2],p=h,n=void 0,q=F;if(0>p||0>n)throw new O(28);if(null===l.eb)throw new O(8);if(1===(l.flags&2097155))throw new O(8);if(Q(l.node.mode))throw new O(31);if(!l.Pa.read)throw new O(28);var v="undefined"!==typeof n;if(!v)n=l.position;
else if(!l.seekable)throw new O(70);var k=l.Pa.read(l,q,m,p,n);v||(l.position+=k);var u=k;if(0>u){var x=-1;break a}a+=u;if(u<h)break}x=a}E[d>>2]=x;return 0}catch(y){return"undefined"!==typeof R&&y instanceof O||t(y),y.Va}},M:function(a,b,c,d,e){try{var f=lc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Vb(f,a,d);Ya=[f.position>>>0,(M=f.position,1<=+Math.abs(M)?0<M?(Math.min(+Math.floor(M/4294967296),4294967295)|0)>>>0:~~+Math.ceil((M-+(~~M>>>0))/4294967296)>>>0:
0)];E[e>>2]=Ya[0];E[e+4>>2]=Ya[1];f.Pb&&0===a&&0===d&&(f.Pb=null);return 0}catch(h){return"undefined"!==typeof R&&h instanceof O||t(h),h.Va}},B:function(a,b,c,d){try{a:{for(var e=lc(a),f=a=0;f<c;f++){var h=Wb(e,F,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}E[d>>2]=l;return 0}catch(m){return"undefined"!==typeof R&&m instanceof O||t(m),m.Va}},c:function(){return oa},qa:function(){var a=self.navigator.userAgent,b=ua(a)+1,c=Ea(b);B(a,A,c,b);return c},R:Id,O:Ud,x:Vd,w:Wd,ha:function(a){ab();
var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?E[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=
b.getDate();E[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},b:function(a){oa=a},H:Od,S:function(a,b,c,d){return Od(a,b,c,d)},I:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;qa=g.asm.ra;Ia();L=g.asm.Fa;Ka.unshift(g.asm.sa);Ra("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Xa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:Xd};Qa("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||"function"!==
typeof WebAssembly.instantiateStreaming||Sa()||"function"!==typeof fetch?c(b):fetch(Ta,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.sa).apply(null,arguments)};
var W=g._free=function(){return(W=g._free=g.asm.ta).apply(null,arguments)},Ea=g._malloc=function(){return(Ea=g._malloc=g.asm.ua).apply(null,arguments)},cd=g.___getTypeName=function(){return(cd=g.___getTypeName=g.asm.va).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.wa).apply(null,arguments)};
var Sd=g._memset=function(){return(Sd=g._memset=g.asm.xa).apply(null,arguments)},eb=g.__get_tzname=function(){return(eb=g.__get_tzname=g.asm.ya).apply(null,arguments)},db=g.__get_daylight=function(){return(db=g.__get_daylight=g.asm.za).apply(null,arguments)},cb=g.__get_timezone=function(){return(cb=g.__get_timezone=g.asm.Aa).apply(null,arguments)},Zd=g.stackSave=function(){return(Zd=g.stackSave=g.asm.Ba).apply(null,arguments)},$d=g.stackRestore=function(){return($d=g.stackRestore=g.asm.Ca).apply(null,
arguments)},Td=g._setThrew=function(){return(Td=g._setThrew=g.asm.Da).apply(null,arguments)},Rd=g._memalign=function(){return(Rd=g._memalign=g.asm.Ea).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ga).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.Ha).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ia).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Ja).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Ka).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.La).apply(null,arguments)};function Vd(a,b){var c=Zd();try{L.get(a)(b)}catch(d){$d(c);if(d!==d+0&&"longjmp"!==d)throw d;Td(1,0)}}function Wd(a,b,c){var d=Zd();try{L.get(a)(b,c)}catch(e){$d(d);if(e!==e+0&&"longjmp"!==e)throw e;Td(1,0)}}
function Ud(a,b,c,d){var e=Zd();try{return L.get(a)(b,c,d)}catch(f){$d(e);if(f!==f+0&&"longjmp"!==f)throw f;Td(1,0)}}g.addRunDependency=Qa;g.removeRunDependency=Ra;g.FS_createPath=$b;g.FS_createDataFile=bc;g.FS_createPreloadedFile=fc;g.FS_createLazyFile=ec;g.FS_createDevice=cc;g.FS_unlink=Qb;var ae;function Bd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Pa=function be(){ae||ce();ae||(Pa=be)};
function ce(){function a(){if(!ae&&(ae=!0,g.calledRun=!0,!ra)){g.noFSInit||Yb||(Yb=!0,Xb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?cc("/dev","stdin",g.stdin):Pb("/dev/tty","/dev/stdin"),g.stdout?cc("/dev","stdout",null,g.stdout):Pb("/dev/tty","/dev/stdout"),g.stderr?cc("/dev","stderr",null,g.stderr):Pb("/dev/tty1","/dev/stderr"),Sb("/dev/stdin",0),Sb("/dev/stdout",1),Sb("/dev/stderr",1));$a(Ka);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();La.unshift(b)}$a(La)}}if(!(0<Na)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ma();$a(Ja);0<Na||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ce;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ce();


  return BlinkIDImageCaptureWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDImageCaptureWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDImageCaptureWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDImageCaptureWasmSDK"] = BlinkIDImageCaptureWasmSDK;
