
var BlinkIDImageCaptureWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkIDImageCaptureWasmSDK) {
  BlinkIDImageCaptureWasmSDK = BlinkIDImageCaptureWasmSDK || {};


var g;g||(g=typeof BlinkIDImageCaptureWasmSDK !== 'undefined' ? BlinkIDImageCaptureWasmSDK : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});g.ac||(g.ac=0);g.ac++;
(function(a){function b(m,p,n){var q=new XMLHttpRequest;q.open("GET",m,!0);q.responseType="arraybuffer";q.onprogress=function(v){var k=p;v.total&&(k=v.total);if(v.loaded){q.Ec?g.xb[m].loaded=v.loaded:(q.Ec=!0,g.xb||(g.xb={}),g.xb[m]={loaded:v.loaded,total:k});var u=k=v=0,x;for(x in g.xb){var y=g.xb[x];v+=y.total;k+=y.loaded;u++}v=Math.ceil(v*g.ac/u);g.setStatus&&g.setStatus("Downloading data... ("+k+"/"+v+")")}else!g.xb&&g.setStatus&&g.setStatus("Downloading data...")};q.onerror=function(){throw Error("NetworkError for: "+
m);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)n(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(m){console.error("package error:",m)}function d(){function m(v,k,u){this.start=v;this.end=k;this.audio=u}function p(v){if(!v)throw"Loading data file failed."+Error().stack;if(!(v instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;v=new Uint8Array(v);m.prototype.Ic=v;v=a.files;for(var k=
0;k<v.length;++k)m.prototype.kc[v[k].filename].onload();g.removeRunDependency("datafile_../../resources/basic/BlinkIDImageCaptureWasmSDK.data")}g.FS_createPath("/","microblink",!0,!0);m.prototype={kc:{},open:function(v,k){this.name=k;this.kc[k]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.finish(this.Ic.subarray(this.start,this.end))},finish:function(v){g.FS_createDataFile(this.name,null,v,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.kc[this.name]=null}};
for(var n=a.files,q=0;q<n.length;++q)(new m(n[q].start,n[q].end,n[q].audio)).open("GET",n[q].filename);g.addRunDependency("datafile_../../resources/basic/BlinkIDImageCaptureWasmSDK.data");g.xc||(g.xc={});g.xc["../../resources/basic/BlinkIDImageCaptureWasmSDK.data"]={Ad:!1};l?(p(l),l=null):h=p}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,r("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("BlinkIDImageCaptureWasmSDK.data",""):"BlinkIDImageCaptureWasmSDK.data",f=a.remote_package_size,h=null,l=g.getPreloadedPackage?
g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){h?(h(m),h=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/microblink/BlinkID_MoireClassifier_malaysia_6.0.0.strop",start:0,end:7554,audio:0},{filename:"/microblink/BlinkID_RotationClassifier_general_6.1.0.strop",start:7554,end:35460,audio:0},{filename:"/microblink/BlinkID_MonochromeClassifier_general_6.0.0.strop",start:35460,end:42950,audio:0},{filename:"/microblink/BlinkID_BlurClassifier_general_6.2.0.strop",
start:42950,end:47368,audio:0},{filename:"/microblink/BlinkID_Detector_general_6.6.0.strop",start:47368,end:337496,audio:0},{filename:"/microblink/BlinkID_Ocr_mrz_6.4.0.strop",start:337496,end:708632,audio:0},{filename:"/microblink/BlinkID_Classifier_general_6.13.0.strop",start:708632,end:1147034,audio:0},{filename:"/microblink/BlinkID_Analyzer_general_6.5.0.strop",start:1147034,end:1165084,audio:0}],remote_package_size:1165084,package_uuid:"2ea5fa71-3553-4da5-b1cd-7075fbf6acc6"});
var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in g)g.hasOwnProperty(da)&&(ca[da]=g[da]);var ea="./this.program";function fa(a,b){throw b;}var ha=!1,ia=!1;ha="object"===typeof window;ia="function"===typeof importScripts;var ja="",ka,ma;
if(ha||ia)ia?ja=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ja=document.currentScript.src),_scriptDir&&(ja=_scriptDir),ja=0!==ja.indexOf("blob:")?ja.substr(0,ja.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ia&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var na=g.print||console.log.bind(console),r=g.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(g[da]=ca[da]);ca=null;g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var oa=0,pa;g.wasmBinary&&(pa=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&t("no native wasm support detected");var qa,ra=!1,sa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ta(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&sa)return sa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?ta(A,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=xa[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)xa[b>>1]=a.charCodeAt(e),b+=2;xa[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Da(a){var b=ua(a)+1,c=Ea(b);c&&C(a,F,c,b);return c}var Fa,F,A,xa,D,E,H,Ga,Ha;
function Ia(){var a=qa.buffer;Fa=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=xa=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=D=new Uint16Array(a);g.HEAPU32=H=new Uint32Array(a);g.HEAPF32=Ga=new Float32Array(a);g.HEAPF64=Ha=new Float64Array(a)}var I,Ja=[],Ka=[],La=[],Ma=[];Ka.push({Oc:function(){Na()}});function Oa(){var a=g.preRun.shift();Ja.unshift(a)}var Pa=0,Qa=null,Ra=null;function Sa(){Pa++;g.monitorRunDependencies&&g.monitorRunDependencies(Pa)}
function Ta(){Pa--;g.monitorRunDependencies&&g.monitorRunDependencies(Pa);if(0==Pa&&(null!==Qa&&(clearInterval(Qa),Qa=null),Ra)){var a=Ra;Ra=null;a()}}g.preloadedImages={};g.preloadedAudios={};function t(a){if(g.onAbort)g.onAbort(a);a+="";r(a);ra=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Ua(){var a=Va;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Va="BlinkIDImageCaptureWasmSDK.wasm";if(!Ua()){var Wa=Va;Va=g.locateFile?g.locateFile(Wa,ja):ja+Wa}function Xa(){var a=Va;try{if(a==Va&&pa)return new Uint8Array(pa);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){t(b)}}
function Ya(){return pa||!ha&&!ia||"function"!==typeof fetch?Promise.resolve().then(function(){return Xa()}):fetch(Va,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Va+"'";return a.arrayBuffer()}).catch(function(){return Xa()})}
var K,Za,$a={222345:function(a,b){a=z(a);b=z(b);throw Error(a+b);},222455:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},222671:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},222807:function(a,b){a=z(a);b=z(b);console.log(a+b)},222905:function(a){throw Error(z(a));},222948:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};
function ab(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Oc;"number"===typeof c?void 0===b.$b?I.get(c)():I.get(c)(b.$b):c(void 0===b.$b?null:b.$b)}}}var bb;bb=function(){return performance.now()};function cb(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=bb();else return-1;E[b>>2]=a/1E3|0;E[b+4>>2]=a%1E3*1E6|0;return 0}
function db(a){this.bb=a-16;this.pd=function(b){E[this.bb+8>>2]=b};this.md=function(b){E[this.bb+0>>2]=b};this.nd=function(){E[this.bb+4>>2]=0};this.ld=function(){F[this.bb+12>>0]=0};this.od=function(){F[this.bb+13>>0]=0};this.uc=function(b,c){this.pd(b);this.md(c);this.nd();this.ld();this.od()}}var eb=0;
function fb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(!gb){gb=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);E[hb()>>2]=60*f;E[ib()>>2]=Number(b!=e);c=a(c);d=a(d);c=Da(c);d=Da(d);e<b?(E[jb()>>2]=c,E[jb()+4>>2]=d):(E[jb()>>2]=d,E[jb()+4>>2]=c)}}var gb;
function kb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function lb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=kb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function mb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function nb(a){if("/"===a)return"/";a=lb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function ob(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){t("randomDevice")}}
function pb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=kb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var qb=[];function rb(a,b){qb[a]={input:[],ib:[],Cb:b};sb(a,tb)}
var tb={open:function(a){var b=qb[a.node.Gb];if(!b)throw new L(43);a.fb=b;a.seekable=!1},close:function(a){a.fb.Cb.flush(a.fb)},flush:function(a){a.fb.Cb.flush(a.fb)},read:function(a,b,c,d){if(!a.fb||!a.fb.Cb.tc)throw new L(60);for(var e=0,f=0;f<d;f++){try{var h=a.fb.Cb.tc(a.fb)}catch(l){throw new L(29);}if(void 0===h&&0===e)throw new L(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.fb||!a.fb.Cb.fc)throw new L(60);try{for(var e=
0;e<d;e++)a.fb.Cb.fc(a.fb,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},vb={tc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ub(b,!0)}return a.input.shift()},fc:function(a,b){null===b||10===b?(na(ta(a.ib,0)),a.ib=[]):0!=b&&a.ib.push(b)},flush:function(a){a.ib&&0<a.ib.length&&
(na(ta(a.ib,0)),a.ib=[])}},wb={fc:function(a,b){null===b||10===b?(r(ta(a.ib,0)),a.ib=[]):0!=b&&a.ib.push(b)},flush:function(a){a.ib&&0<a.ib.length&&(r(ta(a.ib,0)),a.ib=[])}},M={sb:null,tb:function(){return M.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.sb||(M.sb={dir:{node:{rb:M.Za.rb,lb:M.Za.lb,Eb:M.Za.Eb,Qb:M.Za.Qb,Bc:M.Za.Bc,Yb:M.Za.Yb,Tb:M.Za.Tb,Ac:M.Za.Ac,Ub:M.Za.Ub},stream:{wb:M.ab.wb}},file:{node:{rb:M.Za.rb,lb:M.Za.lb},
stream:{wb:M.ab.wb,read:M.ab.read,write:M.ab.write,lc:M.ab.lc,Rb:M.ab.Rb,Sb:M.ab.Sb}},link:{node:{rb:M.Za.rb,lb:M.Za.lb,Hb:M.Za.Hb},stream:{}},nc:{node:{rb:M.Za.rb,lb:M.Za.lb},stream:xb}});c=yb(a,b,c,d);N(c.mode)?(c.Za=M.sb.dir.node,c.ab=M.sb.dir.stream,c.$a={}):32768===(c.mode&61440)?(c.Za=M.sb.file.node,c.ab=M.sb.file.stream,c.eb=0,c.$a=null):40960===(c.mode&61440)?(c.Za=M.sb.link.node,c.ab=M.sb.link.stream):8192===(c.mode&61440)&&(c.Za=M.sb.nc.node,c.ab=M.sb.nc.stream);c.timestamp=Date.now();a&&
(a.$a[b]=c,a.timestamp=c.timestamp);return c},Bd:function(a){return a.$a?a.$a.subarray?a.$a.subarray(0,a.eb):new Uint8Array(a.$a):new Uint8Array(0)},qc:function(a,b){var c=a.$a?a.$a.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.$a,a.$a=new Uint8Array(b),0<a.eb&&a.$a.set(c.subarray(0,a.eb),0))},hd:function(a,b){if(a.eb!=b)if(0==b)a.$a=null,a.eb=0;else{var c=a.$a;a.$a=new Uint8Array(b);c&&a.$a.set(c.subarray(0,Math.min(b,a.eb)));a.eb=b}},Za:{rb:function(a){var b=
{};b.Lc=8192===(a.mode&61440)?a.id:1;b.cc=a.id;b.mode=a.mode;b.cd=1;b.uid=0;b.Tc=0;b.Gb=a.Gb;b.size=N(a.mode)?4096:32768===(a.mode&61440)?a.eb:40960===(a.mode&61440)?a.link.length:0;b.Fc=new Date(a.timestamp);b.bd=new Date(a.timestamp);b.Kc=new Date(a.timestamp);b.Gc=4096;b.Hc=Math.ceil(b.size/b.Gc);return b},lb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.hd(a,b.size)},Eb:function(){throw zb[44];},Qb:function(a,b,c,d){return M.createNode(a,
b,c,d)},Bc:function(a,b,c){if(N(a.mode)){try{var d=Ab(b,c)}catch(f){}if(d)for(var e in d.$a)throw new L(55);}delete a.parent.$a[a.name];a.parent.timestamp=Date.now();a.name=c;b.$a[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Yb:function(a,b){delete a.$a[b];a.timestamp=Date.now()},Tb:function(a,b){var c=Ab(a,b),d;for(d in c.$a)throw new L(55);delete a.$a[b];a.timestamp=Date.now()},Ac:function(a){var b=[".",".."],c;for(c in a.$a)a.$a.hasOwnProperty(c)&&b.push(c);return b},Ub:function(a,b,c){a=M.createNode(a,
b,41471,0);a.link=c;return a},Hb:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ab:{read:function(a,b,c,d,e){var f=a.node.$a;if(e>=a.node.eb)return 0;a=Math.min(a.node.eb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===F.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.$a||a.$a.subarray)){if(f)return a.$a=b.subarray(c,c+d),a.eb=d;if(0===a.eb&&0===e)return a.$a=
b.slice(c,c+d),a.eb=d;if(e+d<=a.eb)return a.$a.set(b.subarray(c,c+d),e),d}M.qc(a,e+d);if(a.$a.subarray&&b.subarray)a.$a.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.$a[e+f]=b[c+f];a.eb=Math.max(a.eb,e+d);return d},wb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.eb);if(0>b)throw new L(28);return b},lc:function(a,b,c){M.qc(a.node,b+c);a.node.eb=Math.max(a.node.eb,b+c)},Rb:function(a,b,c,d,e,f){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);
a=a.node.$a;if(f&2||a.buffer!==Fa){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ea(f);c<f;)F[b+c++]=0;c=b;if(!c)throw new L(48);F.set(a,c)}else d=!1,c=a.byteOffset;return{bb:c,Zb:d}},Sb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ab.write(a,b,0,d,c,!1);return 0}}},Bb=null,Cb={},Db=[],Eb=1,Fb=null,Gb=!0,O={},L=null,zb={};
function Hb(a,b){a=pb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={sc:!0,ic:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ic)throw new L(32);a=kb(a.split("/").filter(function(h){return!!h}),!1);var e=Bb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Ab(e,a[d]);c=lb(c+"/"+a[d]);e.Ab&&(!f||f&&b.sc)&&(e=e.Ab.root);if(!f||b.Mb)for(f=0;40960===(e.mode&61440);)if(e=Ib(c),c=pb(mb(c),e),e=Hb(c,{ic:b.ic}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function Jb(a){for(var b;;){if(a===a.parent)return a=a.tb.wc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Kb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Fb.length}function Lb(a){var b=Kb(a.parent.id,a.name);if(Fb[b]===a)Fb[b]=a.Bb;else for(b=Fb[b];b;){if(b.Bb===a){b.Bb=a.Bb;break}b=b.Bb}}
function Ab(a,b){var c;if(c=(c=Mb(a,"x"))?c:a.Za.Eb?0:2)throw new L(c,a);for(c=Fb[Kb(a.id,b)];c;c=c.Bb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Za.Eb(a,b)}function yb(a,b,c,d){a=new Nb(a,b,c,d);b=Kb(a.parent.id,a.name);a.Bb=Fb[b];return Fb[b]=a}function N(a){return 16384===(a&61440)}var Ob={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Pb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Mb(a,b){if(Gb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Qb(a,b){try{return Ab(a,b),20}catch(c){}return Mb(a,"wx")}function Rb(a,b,c){try{var d=Ab(a,b)}catch(e){return e.hb}if(a=Mb(a,"wx"))return a;if(c){if(!N(d.mode))return 54;if(d===d.parent||"/"===Jb(d))return 10}else if(N(d.mode))return 31;return 0}
function Sb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Db[a])return a;throw new L(33);}function Tb(a,b){Ub||(Ub=function(){},Ub.prototype={object:{get:function(){return this.node},set:function(e){this.node=e}}});var c=new Ub,d;for(d in a)c[d]=a[d];a=c;b=Sb(b);a.qb=b;return Db[b]=a}var xb={open:function(a){a.ab=Cb[a.node.Gb].ab;a.ab.open&&a.ab.open(a)},wb:function(){throw new L(70);}};function sb(a,b){Cb[a]={ab:b}}
function Vb(a,b){var c="/"===b,d=!b;if(c&&Bb)throw new L(10);if(!c&&!d){var e=Hb(b,{sc:!1});b=e.path;e=e.node;if(e.Ab)throw new L(10);if(!N(e.mode))throw new L(54);}b={type:a,Dd:{},wc:b,ad:[]};a=a.tb(b);a.tb=b;b.root=a;c?Bb=a:e&&(e.Ab=b,e.tb&&e.tb.ad.push(b))}function Wb(a,b,c){var d=Hb(a,{parent:!0}).node;a=nb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Qb(d,a);if(e)throw new L(e);if(!d.Za.Qb)throw new L(63);return d.Za.Qb(d,a,b,c)}function Xb(a){return Wb(a,16895,0)}
function Yb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Wb(a,b|8192,c)}function Zb(a,b){if(!pb(a))throw new L(44);var c=Hb(b,{parent:!0}).node;if(!c)throw new L(44);b=nb(b);var d=Qb(c,b);if(d)throw new L(d);if(!c.Za.Ub)throw new L(63);c.Za.Ub(c,b,a)}
function $b(a){var b=Hb(a,{parent:!0}).node,c=nb(a),d=Ab(b,c),e=Rb(b,c,!1);if(e)throw new L(e);if(!b.Za.Yb)throw new L(63);if(d.Ab)throw new L(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(f){r("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Za.Yb(b,c);Lb(d);try{if(O.onDeletePath)O.onDeletePath(a)}catch(f){r("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Ib(a){a=Hb(a).node;if(!a)throw new L(44);if(!a.Za.Hb)throw new L(28);return pb(Jb(a.parent),a.Za.Hb(a))}function ac(a,b){a="string"===typeof a?Hb(a,{Mb:!0}).node:a;if(!a.Za.lb)throw new L(63);a.Za.lb(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function bc(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var e=Ob[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=lb(a);try{f=Hb(a,{Mb:!(b&131072)}).node}catch(h){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=Wb(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!N(f.mode))throw new L(54);if(!e&&(c=f?40960===(f.mode&61440)?32:N(f.mode)&&
("r"!==Pb(b)||b&512)?31:Mb(f,Pb(b)):44))throw new L(c);if(b&512){c=f;c="string"===typeof c?Hb(c,{Mb:!0}).node:c;if(!c.Za.lb)throw new L(63);if(N(c.mode))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(e=Mb(c,"w"))throw new L(e);c.Za.lb(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Tb({node:f,path:Jb(f),flags:b,seekable:!0,position:0,ab:f.ab,yd:[],error:!1},d);d.ab.open&&d.ab.open(d);!g.logReadFiles||b&1||(cc||(cc={}),a in cc||(cc[a]=1,r("FS.trackingDelegate error on read file: "+a)));
try{O.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),O.onOpenFile(a,f))}catch(h){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+h.message)}return d}function dc(a){if(null===a.qb)throw new L(8);a.bc&&(a.bc=null);try{a.ab.close&&a.ab.close(a)}catch(b){throw b;}finally{Db[a.qb]=null}a.qb=null}function ec(a,b,c){if(null===a.qb)throw new L(8);if(!a.seekable||!a.ab.wb)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ab.wb(a,b,c);a.yd=[]}
function fc(a,b,c,d,e,f){if(0>d||0>e)throw new L(28);if(null===a.qb)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(N(a.node.mode))throw new L(31);if(!a.ab.write)throw new L(28);a.seekable&&a.flags&1024&&ec(a,0,2);var h="undefined"!==typeof e;if(!h)e=a.position;else if(!a.seekable)throw new L(70);b=a.ab.write(a,b,c,d,e,f);h||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(l){r("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function gc(){L||(L=function(a,b){this.node=b;this.kd=function(c){this.hb=c};this.kd(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){zb[a]=new L(a);zb[a].stack="<generic error, no stack>"}))}var hc;function ic(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function jc(a,b){a="string"===typeof a?a:Jb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=lb(a+"/"+c);try{Xb(d)}catch(e){}a=d}}return d}
function kc(a,b,c,d){a=lb(("string"===typeof a?a:Jb(a))+"/"+b);c=ic(c,d);return Wb(a,(void 0!==c?c:438)&4095|32768,0)}function lc(a,b,c,d,e,f){a=b?lb(("string"===typeof a?a:Jb(a))+"/"+b):a;d=ic(d,e);e=Wb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}ac(e,d|146);a=bc(e,577);fc(a,c,0,c.length,0,f);dc(a);ac(e,d)}return e}
function mc(a,b,c,d){a=lb(("string"===typeof a?a:Jb(a))+"/"+b);b=ic(!!c,!!d);mc.vc||(mc.vc=64);var e=mc.vc++<<8|0;sb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,h,l,m){for(var p=0,n=0;n<m;n++){try{var q=c()}catch(v){throw new L(29);}if(void 0===q&&0===p)throw new L(6);if(null===q||void 0===q)break;p++;h[l+n]=q}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{d(h[l+p])}catch(n){throw new L(29);}m&&
(f.node.timestamp=Date.now());return p}});return Yb(a,b,e)}function nc(a){if(!(a.Wc||a.Xc||a.link||a.$a)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.$a=ub(ka(a.url),!0),a.eb=a.$a.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function oc(a,b,c,d,e){function f(){this.ec=!1;this.Lb=[]}f.prototype.get=function(n){if(!(n>this.length-1||0>n)){var q=n%this.oc;return this.Nb(n/this.oc|0)[q]}};f.prototype.jd=function(n){this.Nb=n};f.prototype.mc=function(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);if(!(200<=n.status&&300>n.status||304===n.status))throw Error("Couldn't load "+c+". Status: "+n.status);var q=Number(n.getResponseHeader("Content-length")),v,k=(v=n.getResponseHeader("Accept-Ranges"))&&"bytes"===v;n=
(v=n.getResponseHeader("Content-Encoding"))&&"gzip"===v;var u=1048576;k||(u=q);var x=this;x.jd(function(y){var J=y*u,G=(y+1)*u-1;G=Math.min(G,q-1);if("undefined"===typeof x.Lb[y]){var la=x.Lb;if(J>G)throw Error("invalid range ("+J+", "+G+") or no bytes requested!");if(G>q-1)throw Error("only "+q+" bytes available! programmer error!");var w=new XMLHttpRequest;w.open("GET",c,!1);q!==u&&w.setRequestHeader("Range","bytes="+J+"-"+G);"undefined"!=typeof Uint8Array&&(w.responseType="arraybuffer");w.overrideMimeType&&
w.overrideMimeType("text/plain; charset=x-user-defined");w.send(null);if(!(200<=w.status&&300>w.status||304===w.status))throw Error("Couldn't load "+c+". Status: "+w.status);J=void 0!==w.response?new Uint8Array(w.response||[]):ub(w.responseText||"",!0);la[y]=J}if("undefined"===typeof x.Lb[y])throw Error("doXHR failed!");return x.Lb[y]});if(n||!q)u=q=1,u=q=this.Nb(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.Dc=q;this.Cc=u;this.ec=!0};if("undefined"!==
typeof XMLHttpRequest){if(!ia)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new f;Object.defineProperties(h,{length:{get:function(){this.ec||this.mc();return this.Dc}},oc:{get:function(){this.ec||this.mc();return this.Cc}}});var l=void 0}else l=c,h=void 0;var m=kc(a,b,d,e);h?m.$a=h:l&&(m.$a=null,m.url=l);Object.defineProperties(m,{eb:{get:function(){return this.$a.length}}});var p={};Object.keys(m.ab).forEach(function(n){var q=
m.ab[n];p[n]=function(){nc(m);return q.apply(null,arguments)}});p.read=function(n,q,v,k,u){nc(m);n=n.node.$a;if(u>=n.length)return 0;k=Math.min(n.length-u,k);if(n.slice)for(var x=0;x<k;x++)q[v+x]=n[u+x];else for(x=0;x<k;x++)q[v+x]=n.get(u+x);return k};m.ab=p;return m}
function pc(a,b,c,d,e,f,h,l,m,p){function n(k){function u(y){p&&p();l||lc(a,b,y,d,e,m);f&&f();Ta(v)}var x=!1;g.preloadPlugins.forEach(function(y){!x&&y.canHandle(q)&&(y.handle(k,q,u,function(){h&&h();Ta(v)}),x=!0)});x||u(k)}qc.uc();var q=b?pb(lb(a+"/"+b)):a,v="cp "+q;Sa(v);"string"==typeof c?qc.zd(c,function(k){n(k)},h):n(c)}var Q={},Ub,cc,rc={};
function sc(a,b){try{var c=Hb(a,{Mb:!0}).node;if(!c)throw new L(44);if(!c.Za.rb)throw new L(63);var d=c.Za.rb(c)}catch(e){if(e&&e.node&&lb(a)!==lb(Jb(e.node)))return-54;throw e;}E[b>>2]=d.Lc;E[b+4>>2]=0;E[b+8>>2]=d.cc;E[b+12>>2]=d.mode;E[b+16>>2]=d.cd;E[b+20>>2]=d.uid;E[b+24>>2]=d.Tc;E[b+28>>2]=d.Gb;E[b+32>>2]=0;Za=[d.size>>>0,(K=d.size,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];E[b+40>>2]=Za[0];E[b+44>>2]=Za[1];E[b+48>>
2]=4096;E[b+52>>2]=d.Hc;E[b+56>>2]=d.Fc.getTime()/1E3|0;E[b+60>>2]=0;E[b+64>>2]=d.bd.getTime()/1E3|0;E[b+68>>2]=0;E[b+72>>2]=d.Kc.getTime()/1E3|0;E[b+76>>2]=0;Za=[d.cc>>>0,(K=d.cc,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];E[b+80>>2]=Za[0];E[b+84>>2]=Za[1];return 0}var tc=void 0;function uc(){tc+=4;return E[tc-4>>2]}function vc(a){a=Db[a];if(!a)throw new L(8);return a}var wc={};
function xc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function yc(a){return this.fromWireType(H[a>>2])}var zc={},Ac={},Bc={};function Cc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Dc(a,b){a=Cc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ec(a){var b=Error,c=Dc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Fc=void 0;function Gc(a){throw new Fc(a);}
function Hc(a,b,c){function d(l){l=c(l);l.length!==a.length&&Gc("Mismatched type converter count");for(var m=0;m<a.length;++m)Ic(a[m],l[m])}a.forEach(function(l){Bc[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){Ac.hasOwnProperty(l)?e[m]=Ac[l]:(f.push(l),zc.hasOwnProperty(l)||(zc[l]=[]),zc[l].push(function(){e[m]=Ac[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function Jc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Kc=void 0;function R(a){for(var b="";A[a];)b+=Kc[A[a++]];return b}var Lc=void 0;function S(a){throw new Lc(a);}
function Ic(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(Ac.hasOwnProperty(a)){if(c.Uc)return;S("Cannot register type '"+d+"' twice")}Ac[a]=b;delete Bc[a];zc.hasOwnProperty(a)&&(b=zc[a],delete zc[a],b.forEach(function(e){e()}))}function Mc(a){return{count:a.count,yb:a.yb,Fb:a.Fb,bb:a.bb,gb:a.gb,mb:a.mb,nb:a.nb}}
function Nc(a){S(a.Ya.gb.cb.name+" instance already deleted")}var Oc=!1;function Pc(){}function Qc(a){--a.count.value;0===a.count.value&&(a.mb?a.nb.ub(a.mb):a.gb.cb.ub(a.bb))}
function Rc(a){if("undefined"===typeof FinalizationGroup)return Rc=function(b){return b},a;Oc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.bb?Qc(c):console.warn("object already deleted: "+c.bb)});Rc=function(b){Oc.register(b,b.Ya,b.Ya);return b};Pc=function(b){Oc.unregister(b.Ya)};return Rc(a)}var Sc=void 0,Tc=[];function Uc(){for(;Tc.length;){var a=Tc.pop();a.Ya.yb=!1;a["delete"]()}}function Vc(){}var Wc={};
function Xc(a,b,c){if(void 0===a[b].jb){var d=a[b];a[b]=function(){a[b].jb.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].jb+")!");return a[b].jb[arguments.length].apply(this,arguments)};a[b].jb=[];a[b].jb[d.Kb]=d}}
function Yc(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].jb&&void 0!==g[a].jb[c])&&S("Cannot register public name '"+a+"' twice"),Xc(g,a,a),g.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].jb[c]=b):(g[a]=b,void 0!==c&&(g[a].Cd=c))}function Zc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.zb=c;this.ub=d;this.ob=e;this.Pc=f;this.Jb=h;this.Mc=l;this.fd=[]}
function $c(a,b,c){for(;b!==c;)b.Jb||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Jb(a),b=b.ob;return a}function ad(a,b){if(null===b)return this.dc&&S("null is not a valid "+this.name),0;b.Ya||S('Cannot pass "'+bd(b)+'" as a '+this.name);b.Ya.bb||S("Cannot pass deleted object as a pointer of type "+this.name);return $c(b.Ya.bb,b.Ya.gb.cb,this.cb)}
function cd(a,b){if(null===b){this.dc&&S("null is not a valid "+this.name);if(this.Pb){var c=this.hc();null!==a&&a.push(this.ub,c);return c}return 0}b.Ya||S('Cannot pass "'+bd(b)+'" as a '+this.name);b.Ya.bb||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Ob&&b.Ya.gb.Ob&&S("Cannot convert argument of type "+(b.Ya.nb?b.Ya.nb.name:b.Ya.gb.name)+" to parameter type "+this.name);c=$c(b.Ya.bb,b.Ya.gb.cb,this.cb);if(this.Pb)switch(void 0===b.Ya.mb&&S("Passing raw pointer to smart pointer is illegal"),
this.td){case 0:b.Ya.nb===this?c=b.Ya.mb:S("Cannot convert argument of type "+(b.Ya.nb?b.Ya.nb.name:b.Ya.gb.name)+" to parameter type "+this.name);break;case 1:c=b.Ya.mb;break;case 2:if(b.Ya.nb===this)c=b.Ya.mb;else{var d=b.clone();c=this.gd(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ub,c)}break;default:S("Unsupporting sharing policy")}return c}
function dd(a,b){if(null===b)return this.dc&&S("null is not a valid "+this.name),0;b.Ya||S('Cannot pass "'+bd(b)+'" as a '+this.name);b.Ya.bb||S("Cannot pass deleted object as a pointer of type "+this.name);b.Ya.gb.Ob&&S("Cannot convert argument of type "+b.Ya.gb.name+" to parameter type "+this.name);return $c(b.Ya.bb,b.Ya.gb.cb,this.cb)}function ed(a,b,c){if(b===c)return a;if(void 0===c.ob)return null;a=ed(a,b,c.ob);return null===a?null:c.Mc(a)}var fd={};
function gd(a,b){for(void 0===b&&S("ptr should not be undefined");a.ob;)b=a.Jb(b),a=a.ob;return fd[b]}function hd(a,b){b.gb&&b.bb||Gc("makeClassHandle requires ptr and ptrType");!!b.nb!==!!b.mb&&Gc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Rc(Object.create(a,{Ya:{value:b}}))}
function id(a,b,c,d){this.name=a;this.cb=b;this.dc=c;this.Ob=d;this.Pb=!1;this.ub=this.gd=this.hc=this.zc=this.td=this.dd=void 0;void 0!==b.ob?this.toWireType=cd:(this.toWireType=d?ad:dd,this.pb=null)}function jd(a,b,c){g.hasOwnProperty(a)||Gc("Replacing nonexistant public symbol");void 0!==g[a].jb&&void 0!==c?g[a].jb[c]=b:(g[a]=b,g[a].Kb=c)}
function kd(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=I.get(b).apply(null,c);return d}}function ld(a,b){a=R(a);var c=-1!=a.indexOf("j")?kd(a,b):I.get(b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var md=void 0;function nd(a){a=od(a);var b=R(a);pd(a);return b}
function qd(a,b){function c(f){e[f]||Ac[f]||(Bc[f]?Bc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new md(a+": "+d.map(nd).join([", "]));}function rd(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function sd(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Dc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function td(a,b,c,d,e){var f=b.length;2>f&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].pb){l=!0;break}var m="void"!==b[0].name,p="",n="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,n+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Cc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var q=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[S,d,e,xc,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+q+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+q+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(n="thisWired"+(0<n.length?", ":"")+n);a+=(m?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].pb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].pb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return sd(p).apply(null,d)}var ud=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function vd(a){4<a&&0===--V[a].jc&&(V[a]=void 0,ud.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ud.length?ud.pop():V.length;V[b]={jc:1,value:a};return b}}function bd(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function wd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ga[c>>2])};case 3:return function(c){return this.fromWireType(Ha[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function xd(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return A[d]};case 1:return c?function(d){return xa[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function W(a){a||S("Cannot use deleted val. handle = "+a);return V[a].value}function yd(a,b){var c=Ac[a];void 0===c&&S(b+" has unknown type "+nd(a));return c}
function zd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=yd(E[(b>>2)+d],"parameter "+d);return c}var Ad={};function Bd(a){var b=Ad[a];return void 0===b?R(a):b}var Cd=[];function Dd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Ed(a){var b=Cd.length;Cd.push(a);return b}var Fd={};function Gd(){return!ia}g._emscripten_is_main_browser_thread=Gd;var Hd=[];function X(a,b){H[a>>2]=b;H[a+4>>2]=b/4294967296|0}var Id;
function Jd(a,b,c,d,e){function f(B){var T=0,P=0;B&&(P=w.response?w.response.byteLength:0,T=Ea(P),A.set(new Uint8Array(w.response),T));H[a+12>>2]=T;X(a+16,P)}var h=H[a+8>>2];if(h){var l=z(h),m=a+112,p=z(m);p||(p="GET");var n=H[m+52>>2],q=H[m+56>>2],v=!!H[m+60>>2],k=H[m+68>>2],u=H[m+72>>2];h=H[m+76>>2];var x=H[m+80>>2],y=H[m+84>>2];m=H[m+88>>2];var J=!!(n&1),G=!!(n&2);n=!!(n&64);k=k?z(k):void 0;u=u?z(u):void 0;var la=x?z(x):void 0,w=new XMLHttpRequest;w.withCredentials=v;w.open(p,l,!n,k,u);n||(w.timeout=
q);w.Fd=l;w.responseType="arraybuffer";x&&w.overrideMimeType(la);if(h)for(;;){p=H[h>>2];if(!p)break;l=H[h+4>>2];if(!l)break;h+=8;p=z(p);l=z(l);w.setRequestHeader(p,l)}Hd.push(w);H[a+0>>2]=Hd.length;h=y&&m?A.slice(y,y+m):null;w.onload=function(B){f(J&&!G);var T=w.response?w.response.byteLength:0;X(a+24,0);T&&X(a+32,T);D[a+40>>1]=w.readyState;D[a+42>>1]=w.status;w.statusText&&C(w.statusText,A,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,B):c&&c(a,w,B)};w.onerror=function(B){f(J);var T=w.status;X(a+
24,0);X(a+32,w.response?w.response.byteLength:0);D[a+40>>1]=w.readyState;D[a+42>>1]=T;c&&c(a,w,B)};w.ontimeout=function(B){c&&c(a,w,B)};w.onprogress=function(B){var T=J&&G&&w.response?w.response.byteLength:0,P=0;J&&G&&(P=Ea(T),A.set(new Uint8Array(w.response),P));H[a+12>>2]=P;X(a+16,T);X(a+24,B.loaded-T);X(a+32,B.total);D[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<B.loaded&&(w.status=200);D[a+42>>1]=w.status;w.statusText&&C(w.statusText,A,a+44,64);d&&d(a,w,B);P&&pd(P)};w.onreadystatechange=
function(B){D[a+40>>1]=w.readyState;2<=w.readyState&&(D[a+42>>1]=w.status);e&&e(a,w,B)};try{w.send(h)}catch(B){c&&c(a,w,B)}}else c(a,0,"no url specified!")}
function Kd(a,b,c,d){var e=Id;if(e){var f=H[a+112+64>>2];f||(f=H[a+8>>2]);var h=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){D[a+40>>1]=4;D[a+42>>1]=200;C("OK",A,a+44,64);c(a,0,h)};l.onerror=function(m){D[a+40>>1]=4;D[a+42>>1]=413;C("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ld(a,b,c){var d=Id;if(d){var e=H[a+112+64>>2];e||(e=H[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=Ea(l);A.set(new Uint8Array(h),m);H[a+12>>2]=m;X(a+16,l);X(a+24,0);X(a+32,l);D[a+40>>1]=4;D[a+42>>1]=200;C("OK",A,a+44,64);b(a,0,h)}else D[a+40>>1]=4,D[a+42>>1]=404,C("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(h){D[a+40>>1]=4;D[a+42>>1]=404;
C("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Md(a,b,c){var d=Id;if(d){var e=H[a+112+64>>2];e||(e=H[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;H[a+12>>2]=0;X(a+16,0);X(a+24,0);X(a+32,0);D[a+40>>1]=4;D[a+42>>1]=200;C("OK",A,a+44,64);b(a,0,h)};f.onerror=function(h){D[a+40>>1]=4;D[a+42>>1]=404;C("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}var Nd={};
function Od(){if(!Pd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Nd)a[b]=Nd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pd=c}return Pd}var Pd;function Qd(a,b){Qd.yc||(Qd.yc=ob());for(var c=0;c<b;c++)F[a+c>>0]=Qd.yc();return 0}function Rd(a){return 0===a%4&&(0!==a%100||0===a%400)}
function Sd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Td=[31,29,31,30,31,30,31,31,30,31,30,31],Ud=[31,28,31,30,31,30,31,31,30,31,30,31];function Vd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Rd(a.getFullYear())?Td:Ud)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Wd(a,b,c,d){function e(k,u,x){for(k="number"===typeof k?k.toString():k||"";k.length<u;)k=x[0]+k;return k}function f(k,u){return e(k,u,"0")}function h(k,u){function x(J){return 0>J?-1:0<J?1:0}var y;0===(y=x(k.getFullYear()-u.getFullYear()))&&0===(y=x(k.getMonth()-u.getMonth()))&&(y=x(k.getDate()-u.getDate()));return y}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Vd(new Date(k.kb+1900,0,1),k.Xb);var u=new Date(k.getFullYear()+1,0,4),x=l(new Date(k.getFullYear(),0,4));u=l(u);return 0>=h(x,k)?0>=h(u,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=E[d+40>>2];d={wd:E[d>>2],vd:E[d+4>>2],Vb:E[d+8>>2],Ib:E[d+12>>2],Db:E[d+16>>2],kb:E[d+20>>2],Wb:E[d+24>>2],Xb:E[d+28>>2],Ed:E[d+32>>2],ud:E[d+
36>>2],xd:p?z(p):""};c=z(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in p)c=c.replace(new RegExp(n,"g"),p[n]);var q="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
v="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return q[k.Wb].substring(0,3)},"%A":function(k){return q[k.Wb]},"%b":function(k){return v[k.Db].substring(0,3)},"%B":function(k){return v[k.Db]},"%C":function(k){return f((k.kb+1900)/100|0,2)},"%d":function(k){return f(k.Ib,2)},"%e":function(k){return e(k.Ib,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Vb,
2)},"%I":function(k){k=k.Vb;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.Ib+Sd(Rd(k.kb+1900)?Td:Ud,k.Db-1),3)},"%m":function(k){return f(k.Db+1,2)},"%M":function(k){return f(k.vd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Vb&&12>k.Vb?"AM":"PM"},"%S":function(k){return f(k.wd,2)},"%t":function(){return"\t"},"%u":function(k){return k.Wb||7},"%U":function(k){var u=new Date(k.kb+1900,0,1),x=0===u.getDay()?u:Vd(u,7-u.getDay());k=new Date(k.kb+1900,k.Db,k.Ib);return 0>
h(x,k)?f(Math.ceil((31-x.getDate()+(Sd(Rd(k.getFullYear())?Td:Ud,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%V":function(k){var u=new Date(k.kb+1901,0,4),x=l(new Date(k.kb+1900,0,4));u=l(u);var y=Vd(new Date(k.kb+1900,0,1),k.Xb);return 0>h(y,x)?"53":0>=h(u,y)?"01":f(Math.ceil((x.getFullYear()<k.kb+1900?k.Xb+32-x.getDate():k.Xb+1-x.getDate())/7),2)},"%w":function(k){return k.Wb},"%W":function(k){var u=new Date(k.kb,0,1),x=1===u.getDay()?u:Vd(u,0===u.getDay()?1:7-u.getDay()+1);k=
new Date(k.kb+1900,k.Db,k.Ib);return 0>h(x,k)?f(Math.ceil((31-x.getDate()+(Sd(Rd(k.getFullYear())?Td:Ud,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(x,u)?"01":"00"},"%y":function(k){return(k.kb+1900).toString().substring(2)},"%Y":function(k){return k.kb+1900},"%z":function(k){k=k.ud;var u=0<=k;k=Math.abs(k)/60;return(u?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.xd},"%%":function(){return"%"}};for(n in p)0<=c.indexOf(n)&&(c=c.replace(new RegExp(n,"g"),p[n](d)));n=
ub(c,!1);if(n.length>b)return 0;F.set(n,a);return n.length-1}var Xd=[];function Nb(a,b,c,d){a||(a=this);this.parent=a;this.tb=a.tb;this.Ab=null;this.id=Eb++;this.name=b;this.mode=c;this.Za={};this.ab={};this.Gb=d}
Object.defineProperties(Nb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Xc:{get:function(){return N(this.mode)}},Wc:{get:function(){return 8192===(this.mode&61440)}}});gc();Fb=Array(4096);Vb(M,"/");Xb("/tmp");Xb("/home");Xb("/home/web_user");
(function(){Xb("/dev");sb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Yb("/dev/null",259);rb(1280,vb);rb(1536,wb);Yb("/dev/tty",1280);Yb("/dev/tty1",1536);var a=ob();mc("/dev","random",a);mc("/dev","urandom",a);Xb("/dev/shm");Xb("/dev/shm/tmp")})();
(function(){Xb("/proc");var a=Xb("/proc/self");Xb("/proc/self/fd");Vb({tb:function(){var b=yb(a,"fd",16895,73);b.Za={Eb:function(c,d){var e=Db[+d];if(!e)throw new L(8);c={parent:null,tb:{wc:"fake"},Za:{Hb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var qc;g.FS_createPath=jc;g.FS_createDataFile=lc;g.FS_createPreloadedFile=pc;g.FS_createLazyFile=oc;g.FS_createDevice=mc;g.FS_unlink=$b;Fc=g.InternalError=Ec("InternalError");
for(var Yd=Array(256),Zd=0;256>Zd;++Zd)Yd[Zd]=String.fromCharCode(Zd);Kc=Yd;Lc=g.BindingError=Ec("BindingError");Vc.prototype.isAliasOf=function(a){if(!(this instanceof Vc&&a instanceof Vc))return!1;var b=this.Ya.gb.cb,c=this.Ya.bb,d=a.Ya.gb.cb;for(a=a.Ya.bb;b.ob;)c=b.Jb(c),b=b.ob;for(;d.ob;)a=d.Jb(a),d=d.ob;return b===d&&c===a};
Vc.prototype.clone=function(){this.Ya.bb||Nc(this);if(this.Ya.Fb)return this.Ya.count.value+=1,this;var a=Rc(Object.create(Object.getPrototypeOf(this),{Ya:{value:Mc(this.Ya)}}));a.Ya.count.value+=1;a.Ya.yb=!1;return a};Vc.prototype["delete"]=function(){this.Ya.bb||Nc(this);this.Ya.yb&&!this.Ya.Fb&&S("Object already scheduled for deletion");Pc(this);Qc(this.Ya);this.Ya.Fb||(this.Ya.mb=void 0,this.Ya.bb=void 0)};Vc.prototype.isDeleted=function(){return!this.Ya.bb};
Vc.prototype.deleteLater=function(){this.Ya.bb||Nc(this);this.Ya.yb&&!this.Ya.Fb&&S("Object already scheduled for deletion");Tc.push(this);1===Tc.length&&Sc&&Sc(Uc);this.Ya.yb=!0;return this};id.prototype.Qc=function(a){this.zc&&(a=this.zc(a));return a};id.prototype.pc=function(a){this.ub&&this.ub(a)};id.prototype.argPackAdvance=8;id.prototype.readValueFromPointer=yc;id.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
id.prototype.fromWireType=function(a){function b(){return this.Pb?hd(this.cb.zb,{gb:this.dd,bb:c,nb:this,mb:a}):hd(this.cb.zb,{gb:this,bb:a})}var c=this.Qc(a);if(!c)return this.pc(a),null;var d=gd(this.cb,c);if(void 0!==d){if(0===d.Ya.count.value)return d.Ya.bb=c,d.Ya.mb=a,d.clone();d=d.clone();this.pc(a);return d}d=this.cb.Pc(c);d=Wc[d];if(!d)return b.call(this);d=this.Ob?d.Jc:d.pointerType;var e=ed(c,this.cb,d.cb);return null===e?b.call(this):this.Pb?hd(d.cb.zb,{gb:d,bb:e,nb:this,mb:a}):hd(d.cb.zb,
{gb:d,bb:e})};g.getInheritedInstanceCount=function(){return Object.keys(fd).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in fd)fd.hasOwnProperty(b)&&a.push(fd[b]);return a};g.flushPendingDeletes=Uc;g.setDelayFunction=function(a){Sc=a;Tc.length&&Sc&&Sc(Uc)};md=g.UnboundTypeError=Ec("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){Id=a;Ta("library_fetch_init")},function(){Id=!1;Ta("library_fetch_init")});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Sa("library_fetch_init");
function ub(a,b){var c=Array(ua(a)+1);a=C(a,c,0,c.length);b&&(c.length=a);return c}
var ne={na:function(a,b){return cb(a,b)},z:function(a){return Ea(a+16)+16},y:function(a,b,c){(new db(a)).uc(b,c);eb++;throw a;},fa:function(a,b){fb();a=new Date(1E3*E[a>>2]);E[b>>2]=a.getSeconds();E[b+4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);E[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();
c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;E[b+32>>2]=a;a=E[jb()+(a?4:0)>>2];E[b+40>>2]=a;return b},J:function(a,b,c){tc=c;try{var d=vc(a);switch(b){case 0:var e=uc();return 0>e?-28:bc(d.path,d.flags,0,e).qb;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=uc(),d.flags|=e,0;case 12:return e=uc(),xa[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return-1;default:return-28}}catch(f){return"undefined"!==typeof Q&&f instanceof L||t(f),-f.hb}},
ka:function(a,b){try{var c=vc(a);return sc(c.path,b)}catch(d){return"undefined"!==typeof Q&&d instanceof L||t(d),-d.hb}},ma:function(a,b,c){tc=c;try{var d=vc(a);switch(b){case 21509:case 21505:return d.fb?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.fb?0:-59;case 21519:if(!d.fb)return-59;var e=uc();return E[e>>2]=0;case 21520:return d.fb?-28:-59;case 21531:a=e=uc();if(!d.ab.Vc)throw new L(59);return d.ab.Vc(d,b,a);case 21523:return d.fb?0:-59;case 21524:return d.fb?
0:-59;default:t("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof Q&&f instanceof L||t(f),-f.hb}},ia:function(a,b,c,d,e,f){try{a:{f<<=12;var h=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=$d(16384,b);if(!m){l=-48;break a}ae(m,0,b);h=!0}else{var p=Db[e];if(!p){l=-8;break a}var n=f;if(0!==(c&2)&&0===(d&2)&&2!==(p.flags&2097155))throw new L(2);if(1===(p.flags&2097155))throw new L(2);if(!p.ab.Rb)throw new L(43);var q=p.ab.Rb(p,a,b,n,c,d);m=q.bb;h=q.Zb}rc[m]={$c:m,Zc:b,
Zb:h,qb:e,ed:c,flags:d,offset:f};l=m}}return l}catch(v){return"undefined"!==typeof Q&&v instanceof L||t(v),-v.hb}},ga:function(){return 0},ha:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=rc[a];if(d&&b===d.Zc){var e=Db[d.qb];e&&d.ed&2&&e&&e.ab.Sb&&e.ab.Sb(e,A.slice(a,a+b),d.offset,b,d.flags);rc[a]=null;d.Zb&&pd(d.$c)}c=0}return c}catch(f){return"undefined"!==typeof Q&&f instanceof L||t(f),-f.hb}},w:function(a,b,c){tc=c;try{var d=z(a),e=c?uc():0;return bc(d,b,e).qb}catch(f){return"undefined"!==
typeof Q&&f instanceof L||t(f),-f.hb}},la:function(a){try{a=z(a);var b=Hb(a,{parent:!0}).node,c=nb(a),d=Ab(b,c),e=Rb(b,c,!0);if(e)throw new L(e);if(!b.Za.Tb)throw new L(63);if(d.Ab)throw new L(10);try{O.willDeletePath&&O.willDeletePath(a)}catch(f){r("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.Za.Tb(b,c);Lb(d);try{if(O.onDeletePath)O.onDeletePath(a)}catch(f){r("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}return 0}catch(f){return"undefined"!==
typeof Q&&f instanceof L||t(f),-f.hb}},ja:function(a,b){try{return a=z(a),sc(a,b)}catch(c){return"undefined"!==typeof Q&&c instanceof L||t(c),-c.hb}},L:function(a){try{return a=z(a),$b(a),0}catch(b){return"undefined"!==typeof Q&&b instanceof L||t(b),-b.hb}},i:function(a){var b=wc[a];delete wc[a];var c=b.hc,d=b.ub,e=b.rc,f=e.map(function(h){return h.Sc}).concat(e.map(function(h){return h.rd}));Hc([a],f,function(h){var l={};e.forEach(function(m,p){var n=h[p],q=m.Nb,v=m.Rc,k=h[p+e.length],u=m.qd,x=m.sd;
l[m.Nc]={read:function(y){return n.fromWireType(q(v,y))},write:function(y,J){var G=[];u(x,y,k.toWireType(G,J));xc(G)}}});return[{name:b.name,fromWireType:function(m){var p={},n;for(n in l)p[n]=l[n].read(m);d(m);return p},toWireType:function(m,p){for(var n in l)if(!(n in p))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in l)l[n].write(q,p[n]);null!==m&&m.push(d,q);return q},argPackAdvance:8,readValueFromPointer:yc,pb:d}]})},pa:function(a,b,c,d,e){var f=Jc(c);b=R(b);Ic(a,{name:b,fromWireType:function(h){return!!h},
toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=F;else if(2===c)l=xa;else if(4===c)l=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},pb:null})},D:function(a,b,c,d,e,f,h,l,m,p,n,q,v){n=R(n);f=ld(e,f);l&&(l=ld(h,l));p&&(p=ld(m,p));v=ld(q,v);var k=Cc(n);Yc(k,function(){qd("Cannot construct "+n+" due to unbound types",[d])});Hc([a,b,c],d?[d]:[],function(u){u=u[0];if(d){var x=u.cb;var y=x.zb}else y=Vc.prototype;
u=Dc(k,function(){if(Object.getPrototypeOf(this)!==J)throw new Lc("Use 'new' to construct "+n);if(void 0===G.vb)throw new Lc(n+" has no accessible constructor");var w=G.vb[arguments.length];if(void 0===w)throw new Lc("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.vb).toString()+") parameters instead!");return w.apply(this,arguments)});var J=Object.create(y,{constructor:{value:u}});u.prototype=J;var G=new Zc(n,u,J,v,x,f,l,p);x=new id(n,
G,!0,!1);y=new id(n+"*",G,!1,!1);var la=new id(n+" const*",G,!1,!0);Wc[a]={pointerType:y,Jc:la};jd(k,u);return[x,y,la]})},R:function(a,b,c,d,e,f){0<b||t("Assertion failed: undefined");var h=rd(b,c);e=ld(d,e);var l=[f],m=[];Hc([],[a],function(p){p=p[0];var n="constructor "+p.name;void 0===p.cb.vb&&(p.cb.vb=[]);if(void 0!==p.cb.vb[b-1])throw new Lc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+p.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
p.cb.vb[b-1]=function(){qd("Cannot construct "+p.name+" due to unbound types",h)};Hc([],h,function(q){p.cb.vb[b-1]=function(){arguments.length!==b-1&&S(n+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var v=1;v<b;++v)l[v]=q[v].toWireType(m,arguments[v-1]);v=e.apply(null,l);xc(m);return q[0].fromWireType(v)};return[]});return[]})},p:function(a,b,c,d,e,f,h,l){var m=rd(c,d);b=R(b);f=ld(e,f);Hc([],[a],function(p){function n(){qd("Cannot call "+q+" due to unbound types",
m)}p=p[0];var q=p.name+"."+b;l&&p.cb.fd.push(b);var v=p.cb.zb,k=v[b];void 0===k||void 0===k.jb&&k.className!==p.name&&k.Kb===c-2?(n.Kb=c-2,n.className=p.name,v[b]=n):(Xc(v,b,q),v[b].jb[c-2]=n);Hc([],m,function(u){u=td(q,u,p,f,h);void 0===v[b].jb?(u.Kb=c-2,v[b]=u):v[b].jb[c-2]=u;return[]});return[]})},oa:function(a,b){b=R(b);Ic(a,{name:b,fromWireType:function(c){var d=V[c].value;vd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:yc,pb:null})},N:function(a,b,
c){c=Jc(c);b=R(b);Ic(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+bd(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:wd(b,c),pb:null})},C:function(a,b,c,d,e,f){var h=rd(b,c);a=R(a);e=ld(d,e);Yc(a,function(){qd("Cannot call "+a+" due to unbound types",h)},b-1);Hc([],h,function(l){jd(a,td(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},k:function(a,b,c,d,e){function f(p){return p}
b=R(b);-1===e&&(e=4294967295);var h=Jc(c);if(0===d){var l=32-8*c;f=function(p){return p<<l>>>l}}var m=-1!=b.indexOf("unsigned");Ic(a,{name:b,fromWireType:f,toWireType:function(p,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+bd(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+bd(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:xd(b,
h,0!==d),pb:null})},h:function(a,b,c){function d(f){f>>=2;var h=H;return new e(Fa,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);Ic(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Uc:!0})},O:function(a,b){b=R(b);var c="std::string"===b;Ic(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),
m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(A[d+4+h]);m=m.join("")}pd(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");var h=(c&&f?function(){return ua(e)}:function(){return e.length})(),l=Ea(4+h+1);H[l>>2]=h;if(c&&f)C(e,A,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&
(pd(l),S("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<h;++f)A[l+4+f]=e[f];null!==d&&d.push(pd,l);return l},argPackAdvance:8,readValueFromPointer:yc,pb:function(d){pd(d)}})},x:function(a,b,c){c=R(c);if(2===b){var d=wa;var e=ya;var f=za;var h=function(){return D};var l=1}else 4===b&&(d=Aa,e=Ba,f=Ca,h=function(){return H},l=2);Ic(a,{name:c,fromWireType:function(m){for(var p=H[m>>2],n=h(),q,v=m+4,k=0;k<=p;++k){var u=m+4+k*b;if(k==p||0==n[u>>l])v=d(v,u-v),void 0===
q?q=v:(q+=String.fromCharCode(0),q+=v),v=u+b}pd(m);return q},toWireType:function(m,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var n=f(p),q=Ea(4+n+b);H[q>>2]=n>>l;e(p,q+4,n+b);null!==m&&m.push(pd,q);return q},argPackAdvance:8,readValueFromPointer:yc,pb:function(m){pd(m)}})},j:function(a,b,c,d,e,f){wc[a]={name:R(b),hc:ld(c,d),ub:ld(e,f),rc:[]}},d:function(a,b,c,d,e,f,h,l,m,p){wc[a].rc.push({Nc:R(b),Sc:c,Nb:ld(d,e),Rc:f,rd:h,qd:ld(l,m),sd:p})},qa:function(a,b){b=R(b);Ic(a,
{Yc:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ra:function(a){delete Hd[a-1]},n:function(a,b,c){a=W(a);b=yd(b,"emval::as");var d=[],e=U(d);E[c>>2]=e;return b.toWireType(d,a)},za:function(a,b,c,d){a=W(a);c=zd(b,c);for(var e=Array(b),f=0;f<b;++f){var h=c[f];e[f]=h.readValueFromPointer(d);d+=h.argPackAdvance}a=a.apply(void 0,e);return U(a)},t:function(a,b,c,d){a=Cd[a];b=W(b);c=Bd(c);a(b,c,null,d)},I:vd,Aa:function(a,b){a=W(a);b=W(b);return a==b},xa:function(a){if(0===
a)return U(Dd());a=Bd(a);return U(Dd()[a])},s:function(a,b){b=zd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+Cc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+
h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Yc||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=sd(e).apply(null,f);return Ed(a)},ya:function(a){a=Bd(a);return U(g[a])},o:function(a,b){a=W(a);b=W(b);return U(a[b])},S:function(a){4<a&&(V[a].jc+=1)},B:function(a,b,c,d){a=W(a);var e=Fd[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(yd,g,U);Fd[b]=e}return e(a,c,d)},va:function(){return U([])},W:function(a){return U(Bd(a))},wa:function(){return U({})},Ca:function(a){xc(V[a].value);
vd(a)},v:function(a,b,c){a=W(a);b=W(b);c=W(c);a[b]=c},q:function(a,b){a=yd(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},Ba:function(a){a=W(a);return U(typeof a)},l:function(){t()},H:cb,r:function(a,b,c){Xd.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,Xd.push(d?Ha[c++>>1]:E[c]),++c;return $a[a].apply(null,Xd)},ta:Gd,c:function(a,b){Y(a,b||1);throw"longjmp";},Z:function(a,b,c){A.copyWithin(a,b,b+c)},_:function(a){var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=
2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{qa.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ia();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},sa:function(a,b,c,d,e){function f(B){Jd(B,h,p,n,m)}function h(B,T){Kd(B,T.response,function(P){u?I.get(u)(P):b&&b(P)},function(P){u?I.get(u)(P):b&&b(P)})}function l(B){Jd(B,q,p,n,m)}function m(B){J?I.get(J)(B):e&&e(B)}function p(B){x?I.get(x)(B):c&&c(B)}function n(B){y?I.get(y)(B):
d&&d(B)}function q(B){u?I.get(u)(B):b&&b(B)}noExitRuntime=!0;var v=a+112,k=z(v),u=H[v+36>>2],x=H[v+40>>2],y=H[v+44>>2],J=H[v+48>>2],G=H[v+52>>2],la=!!(G&4),w=!!(G&32);G=!!(G&16);if("EM_IDB_STORE"===k)k=H[v+84>>2],Kd(a,A.slice(k,k+H[v+88>>2]),q,p);else if("EM_IDB_DELETE"===k)Md(a,q,p);else if(G){if(w)return 0;Jd(a,la?h:q,p,n,m)}else Ld(a,q,w?p:la?f:l);return a},da:function(a,b){try{var c=0;Od().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=
0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof Q&&d instanceof L||t(d),d.hb}},ea:function(a,b){try{var c=Od();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0}catch(e){return"undefined"!==typeof Q&&e instanceof L||t(e),e.hb}},A:function(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);ra=!0}fa(a,new be(a))},u:function(a){try{var b=vc(a);dc(b);return 0}catch(c){return"undefined"!==typeof Q&&c instanceof L||t(c),c.hb}},ca:function(a,b){try{var c=vc(a);F[b>>
0]=c.fb?2:N(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof L||t(d),d.hb}},M:function(a,b,c,d){try{a:{for(var e=vc(a),f=a=0;f<c;f++){var h=E[b+(8*f+4)>>2],l=e,m=E[b+8*f>>2],p=h,n=void 0,q=F;if(0>p||0>n)throw new L(28);if(null===l.qb)throw new L(8);if(1===(l.flags&2097155))throw new L(8);if(N(l.node.mode))throw new L(31);if(!l.ab.read)throw new L(28);var v="undefined"!==typeof n;if(!v)n=l.position;else if(!l.seekable)throw new L(70);var k=l.ab.read(l,
q,m,p,n);v||(l.position+=k);var u=k;if(0>u){var x=-1;break a}a+=u;if(u<h)break}x=a}E[d>>2]=x;return 0}catch(y){return"undefined"!==typeof Q&&y instanceof L||t(y),y.hb}},T:function(a,b,c,d,e){try{var f=vc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;ec(f,a,d);Za=[f.position>>>0,(K=f.position,1<=+Math.abs(K)?0<K?(Math.min(+Math.floor(K/4294967296),4294967295)|0)>>>0:~~+Math.ceil((K-+(~~K>>>0))/4294967296)>>>0:0)];E[e>>2]=Za[0];E[e+4>>2]=Za[1];f.bc&&0===a&&0===d&&
(f.bc=null);return 0}catch(h){return"undefined"!==typeof Q&&h instanceof L||t(h),h.hb}},K:function(a,b,c,d){try{a:{for(var e=vc(a),f=a=0;f<c;f++){var h=fc(e,F,E[b+8*f>>2],E[b+(8*f+4)>>2],void 0);if(0>h){var l=-1;break a}a+=h}l=a}E[d>>2]=l;return 0}catch(m){return"undefined"!==typeof Q&&m instanceof L||t(m),m.hb}},a:function(){return oa|0},Da:function(){var a=self.navigator.userAgent,b=ua(a)+1,c=Ea(b);C(a,A,c,b);return c},$:Qd,E:ce,g:de,m:ee,G:fe,Y:ge,e:he,f:ie,F:je,X:ke,V:le,U:me,ua:function(a){fb();
var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?E[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=
b.getDate();E[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},b:function(a){oa=a|0},P:Wd,aa:function(a,b,c,d){return Wd(a,b,c,d)},ba:function(a){switch(a){case 30:return 16384;case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:return 200809;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}return-1},Q:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;qa=g.asm.Ea;Ia();I=g.asm.Ia;Ta("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){r("failed to asynchronously prepare wasm: "+f);t(f)})}var d={a:ne};Sa("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return pa||"function"!==typeof WebAssembly.instantiateStreaming||
Ua()||"function"!==typeof fetch?c(b):fetch(Va,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){r("wasm streaming compile failed: "+f);r("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var Na=g.___wasm_call_ctors=function(){return(Na=g.___wasm_call_ctors=g.asm.Fa).apply(null,arguments)},pd=g._free=function(){return(pd=g._free=g.asm.Ga).apply(null,arguments)},Ea=g._malloc=function(){return(Ea=g._malloc=g.asm.Ha).apply(null,arguments)},od=g.___getTypeName=function(){return(od=g.___getTypeName=g.asm.Ja).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.Ka).apply(null,arguments)};
var ae=g._memset=function(){return(ae=g._memset=g.asm.La).apply(null,arguments)},jb=g.__get_tzname=function(){return(jb=g.__get_tzname=g.asm.Ma).apply(null,arguments)},ib=g.__get_daylight=function(){return(ib=g.__get_daylight=g.asm.Na).apply(null,arguments)},hb=g.__get_timezone=function(){return(hb=g.__get_timezone=g.asm.Oa).apply(null,arguments)},Z=g.stackSave=function(){return(Z=g.stackSave=g.asm.Pa).apply(null,arguments)},oe=g.stackRestore=function(){return(oe=g.stackRestore=g.asm.Qa).apply(null,
arguments)},Y=g._setThrew=function(){return(Y=g._setThrew=g.asm.Ra).apply(null,arguments)},$d=g._memalign=function(){return($d=g._memalign=g.asm.Sa).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.Ta).apply(null,arguments)};g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.Ua).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Va).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.Wa).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.Xa).apply(null,arguments)};function he(a,b){var c=Z();try{I.get(a)(b)}catch(d){oe(c);if(d!==d+0&&"longjmp"!==d)throw d;Y(1,0)}}function de(a,b){var c=Z();try{return I.get(a)(b)}catch(d){oe(c);if(d!==d+0&&"longjmp"!==d)throw d;Y(1,0)}}function ie(a,b,c){var d=Z();try{I.get(a)(b,c)}catch(e){oe(d);if(e!==e+0&&"longjmp"!==e)throw e;Y(1,0)}}
function ee(a,b,c){var d=Z();try{return I.get(a)(b,c)}catch(e){oe(d);if(e!==e+0&&"longjmp"!==e)throw e;Y(1,0)}}function fe(a,b,c,d){var e=Z();try{return I.get(a)(b,c,d)}catch(f){oe(e);if(f!==f+0&&"longjmp"!==f)throw f;Y(1,0)}}function je(a,b,c,d){var e=Z();try{I.get(a)(b,c,d)}catch(f){oe(e);if(f!==f+0&&"longjmp"!==f)throw f;Y(1,0)}}function ge(a,b,c,d,e){var f=Z();try{return I.get(a)(b,c,d,e)}catch(h){oe(f);if(h!==h+0&&"longjmp"!==h)throw h;Y(1,0)}}
function ke(a,b,c,d,e){var f=Z();try{I.get(a)(b,c,d,e)}catch(h){oe(f);if(h!==h+0&&"longjmp"!==h)throw h;Y(1,0)}}function ce(a){var b=Z();try{return I.get(a)()}catch(c){oe(b);if(c!==c+0&&"longjmp"!==c)throw c;Y(1,0)}}function le(a,b,c,d,e,f,h){var l=Z();try{I.get(a)(b,c,d,e,f,h)}catch(m){oe(l);if(m!==m+0&&"longjmp"!==m)throw m;Y(1,0)}}function me(a,b,c,d,e,f,h,l,m,p){var n=Z();try{I.get(a)(b,c,d,e,f,h,l,m,p)}catch(q){oe(n);if(q!==q+0&&"longjmp"!==q)throw q;Y(1,0)}}g.addRunDependency=Sa;
g.removeRunDependency=Ta;g.FS_createPath=jc;g.FS_createDataFile=lc;g.FS_createPreloadedFile=pc;g.FS_createLazyFile=oc;g.FS_createDevice=mc;g.FS_unlink=$b;var pe;function be(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ra=function qe(){pe||re();pe||(Ra=qe)};
function re(){function a(){if(!pe&&(pe=!0,g.calledRun=!0,!ra)){g.noFSInit||hc||(hc=!0,gc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?mc("/dev","stdin",g.stdin):Zb("/dev/tty","/dev/stdin"),g.stdout?mc("/dev","stdout",null,g.stdout):Zb("/dev/tty","/dev/stdout"),g.stderr?mc("/dev","stderr",null,g.stderr):Zb("/dev/tty1","/dev/stderr"),bc("/dev/stdin",0),bc("/dev/stdout",1),bc("/dev/stderr",1));ab(Ka);Gb=!1;ab(La);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==
typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();Ma.unshift(b)}ab(Ma)}}if(!(0<Pa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Oa();ab(Ja);0<Pa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=re;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();re();


  return BlinkIDImageCaptureWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkIDImageCaptureWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkIDImageCaptureWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkIDImageCaptureWasmSDK"] = BlinkIDImageCaptureWasmSDK;
